### ISSUE TITLE
Collection which contains itself fails on full view

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1076]
Collection which contains itself fails on full view on Plone 5.0rc3

```
- Expression: "view/enabled"
 - Filename:   ... layout-2.5.15-py2.7.egg/plone/app/layout/viewlets/toc.pt
 - Location:   (line 2: col 19)
 - Source:     tal:condition="view/enabled"
                              ^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fad596ad510>
               views: <ViewMapper - at 0x7fad59832ed0>
               modules: <instance - at 0x7fad6a493050>
               args: <tuple - at 0x7fad76a2e050>
               here: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               user: <ImplicitAcquisitionWrapper - at 0x7fad5d06d460>
               nothing: <NoneType - at 0x7fad76829920>
               container: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               request: <instance - at 0x7fad591145f0>
               wrapped_repeat: <SafeMapping - at 0x7fad59445208>
               traverse_subpath: <list - at 0x7fad595d1170>
               default: <object - at 0x7fad76a04510>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               view: <TableOfContentsViewlet plone.tableofcontents at 0x7fad598324d0>
               translate: <function translate at 0x7fad5915b1b8>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fad5d5fcbe0>
               options: {...} (0)
               target_language: de
Traceback (most recent call last):
  File "/home/vagrant/Eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/vagrant/Eggs/plone.app.layout-2.5.15-py2.7.egg/plone/app/layout/viewlets/common.py", line 59, in render
    return self.index()
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/vagrant/Eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/vagrant/Eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/vagrant/Eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "1ad4de5f3e3b1b05eda3dc19f854dd5f.py", line 90, in render
  File "/home/vagrant/Eggs/five.pt-2.2.3-py2.7.egg/five/pt/expressions.py", line 154, in __call__
    base = self.traverse(base, request, path_items)
  File "/home/vagrant/Eggs/five.pt-2.2.3-py2.7.egg/five/pt/expressions.py", line 126, in traverse
    base, name, path_items[i:], request=request
  File "/home/vagrant/Eggs/zope.traversing-3.13.2-py2.7.egg/zope/traversing/adapters.py", line 131, in traversePathElement
    traversable = ITraversable(obj, None)
  File "/home/vagrant/Eggs/zope.component-3.9.5-py2.7.egg/zope/component/hookable.py", line 33, in __call__
    return self.__implementation(*args, **kw)
  File "/home/vagrant/Eggs/zope.component-3.9.5-py2.7.egg/zope/component/hooks.py", line 104, in adapter_hook
    return siteinfo.adapter_hook(interface, object, name, default)
RuntimeError: maximum recursion depth exceeded

 - Expression: "view/enabled"
 - Filename:   ... layout-2.5.15-py2.7.egg/plone/app/layout/viewlets/toc.pt
 - Location:   (line 2: col 19)
 - Source:     tal:condition="view/enabled"
                              ^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fad596ad510>
               views: <ViewMapper - at 0x7fad59832ed0>
               modules: <instance - at 0x7fad6a493050>
               args: <tuple - at 0x7fad76a2e050>
               here: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               user: <ImplicitAcquisitionWrapper - at 0x7fad5d06d460>
               nothing: <NoneType - at 0x7fad76829920>
               container: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               request: <instance - at 0x7fad591145f0>
               wrapped_repeat: <SafeMapping - at 0x7fad59445208>
               traverse_subpath: <list - at 0x7fad595d1170>
               default: <object - at 0x7fad76a04510>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               view: <TableOfContentsViewlet plone.tableofcontents at 0x7fad598324d0>
               translate: <function translate at 0x7fad5915b1b8>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fad5d5fcbe0>
               options: {...} (0)
               target_language: de


2015-09-24 16:01:41 ERROR plone.app.viewletmanager rendering of plone.belowcontentbody in plone.abovecontenttitle.documentactions fails: maximum recursion depth exceeded

 - Expression: "view/actions"
 - Filename:   ... -py2.7.egg/plone/app/layout/viewlets/document_actions.pt
 - Location:   (line 7: col 39)
 - Source:     ... :docactions tal:condition="view/actions">
                                              ^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fad597d0050>
               views: <ViewMapper - at 0x7fad59647490>
               modules: <instance - at 0x7fad6a493050>
               args: <tuple - at 0x7fad76a2e050>
               here: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               user: <ImplicitAcquisitionWrapper - at 0x7fad5d06d460>
               nothing: <NoneType - at 0x7fad76829920>
               container: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               request: <instance - at 0x7fad591145f0>
               wrapped_repeat: <SafeMapping - at 0x7fad59460c58>
               traverse_subpath: <list - at 0x7fad595ec710>
               default: <object - at 0x7fad76a04510>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               view: <DocumentActionsViewlet plone.abovecontenttitle.documentactions at 0x7fad59647450>
               translate: <function translate at 0x7fad591fc668>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fad5d5fcbe0>
               options: {...} (0)
               target_language: de
Traceback (most recent call last):
  File "/home/vagrant/Eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/vagrant/Eggs/plone.app.layout-2.5.15-py2.7.egg/plone/app/layout/viewlets/common.py", line 59, in render
    return self.index()
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/vagrant/Eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/vagrant/Eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/vagrant/Eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "75a874dd70620b51f442dbeaba0134ce.py", line 123, in render
  File "/home/vagrant/Eggs/five.pt-2.2.3-py2.7.egg/five/pt/expressions.py", line 154, in __call__
    base = self.traverse(base, request, path_items)
  File "/home/vagrant/Eggs/five.pt-2.2.3-py2.7.egg/five/pt/expressions.py", line 126, in traverse
    base, name, path_items[i:], request=request
  File "/home/vagrant/Eggs/zope.traversing-3.13.2-py2.7.egg/zope/traversing/adapters.py", line 131, in traversePathElement
    traversable = ITraversable(obj, None)
  File "/home/vagrant/Eggs/zope.component-3.9.5-py2.7.egg/zope/component/hookable.py", line 33, in __call__
    return self.__implementation(*args, **kw)
  File "/home/vagrant/Eggs/zope.component-3.9.5-py2.7.egg/zope/component/hooks.py", line 104, in adapter_hook
    return siteinfo.adapter_hook(interface, object, name, default)
RuntimeError: maximum recursion depth exceeded

 - Expression: "view/actions"
 - Filename:   ... -py2.7.egg/plone/app/layout/viewlets/document_actions.pt
 - Location:   (line 7: col 39)
 - Source:     ... :docactions tal:condition="view/actions">
                                              ^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fad597d0050>
               views: <ViewMapper - at 0x7fad59647490>
               modules: <instance - at 0x7fad6a493050>
               args: <tuple - at 0x7fad76a2e050>
               here: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               user: <ImplicitAcquisitionWrapper - at 0x7fad5d06d460>
               nothing: <NoneType - at 0x7fad76829920>
               container: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               request: <instance - at 0x7fad591145f0>
               wrapped_repeat: <SafeMapping - at 0x7fad59460c58>
               traverse_subpath: <list - at 0x7fad595ec710>
               default: <object - at 0x7fad76a04510>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0x7fad5cf13e60>
               view: <DocumentActionsViewlet plone.abovecontenttitle.documentactions at 0x7fad59647450>
               translate: <function translate at 0x7fad591fc668>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fad5d5fcbe0>
               options: {...} (0)
               target_language: de


2015-09-24 16:01:41 ERROR Zope.SiteErrorLog 1443103301.990.201268843505 http://localhost:8008/Plone2/123456/full_view
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 255, in render
  Module f6def51bf04d9525b123b1b5f5b72ed5.py, line 1223, in render_master
  Module f6def51bf04d9525b123b1b5f5b72ed5.py, line 420, in render_content
  Module 3b42e4e4ce265425558246eda7325829.py, line 243, in __fill_content_core
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module f2af528485cd8d483bb43f9988c07bb2.py, line 457, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module f2af528485cd8d483bb43f9988c07bb2.py, line 457, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module f2af528485cd8d483bb43f9988c07bb2.py, line 457, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module f2af528485cd8d483bb43f9988c07bb2.py, line 457, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module f2af528485cd8d483bb43f9988c07bb2.py, line 457, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module f2af528485cd8d483bb43f9988c07bb2.py, line 457, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module f2af528485cd8d483bb43f9988c07bb2.py, line 457, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module f2af528485cd8d483bb43f9988c07bb2.py, line 457, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module f2af528485cd8d483bb43f9988c07bb2.py, line 457, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module f2af528485cd8d483bb43f9988c07bb2.py, line 457, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 171, in render
  Module f2af528485cd8d483bb43f9988c07bb2.py, line 457, in render
  Module 3b42e4e4ce265425558246eda7325829.py, line 166, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 437, in render_content_core
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 295, in render_listing
  Module 3b42e4e4ce265425558246eda7325829.py, line 154, in __fill_entries
  Module b1b6fa02ea2ea5b86e36d2e0bdb01f3a.py, line 1429, in render_entries
  Module 3b42e4e4ce265425558246eda7325829.py, line 114, in __fill_entry
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
RuntimeError: maximum recursion depth exceeded in cmp

 - Expression: "obj/@@full_view_item | nothing"
 - Filename:   ... gg/plone/app/contenttypes/browser/templates/full_view.pt
 - Location:   (line 17: col 71)
 - Source:     ... eplace="structure obj/@@full_view_item | nothing" />
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "view/batch"
 - Filename:   ... .egg/plone/app/contenttypes/browser/templates/listing.pt
 - Location:   (line 22: col 31)
 - Source:     <tal:results define="batch view/batch">
                                          ^^^^^^^^^^
 - Arguments:  modules: <instance - at 0x7fad6a493050>
               context_state: <ContextState plone_context_state at 0x7fad59434810>
               rendering_error: <list - at 0x7fad5930db48>
               plone_view: <Plone plone at 0x7fad59434250>
               item_url: http://localhost:8008/Plone2/news
               container: <ImplicitAcquisitionWrapper news at 0x7fad5d0edb90>
               item_macro: <Macro - at 0x7fad59204ad0>
               wrapped_repeat: <SafeMapping - at 0x7fad5921ac58>
               portal_url: http://localhost:8008/Plone2
               traverse_subpath: <list - at 0x7fad5930d4d0>
               template: <ViewPageTemplateFile - at 0x7fad596f1790>
               translate: <function translate at 0x7fad591fc8c0>
               repeat: {...} (0)
               views: <ViewMapper - at 0x7fad59647c10>
               args: <tuple - at 0x7fad76a2e050>
               here: <ImplicitAcquisitionWrapper news at 0x7fad5d0edb90>
               site_properties: <ImplicitAcquisitionWrapper site_properties at 0x7fad5d0ed280>
               user: <ImplicitAcquisitionWrapper - at 0x7fad5d06d460>
               nothing: <NoneType - at 0x7fad76829920>
               lang: de
               dummy: <NoneType - at 0x7fad76829920>
               default: <object - at 0x7fad76a04510>
               request: <instance - at 0x7fad591145f0>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper news at 0x7fad5d0edb90>
               portal_state: <PortalState plone_portal_state at 0x7fad594347d0>
               plone_layout: <LayoutPolicy plone_layout at 0x7fad59434850>
               checkPermission: <instancemethod checkPermission at 0x7fad5d085690>
               view: <SimpleViewClass from /home/vagrant/Eggs/plone.app.contenttypes-1.2.3-py2.7.egg/plone/app/contenttypes/browser/templates/listing.pt listing_view at 0x7fad59434450>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fad5d5fcbe0>
               options: {...} (0)
               target_language: de

```

**Comment by hvelarde** [comment]
a collection that contains itself… what can possibly go wrong? :-)

**Comment by tomgross** [comment]
Yeah, but we should catch this case rather then giving a really ugly traceback.

**Comment by vangheem** [comment]
Fix in this PR: https://github.com/plone/plone.app.contenttypes/pull/272
