### ISSUE TITLE
plone 5.0rc3 /zope has locked me out

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1107]
pls check my sites at demo.kousalam.com:8090 , 128.199.230.56:8090

i am unable to login into the site using admin , username and password. i had created a user siteadmin through the site and am able to login through that. but siteadmin does not have any rights currently. i tried to create new user but i am getting the following error. there are two attempts to create add user:

ssp@mail:/opt/plone/zinstance$ sudo bin/plonectl adduser admin
instance: usage: adduser <name> <password>
ssp@mail:/opt/plone/zinstance$ sudo bin/plonectl adduser admin admin@123
instance: 2015-09-28 23:43:29 ERROR zc.lockfile Error locking file /opt/plone/zi                                                                                        nstance/var/filestorage/Data.fs.lock; pid=15464
Traceback (most recent call last):
  File "/opt/plone/buildout-cache/eggs/zc.lockfile-1.0.2-py2.7.egg/zc/lockfile/_                                                                                        _init__.py", line 84, in __init__
    _lock_file(fp)
  File "/opt/plone/buildout-cache/eggs/zc.lockfile-1.0.2-py2.7.egg/zc/lockfile/_                                                                                        _init__.py", line 59, in _lock_file
    raise LockError("Couldn't lock %r" % file.name)
LockError: Couldn't lock '/opt/plone/zinstance/var/filestorage/Data.fs.lock'
Traceback (most recent call last):
  File "/opt/plone/zinstance/parts/instance/bin/interpreter", line 268, in <modu                                                                                        le>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/__init__.py                                                                                        ", line 51, in app
    startup()
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/__init__.py                                                                                        ", line 47, in startup
    _startup()
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/startup                                                                                        .py", line 81, in startup
    DB = dbtab.getDatabase('/', is_root=1)
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/dat                                                                                        atypes.py", line 287, in getDatabase
    db = factory.open(name, self.databases)
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/dat                                                                                        atypes.py", line 185, in open
    DB = self.createDB(database_name, databases)
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/dat                                                                                        atypes.py", line 182, in createDB
    return ZODBDatabase.open(self, databases)
  File "/opt/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/                                                                                        config.py", line 101, in open
    storage = section.storage.open()
  File "/opt/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/                                                                                        config.py", line 183, in open
    base = self.config.base.open()
  File "/opt/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/                                                                                        config.py", line 177, in open
    return FileStorage(config.path, **options)
  File "/opt/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/                                                                                        FileStorage/FileStorage.py", line 125, in __init__
    self._lock_file = LockFile(file_name + '.lock')
  File "/opt/plone/buildout-cache/eggs/zc.lockfile-1.0.2-py2.7.egg/zc/lockfile/_                                                                                        _init__.py", line 84, in __init__
    _lock_file(fp)
  File "/opt/plone/buildout-cache/eggs/zc.lockfile-1.0.2-py2.7.egg/zc/lockfile/_                                                                                        _init__.py", line 59, in _lock_file
    raise LockError("Couldn't lock %r" % file.name)
zc.lockfile.LockError: Couldn't lock '/opt/plone/zinstance/var/filestorage/Data.                                                                                        fs.lock'
ssp@mail:/opt/plone/zinstance$ sudo bin/plonectl adduser sudhan77 kousalam
instance: 2015-09-28 23:44:55 ERROR zc.lockfile Error locking file /opt/plone/zinstance/var/filestorage/Data.fs.lock; pid=15464
Traceback (most recent call last):
  File "/opt/plone/buildout-cache/eggs/zc.lockfile-1.0.2-py2.7.egg/zc/lockfile/__init__.py", line 84, in __init__
    _lock_file(fp)
  File "/opt/plone/buildout-cache/eggs/zc.lockfile-1.0.2-py2.7.egg/zc/lockfile/__init__.py", line 59, in _lock_file
    raise LockError("Couldn't lock %r" % file.name)
LockError: Couldn't lock '/opt/plone/zinstance/var/filestorage/Data.fs.lock'
Traceback (most recent call last):
  File "/opt/plone/zinstance/parts/instance/bin/interpreter", line 268, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/__init__.py", line 51, in app
    startup()
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/startup.py", line 81, in startup
    DB = dbtab.getDatabase('/', is_root=1)
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/datatypes.py", line 287, in getDatabase
    db = factory.open(name, self.databases)
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/datatypes.py", line 185, in open
    DB = self.createDB(database_name, databases)
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/datatypes.py", line 182, in createDB
    return ZODBDatabase.open(self, databases)
  File "/opt/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/config.py", line 101, in open
    storage = section.storage.open()
  File "/opt/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/config.py", line 183, in open
    base = self.config.base.open()
  File "/opt/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/config.py", line 177, in open
    return FileStorage(config.path, **options)
  File "/opt/plone/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/FileStorage/FileStorage.py", line 125, in __init__
    self._lock_file = LockFile(file_name + '.lock')
  File "/opt/plone/buildout-cache/eggs/zc.lockfile-1.0.2-py2.7.egg/zc/lockfile/__init__.py", line 84, in __init__
    _lock_file(fp)
  File "/opt/plone/buildout-cache/eggs/zc.lockfile-1.0.2-py2.7.egg/zc/lockfile/__init__.py", line 59, in _lock_file
    raise LockError("Couldn't lock %r" % file.name)
zc.lockfile.LockError: Couldn't lock '/opt/plone/zinstance/var/filestorage/Data.fs.lock'
ssp@mail:/opt/plone/zinstance$

**Comment by davisagli** [comment]
If you're not running Plone using ZEO, then you have to stop the Zope instance before you can run the adduser script.

**Comment by sudhan77** [comment]
david thanks. i have understood this. but my main problem was that the site
has locked me out. i am unable to get access to the management interface.
the only access i have is through a user i created. but the user does not
have any rights as yet. how do i get access to the ZMI for the site

On Mon, Sep 28, 2015 at 11:52 PM, David Glick <notifications@github.com>
wrote:

> If you're not running Plone using ZEO, then you have to stop the Zope
> instance before you can run the adduser script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/Products.CMFPlone/issues/1107#issuecomment-143833743>
> .
>



-- 
Sudhanshu

**Comment by sudhan77** [comment]
the following is  the details from adminPassword.txt . it does not give me
access to the ZMI

Use the account information below to log into the Zope Management Interface
The account has full 'Manager' privileges.

  Username: admin
  Password: admin@1234

This account is created when the object database is initialized. If you
change
the password later (which you should!), you'll need to use the new password.

Use this account only to create Plone sites and initial users. Do not use it
for routine login or maintenance.





On Tue, Sep 29, 2015 at 7:51 AM, Sudhanshu Sekhar Pani <sudhan77@gmail.com>
wrote:

> david thanks. i have understood this. but my main problem was that the
> site has locked me out. i am unable to get access to the management
> interface. the only access i have is through a user i created. but the user
> does not have any rights as yet. how do i get access to the ZMI for the site
>
> On Mon, Sep 28, 2015 at 11:52 PM, David Glick <notifications@github.com>
> wrote:
>
>> If you're not running Plone using ZEO, then you have to stop the Zope
>> instance before you can run the adduser script.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/plone/Products.CMFPlone/issues/1107#issuecomment-143833743>
>> .
>>
>
>
>
> --
> Sudhanshu
>



-- 
Sudhanshu

**Comment by mauritsvanrees** [comment]
Like David said, you first need to stop your Zope instance. So probably `sudo bin/plonectl stop`.  Then run the adduser command and then start the Zope instance again.

One other hint: when the adduser command exits with a message 'Created user: None' then creation has failed: a user with the given id already exists and the command will not overwrite it.  Then simply run the command again with another user id.
