### ISSUE TITLE
Problems with Plone 5

### ISSUE THREAD

**Issue by dtordable** [plone/Products.CMFPlone#1117]
I've recently installed the system that fails when you create a folder called /blog, using collective.blog.star, Products.PloneFormGen and so. The data of the site is saved on a relational database using RelStorage for that purpose. 

The basic problem arrives when you surf to that folder and you touch the sidebar. Shows the error "Error while rendering plone.contentviews" without showing the desired links. Here it is the traceback that Plone shouts:
Last login: Wed Sep 30 21:54:05 2015 from 84.78.20.232
FreeBSD 10.2-RELEASE (GENERIC) #0 r286666: Wed Aug 12 15:26:37 UTC 2015

server    : 284451
ip        : 91.121.159.97
hostname  : ns359895.ip-91-121-159.eu

Agent pid 6103
[plone@danieltordable ~]$ cd danieltordable.net/
[plone@danieltordable ~/danieltordable.net]$ bin/plonectl fg
instance: 2015-09-30 21:55:16 INFO ZServer HTTP server started at Wed Sep 30 21:55:16 2015
        Hostname: 0.0.0.0
        Port: 8080
2015-09-30 21:55:30 INFO Products.PloneFormGen gpg_subprocess initialized, using /usr/local/bin/gpg
2015-09-30 21:55:54 INFO Plone OpenID system packages not installed, OpenID support not available
2015-09-30 21:56:12 INFO PloneFormGen Patching plone.app.portlets ColumnPortletManagerRenderer to not catch Retry exceptions
2015-09-30 21:56:12 INFO Zope Ready to handle requests
2015-09-30 21:58:02 INFO plone.app.theming.policy local cache invalidated on thread 34743707648
2015-09-30 21:58:02 INFO plone.app.theming.policy initializing local cache on thread 34743707648 for http://www.danieltordable.net::None
2015-09-30 21:58:25 ERROR plone.app.viewletmanager rendering of plone.toolbar in plone.contentviews fails: portal_discussion

 - Expression: "provider:plone.contentmenu"
 - Filename:   ... 5.15-py2.7.egg/plone/app/layout/viewlets/contentviews.pt
 - Location:   (line 9: col 32)
 - Source:     ... :replace="structure provider:plone.contentmenu" />
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "view/menu"
 - Filename:   ... enu-2.1.6-py2.7.egg/plone/app/contentmenu/contentmenu.pt
 - Location:   (line 1: col 37)
 - Source:     ... tentactionmenus define="menu view/menu;"
                                                ^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x817d5a590>
               views: <ViewMapper - at 0x817d5a390>
               modules: <instance - at 0x80b532b90>
               args: <tuple - at 0x80064c050>
               here: <ImplicitAcquisitionWrapper blog at 0x8170c6b90>
               user: <ImplicitAcquisitionWrapper - at 0x8139ff550>
               nothing: <NoneType - at 0x800dcbef8>
               container: <ImplicitAcquisitionWrapper blog at 0x8170c6b90>
               request: <instance - at 0x813f7d998>
               wrapped_repeat: <SafeMapping - at 0x814d9baa0>
               traverse_subpath: <list - at 0x819262320>
               default: <object - at 0x8006a2550>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper blog at 0x8170c6b90>
               view: <ContentMenuProvider plone.contentmenu at 0x817d5aa50>
               translate: <function translate at 0x81902de60>
               root: <ImplicitAcquisitionWrapper Zope at 0x81326c2d0>
               options: {...} (0)
               target_language: <NoneType - at 0x800dcbef8>
Traceback (most recent call last):
  File "/home/plone/danieltordable.net/eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/plone/danieltordable.net/eggs/plone.app.layout-2.5.15-py2.7.egg/plone/app/layout/viewlets/common.py", line 59, in render
    return self.index()
  File "/home/plone/danieltordable.net/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/plone/danieltordable.net/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/plone/danieltordable.net/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/plone/danieltordable.net/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/plone/danieltordable.net/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/plone/danieltordable.net/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/plone/danieltordable.net/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "d1eca465ea5b1fedb3e1e22fb6134dc2.py", line 157, in render
  File "/home/plone/danieltordable.net/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/expressions.py", line 74, in render_content_provider
    return cp.render()
  File "/home/plone/danieltordable.net/eggs/plone.app.contentmenu-2.1.6-py2.7.egg/plone/app/contentmenu/view.py", line 18, in render
    return self.index()
  File "/home/plone/danieltordable.net/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/plone/danieltordable.net/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/plone/danieltordable.net/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/plone/danieltordable.net/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/plone/danieltordable.net/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/plone/danieltordable.net/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/plone/danieltordable.net/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/plone/danieltordable.net/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "69aeeb5c944a5cfbee97522b84521039.py", line 102, in render
  File "/home/plone/danieltordable.net/eggs/five.pt-2.2.3-py2.7.egg/five/pt/expressions.py", line 161, in __call__
    return base()
  File "/home/plone/danieltordable.net/eggs/plone.app.contentmenu-2.1.6-py2.7.egg/plone/app/contentmenu/view.py", line 27, in menu
    items = menu.getMenuItems(self.context, self.request)
  File "/home/plone/danieltordable.net/eggs/zope.browsermenu-3.9.1-py2.7.egg/zope/browsermenu/menu.py", line 53, in getMenuItems
    if item.available():
  File "/home/plone/danieltordable.net/eggs/plone.memoize-1.1.1-py2.7.egg/plone/memoize/instance.py", line 51, in memogetter
    val=func(*args, **kwargs)
  File "/home/plone/danieltordable.net/eggs/plone.app.contentmenu-2.1.6-py2.7.egg/plone/app/contentmenu/menu.py", line 192, in available
    contextLayouts = context.getAvailableLayouts()
  File "/home/plone/danieltordable.net/eggs/Products.CMFDynamicViewFTI-4.1.3-py2.7.egg/Products/CMFDynamicViewFTI/browserdefault.py", line 214, in getAvailableLayouts
    name=mid
  File "/home/plone/danieltordable.net/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 120, in queryMultiAdapter
    return sitemanager.queryMultiAdapter(objects, interface, name, default)
  File "/home/plone/danieltordable.net/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 238, in queryMultiAdapter
    objects, interface, name, default)
  File "/home/plone/danieltordable.net/eggs/zope.interface-3.6.7-py2.7-freebsd-10.2-RELEASE-amd64.egg/zope/interface/adapter.py", line 532, in queryMultiAdapter
    result = factory(*objects)
  File "/home/plone/danieltordable.net/eggs/collective.blog.view-1.5.2-py2.7.egg/collective/blog/view/blog.py", line 19, in __init__
    self.portal_discussion = getToolByName(self.context, 'portal_discussion')
  File "<string>", line 13, in check_getToolByName
  File "/home/plone/danieltordable.net/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/utils.py", line 120, in getToolByName
    raise AttributeError, name
AttributeError: portal_discussion

 - Expression: "provider:plone.contentmenu"
 - Filename:   ... 5.15-py2.7.egg/plone/app/layout/viewlets/contentviews.pt
 - Location:   (line 9: col 32)
 - Source:     ... :replace="structure provider:plone.contentmenu" />
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "view/menu"
 - Filename:   ... enu-2.1.6-py2.7.egg/plone/app/contentmenu/contentmenu.pt
 - Location:   (line 1: col 37)
 - Source:     ... tentactionmenus define="menu view/menu;"
                                                ^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x817d5a590>
               views: <ViewMapper - at 0x817d5a390>
               modules: <instance - at 0x80b532b90>
               args: <tuple - at 0x80064c050>
               here: <ImplicitAcquisitionWrapper blog at 0x8170c6b90>
               user: <ImplicitAcquisitionWrapper - at 0x8139ff550>
               nothing: <NoneType - at 0x800dcbef8>
               container: <ImplicitAcquisitionWrapper blog at 0x8170c6b90>
               request: <instance - at 0x813f7d998>
               wrapped_repeat: <SafeMapping - at 0x814d9baa0>
               traverse_subpath: <list - at 0x819262320>
               default: <object - at 0x8006a2550>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper blog at 0x8170c6b90>
               view: <ContentMenuProvider plone.contentmenu at 0x817d5aa50>
               translate: <function translate at 0x81902de60>
               root: <ImplicitAcquisitionWrapper Zope at 0x81326c2d0>
               options: {...} (0)
               target_language: <NoneType - at 0x800dcbef8>

**Comment by mauritsvanrees** [comment]
The important part of the traceback is this last part:

```
File "/home/plone/danieltordable.net/eggs/collective.blog.view-1.5.2-py2.7.egg/collective/blog/view/blog.py", line 19, in __init_
self.portal_discussion = getToolByName(self.context, 'portal_discussion')
File "", line 13, in check_getToolByName
File "/home/plone/danieltordable.net/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/utils.py", line 120, in getToolByName
raise AttributeError, name
AttributeError: portal_discussion
```

The problem is in `collective.blog.view` that expects the `portal_discussion` tool to be available. I suggest to open an issue in that package: https://github.com/collective/collective.blog.view
