### ISSUE TITLE
Upgrade problem Plone 3.3.5 to 4.3.7 : AttributeError: 'tuple' object has no attribute 'remove', available bugfix not release with Plone 4.3.7

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1134]
Traceback (most recent call last):
  File "/home/ajung/.buildout/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/MigrationTool.py", line 259, in upgrade
    step['step'].doStep(setup)
  File "/home/ajung/.buildout/eggs/Products.GenericSetup-1.7.7-py2.7.egg/Products/GenericSetup/upgrade.py", line 160, in doStep
    self.handler(tool)
  File "/home/ajung/.buildout/eggs/plone.app.upgrade-1.3.18-py2.7.egg/plone/app/upgrade/v40/betas.py", line 107, in beta3_beta4
    value.remove('Large Plone Folder')

AttributeError: 'tuple' object has no attribute 'remove'

This is already fixed here:

https://github.com/plone/plone.app.upgrade/blob/master/plone/app/upgrade/v40/betas.py#L99

But the bugfix is not in the plone.app.upgrade-1.3.18 which comes with Plone 4.3.7

**Comment by zopyx** [comment]
This issue was just fixed two days ago


https://github.com/plone/plone.app.upgrade/commit/980b6e598323f57997351cc6b11600073efc260d

So it can not be part of a release. Closing the issue therefore
