### ISSUE TITLE
plone4.csrffixes issue: TypeError: can't compare datetime.datetime to str

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1142]
I am receiving the following error with plone4.csrffixes 1.0.0. Currently no idea how to debug the issue 
since I don't see the error in the traceback so far...investigating deeper...

Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/home/dgho/onkopedia_buildout/eggs/plone.transformchain-1.0.3-py2.7.egg/plone/transformchain/transformer.py", line 48, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/home/dgho/onkopedia_buildout/eggs/plone4.csrffixes-1.0.0-py2.7.egg/plone4/csrffixes/transform.py", line 93, in transformIterable
    return self.transform(result, encoding)
  File "/home/dgho/onkopedia_buildout/eggs/plone4.csrffixes-1.0.0-py2.7.egg/plone4/csrffixes/transform.py", line 114, in transform
    if key in obj:
TypeError: can't compare datetime.datetime to str

**Comment by zopyx** [comment]
Moved to 

https://github.com/plone/plone4.csrffixes/issues/5
