### ISSUE TITLE
Error if removing all entries from 'plone.types_use_view_action_in_listings'

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1175]
If all entries from "plone.types_use_view_action_in_listings" in the control panel are removed the following error occurs in Plone 5:

```
2015-10-16 11:51:34 ERROR Zope.SiteErrorLog 1444989094.60.631693912663 http://localhost:8008/Plone9/portal_registry/@@configuration_registry
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.registry.browser.records, line 60, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module 590201518ade929608918d3098ac9685.py, line 1192, in render
  Module c0ec7dfa4949e7d97f32a018369e2b28.py, line 282, in render_master
  Module 531b21e8bfc2c61bbbaa26b7ba88abfe.py, line 800, in render_master
  Module z3c.pt.expressions, line 71, in render_content_provider
  Module zope.viewlet.manager, line 112, in update
  Module zope.viewlet.manager, line 118, in _updateViewlets
  Module plone.app.layout.viewlets.social, line 60, in update
  Module Products.CMFPlone.browser.syndication.adapters, line 240, in link
TypeError: argument of type 'NoneType' is not iterable

 - Expression: "provider:plone.htmlhead"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 25: col 36)
 - Source:     ... 
                                         ^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fef3d5ad510>
               views: <ViewMapper - at 0x7fef3cfc7ed0>
               modules: <instance - at 0x7fef4f1c6e60>
               args: <tuple - at 0x7fef5b75e050>
               here: <ImplicitAcquisitionWrapper portal_registry at 0x7fef3d54e910>
               user: <ImplicitAcquisitionWrapper - at 0x7fef4157a280>
               nothing: <NoneType - at 0x7fef5b55a920>
               container: <ImplicitAcquisitionWrapper portal_registry at 0x7fef3d54e910>
               request: <instance - at 0x7fef3d76f710>
               wrapped_repeat: <SafeMapping - at 0x7fef3cfcb310>
               options: {...} (0)
               traverse_subpath: <list - at 0x7fef3dc50f80>
               default: <object - at 0x7fef5b734510>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper portal_registry at 0x7fef3d54e910>
               view: <SimpleViewClass from /home/vagrant/Eggs/plone.app.registry-1.3.5-py2.7.egg/plone/app/registry/browser/records.pt configuration_registry at 0x7fef3d2f7a90>
               translate: <function translate at 0x7fef3cfe2668>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fef3d54e320>
               target_language: de
2015-10-16 11:51:34 ERROR root Exception while rendering an error message
Traceback (most recent call last):
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/OFS/SimpleItem.py", line 242, in raise_standardErrorMessage
    v = s(**kwargs)
  File "/home/vagrant/Eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPythonScript.py", line 127, in __call__
    return Script.__call__(self, *args, **kw)
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/vagrant/Eggs/Products.PythonScripts-2.13.2-py2.7.egg/Products/PythonScripts/PythonScript.py", line 344, in _exec
    result = f(*args, **kw)
  File "Script (Python)", line 35, in standard_error_message
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/vagrant/Eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 237, in _exec
    result = self.pt_render(extra_context=bound_names)
  File "/home/vagrant/Eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 177, in pt_render
    self, source, extra_context
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Products/PageTemplates/PageTemplate.py", line 87, in pt_render
    showtal=showtal)
  File "/home/vagrant/Eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/vagrant/Eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/vagrant/Eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "15d863ee1161225ad67f2fba13f235dc.py", line 1492, in render
  File "531b21e8bfc2c61bbbaa26b7ba88abfe.py", line 800, in render_master
  File "/home/vagrant/Eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/expressions.py", line 71, in render_content_provider
    cp.update()
  File "/home/vagrant/Eggs/zope.viewlet-3.7.2-py2.7.egg/zope/viewlet/manager.py", line 112, in update
    self._updateViewlets()
  File "/home/vagrant/Eggs/zope.viewlet-3.7.2-py2.7.egg/zope/viewlet/manager.py", line 118, in _updateViewlets
    viewlet.update()
  File "/home/vagrant/Eggs/plone.app.layout-2.5.15-py2.7.egg/plone/app/layout/viewlets/social.py", line 60, in update
    dict(name="twitter:url", content=item.link),
  File "/home/vagrant/Eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/browser/syndication/adapters.py", line 240, in link
    if self.context.portal_type in self.feed.view_action_types:
TypeError: argument of type 'NoneType' is not iterable

 - Expression: "provider:plone.htmlhead"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 25: col 36)
 - Source:     ... 
                                         ^
 - Arguments:  repeat: {...} (0)
               template: <ImplicitAcquisitionWrapper default_error_message at 0x7fef3d563780>
               modules: <instance - at 0x7fef4f1c6e60>
               here: <ImplicitAcquisitionWrapper portal_registry at 0x7fef3d54e910>
               user: <ImplicitAcquisitionWrapper - at 0x7fef4157a280>
               nothing: <NoneType - at 0x7fef5b55a920>
               container: <ImplicitAcquisitionWrapper portal_registry at 0x7fef3d54e910>
               default: <object - at 0x7fef5b734510>
               request: <instance - at 0x7fef3d76f710>
               wrapped_repeat: <SafeMapping - at 0x7fef3cffa2b8>
               traverse_subpath: <list - at 0x7fef3d960d40>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper portal_registry at 0x7fef3d54e910>
               translate: <function translate at 0x7fef3cff0578>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fef3d54e320>
               options: {...} (9)
               target_language: de

```

![16-10-2015 11-52-35](https://cloud.githubusercontent.com/assets/339384/10539021/fac7da60-73fc-11e5-80f6-8e4b0b0cd11e.png)

**Comment by ale-rt** [comment]
Fixed by https://github.com/plone/Products.CMFPlone/pull/1176
