### ISSUE TITLE
Resource Registry: AttributeError: 'NoneType' object has no attribute 'split' in browser.resources.cock for compile=False

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1199]
I am receiving the following error with this registry.xml:

https://github.com/xml-director/xmldirector.plonecore/blob/plone5/xmldirector/plonecore/profiles/default-50/registry.xml

```
  File "/home/ajung/.buildout/eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/ajung/.buildout/eggs/plone.app.layout-2.5.15-py2.7.egg/plone/app/layout/viewlets/common.py", line 59, in render
    return self.index()
  File "/home/ajung/.buildout/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/ajung/.buildout/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/ajung/.buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/ajung/.buildout/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/ajung/.buildout/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/ajung/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/ajung/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/ajung/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "c5538f6cf577ae734a8e8184def6b5b7.py", line 88, in render
  File "/home/ajung/.buildout/eggs/five.pt-2.2.3-py2.7.egg/five/pt/expressions.py", line 161, in __call__
    return base()
  File "/home/ajung/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/resources/browser/scripts.py", line 99, in scripts
    result.extend(self.ordered_bundles_result())
  File "/home/ajung/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/resources/browser/resource.py", line 171, in ordered_bundles_result
    self.get_data(bundle, result)
  File "/home/ajung/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/resources/browser/scripts.py", line 39, in get_data
    cookWhenChangingSettings(self.context, bundle)
  File "/home/ajung/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/resources/browser/cook.py", line 93, in cookWhenChangingSettings
    resource_path = js_path.split('++plone++')[-1]
AttributeError: 'NoneType' object has no attribute 'split'

 - Expression: "view/scripts"
 - Filename:   ... py2.7.egg/Products/CMFPlone/resources/browser/scripts.pt
 - Location:   (line 1: col 28)
 - Source:     ... tal:scripts repeat="script view/scripts"
                                              ^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fb42e99dc50>
               views: <ViewMapper - at 0x7fb427f0ff90>
               modules: <instance - at 0x7fb4355cd878>
               args: <tuple - at 0x7fb44625d050>
               here: <ImplicitAcquisitionWrapper front-page at 0x7fb42f987a50>
               user: <ImplicitAcquisitionWrapper - at 0x7fb42f987f50>
               nothing: <NoneType - at 0x784160>
               container: <ImplicitAcquisitionWrapper front-page at 0x7fb42f987a50>
               request: <instance - at 0x7fb42c514cf8>
               wrapped_repeat: <SafeMapping - at 0x7fb427d4d7e0>
               traverse_subpath: <list - at 0x7fb42f044998>
               default: <object - at 0x7fb446233bc0>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0x7fb42f987a50>
               view: <SimpleViewletClass from /home/ajung/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/resources/browser/scripts.pt plone.resourceregistries.scripts at 0x7fb427f0fcd0>
               translate: <function translate at 0x7fb427ddf5f0>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fb42e22c2d0>
               options: {...} (0)
               target_language: <NoneType - at 0x784160>


2015-10-20 14:15:44 ERROR plone.app.viewletmanager rendering of plone.htmlhead.links in plone.resourceregistries.styles fails: 'NoneType' object has no attribute 'split'

 - Expression: "view/styles"
 - Filename:   ... -py2.7.egg/Products/CMFPlone/resources/browser/styles.pt
 - Location:   (line 1: col 26)
 - Source:     <tal:styles repeat="style view/styles"
                                         ^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fb42e92f650>
               views: <ViewMapper - at 0x7fb426ae8890>
               modules: <instance - at 0x7fb4355cd878>
               args: <tuple - at 0x7fb44625d050>
               here: <ImplicitAcquisitionWrapper front-page at 0x7fb42f987a50>
               user: <ImplicitAcquisitionWrapper - at 0x7fb42f987f50>
               nothing: <NoneType - at 0x784160>
               container: <ImplicitAcquisitionWrapper front-page at 0x7fb42f987a50>
               request: <instance - at 0x7fb42c514cf8>
               wrapped_repeat: <SafeMapping - at 0x7fb426ae7e68>
               traverse_subpath: <list - at 0x7fb426ae67e8>
               default: <object - at 0x7fb446233bc0>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0x7fb42f987a50>
               view: <SimpleViewletClass from /home/ajung/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/resources/browser/styles.pt plone.resourceregistries.styles at 0x7fb426ae81d0>
               translate: <function translate at 0x7fb426ae4a28>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fb42e22c2d0>
               options: {...} (0)
               target_language: <NoneType - at 0x784160>
Traceback (most recent call last):
  File "/home/ajung/.buildout/eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/ajung/.buildout/eggs/plone.app.layout-2.5.15-py2.7.egg/plone/app/layout/viewlets/common.py", line 59, in render
    return self.index()
  File "/home/ajung/.buildout/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/ajung/.buildout/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/ajung/.buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/ajung/.buildout/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/ajung/.buildout/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/ajung/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/ajung/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/ajung/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "4f9c321039ea20ef34a3e75300b6413e.py", line 88, in render
  File "/home/ajung/.buildout/eggs/five.pt-2.2.3-py2.7.egg/five/pt/expressions.py", line 161, in __call__
    return base()
  File "/home/ajung/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/resources/browser/styles.py", line 78, in styles
    result = self.ordered_bundles_result()
  File "/home/ajung/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/resources/browser/resource.py", line 171, in ordered_bundles_result
    self.get_data(bundle, result)
  File "/home/ajung/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/resources/browser/styles.py", line 60, in get_data
    cookWhenChangingSettings(self.context, bundle)
  File "/home/ajung/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/resources/browser/cook.py", line 93, in cookWhenChangingSettings
    resource_path = js_path.split('++plone++')[-1]
AttributeError: 'NoneType' object has no attribute 'split'

 - Expression: "view/styles"
 - Filename:   ... -py2.7.egg/Products/CMFPlone/resources/browser/styles.pt
 - Location:   (line 1: col 26)
 - Source:     <tal:styles repeat="style view/styles"
                                         ^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fb42e92f650>
               views: <ViewMapper - at 0x7fb426ae8890>
               modules: <instance - at 0x7fb4355cd878>
               args: <tuple - at 0x7fb44625d050>
               here: <ImplicitAcquisitionWrapper front-page at 0x7fb42f987a50>
               user: <ImplicitAcquisitionWrapper - at 0x7fb42f987f50>
               nothing: <NoneType - at 0x784160>
               container: <ImplicitAcquisitionWrapper front-page at 0x7fb42f987a50>
               request: <instance - at 0x7fb42c514cf8>
               wrapped_repeat: <SafeMapping - at 0x7fb426ae7e68>
               traverse_subpath: <list - at 0x7fb426ae67e8>
               default: <object - at 0x7fb446233bc0>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0x7fb42f987a50>
               view: <SimpleViewletClass from /home/ajung/.buildout/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/resources/browser/styles.pt plone.resourceregistries.styles at 0x7fb426ae81d0>
               translate: <function translate at 0x7fb426ae4a28>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fb42e22c2d0>
               options: {...} (0)
               target_language: <NoneType - at 0x784160>
```

**Comment by zopyx** [comment]
The problem seems to be bound to the compile=False setting. Removing this from registry.xml does not cause a problem.

**Comment by vangheem** [comment]
Looks like your "jscompilation" setting is empty.

**Comment by vangheem** [comment]
It needs that setting to know where to store the compiled files.

**Comment by thet** [comment]
for bundles, which are compiled, the jscompilation and csscompilation are set automatically, not?
could be done for non-compiled bundles as well.

**Comment by zopyx** [comment]
Why did you close the error? The traceback clear demonstrates lack of error
handling or bad error handling.

2015-10-20 15:07 GMT+02:00 Johannes Raggam <notifications@github.com>:

**Comment by thet** [comment]
@vangheem closed your issue by fixing it. He added a log statement to the output: https://github.com/plone/Products.CMFPlone/commit/de98208b64fbda149ebd477d756615a42c979016

Maybe we'd need some better validation in the resource registry also.
I would prefer to add the jscompilation path automatically.
