### ISSUE TITLE
plone.protect 1.0.8 AttributeError 'list' object has no attribute 'tree' Plone 4.3.6

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1215]
With plone.protect 1.0.8 installed on an otherwise plain Plone 4.3.6 (unified installer on OS X El Capitan) if I go to /news and Edit (the collection) then press the Cancel button I get

```
2015-10-30 15:33:00 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/Users/kim/PloneBuilds/Plone-4.3.6/buildout-cache/eggs/plone.transformchain-1.0.4-py2.7.egg/plone/transformchain/transformer.py", line 48, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/Users/kim/PloneBuilds/Plone-4.3.6/buildout-cache/eggs/plone.protect-3.0.15-py2.7.egg/plone/protect/auto.py", line 163, in transformIterable
    return self.transform(result, encoding)
  File "/Users/kim/PloneBuilds/Plone-4.3.6/buildout-cache/eggs/plone.protect-3.0.15-py2.7.egg/plone/protect/auto.py", line 267, in transform
    root = result.tree.getroot()
AttributeError: 'list' object has no attribute 'tree'
```

**Comment by fgrcon** [comment]
plone 5 current  coredev:
 same behavior e.g. with relateditems , inserting images with tinymce ....

**Comment by simahawk** [comment]
plone 4.2.5 + plone.protect 3.0.15 + plone4.csrffixes 1.0.8 => same error

**Comment by simahawk** [comment]
looks like "result" passed to this transform is equal to a list w/ an empty string inside [''].
The URL in the case of an image upload via tiny is something like "http://localhost:8080/mysite/resolveuid/77bfbf15c9764b58bc136eb296f18511".

Nonetheless the upload itself is working and the editing of the content is not affected.
The only "visual issue" I'm experiencing in the UX is that you don't get the image preview.

**Comment by davilima6** [comment]
:+1: I got the same error when creating a new site in coredev.

**Comment by mauritsvanrees** [comment]
This has been fixed with this pull request:
https://github.com/plone/plone.protect/pull/30
Pending a release.

**Comment by jensens** [comment]
i close this, PR was merged.
