### ISSUE TITLE
Products.PasswordResetTool 2.1.2 breaks compatibility

### ISSUE THREAD

**Issue by rodfersou** [plone/Products.CMFPlone#1228]
Using Plone 4.3.1

```
cfa@cfa:~/cfa.portal.buildout$ ./bin/instance fg
2015-11-05 17:41:56 INFO ZServer HTTP server started at Thu Nov  5 17:41:56 2015
        Hostname: localhost
        Port: 8080
2015-11-05 17:41:58 ERROR Application Could not import Products.PasswordResetTool
Traceback (most recent call last):
  File "/home/cfa/cfa.portal.buildout/eggs/Zope2-2.13.20-py2.7.egg/OFS/Application.py", line 606, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/home/cfa/cfa.portal.buildout/eggs/Products.PasswordResetTool-2.1.2-py2.7.egg/Products/PasswordResetTool/__init__.py", line 4, in <module>
    import PasswordResetTool
  File "/home/cfa/cfa.portal.buildout/eggs/Products.PasswordResetTool-2.1.2-py2.7.egg/Products/PasswordResetTool/PasswordResetTool.py", line 24, in <module>
    from Products.CMFPlone.interfaces import ISecuritySchema
ImportError: cannot import name ISecuritySchema
Traceback (most recent call last):
  File "/home/cfa/cfa.portal.buildout/eggs/Zope2-2.13.20-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/cfa/cfa.portal.buildout/eggs/Zope2-2.13.20-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/cfa/cfa.portal.buildout/eggs/Zope2-2.13.20-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
    self.startZope()
  File "/home/cfa/cfa.portal.buildout/eggs/Zope2-2.13.20-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
    Zope2.startup()
  File "/home/cfa/cfa.portal.buildout/eggs/Zope2-2.13.20-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/cfa/cfa.portal.buildout/eggs/Zope2-2.13.20-py2.7.egg/Zope2/App/startup.py", line 67, in startup
    OFS.Application.import_products()
  File "/home/cfa/cfa.portal.buildout/eggs/Zope2-2.13.20-py2.7.egg/OFS/Application.py", line 583, in import_products
    import_product(product_dir, product_name, raise_exc=debug_mode)
  File "/home/cfa/cfa.portal.buildout/eggs/Zope2-2.13.20-py2.7.egg/OFS/Application.py", line 606, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/home/cfa/cfa.portal.buildout/eggs/Products.PasswordResetTool-2.1.2-py2.7.egg/Products/PasswordResetTool/__init__.py", line 4, in <module>
    import PasswordResetTool
  File "/home/cfa/cfa.portal.buildout/eggs/Products.PasswordResetTool-2.1.2-py2.7.egg/Products/PasswordResetTool/PasswordResetTool.py", line 24, in <module>
    from Products.CMFPlone.interfaces import ISecuritySchema
ImportError: cannot import name ISecuritySchema
```

**Comment by hvelarde** [comment]
@esteele seems that some changes intended for Plone 5 ended up in the wrong branch: https://github.com/plone/Products.PasswordResetTool/commits/2.1.2

are there any valid bug fixes there or not?

**Comment by mauritsvanrees** [comment]
On Plone 4.3 you should use PasswordresetTool 2.0.x. Plone 4.3.7 pins 2.0.18.

I think 2.1.x was only used in Plone 5 alpha or beta releases. Plone 5 uses 2.2.1. coredev 5 uses 2.2.x (well, master). So the version increase from 2.1.x to 2.2.x was not really necessary...
