### ISSUE TITLE
AttributeError: thumb_visibility after upgrading to Plone 5.0.1

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1291]
After upgrading to Plone 5.0.1 from Plone 5.0 I got the following error:

```
2015-12-18 13:15:22 ERROR root Exception while rendering an error message
Traceback (most recent call last):
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/OFS/SimpleItem.py", line 242, in raise_standardErrorMessage
    v = s(**kwargs)
  File "/home/vagrant/Eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPythonScript.py", line 127, in __call__
    return Script.__call__(self, *args, **kw)
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/vagrant/Eggs/Products.PythonScripts-2.13.2-py2.7.egg/Products/PythonScripts/PythonScript.py", line 344, in _exec
    result = f(*args, **kw)
  File "Script (Python)", line 35, in standard_error_message
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/vagrant/Eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 237, in _exec
    result = self.pt_render(extra_context=bound_names)
  File "/home/vagrant/Eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 177, in pt_render
    self, source, extra_context
  File "/home/vagrant/Eggs/Zope2-2.13.23-py2.7.egg/Products/PageTemplates/PageTemplate.py", line 87, in pt_render
    showtal=showtal)
  File "/home/vagrant/Eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/vagrant/Eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/vagrant/Eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/vagrant/Eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "0fedb7d6ab68446c2aa6a59e9fd8839f.py", line 1492, in render
  File "4e19bb3092c054d49cbb6c01a7228415.py", line 971, in render_master
  File "/home/vagrant/Eggs/plone.app.layout-2.5.17-py2.7.egg/plone/app/layout/globals/layout.py", line 201, in bodyClass
    if self.thumb_visible():
  File "/home/vagrant/Eggs/plone.memoize-1.1.1-py2.7.egg/plone/memoize/view.py", line 47, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/home/vagrant/Eggs/plone.app.layout-2.5.17-py2.7.egg/plone/app/layout/globals/layout.py", line 110, in thumb_visible
    thumb_visibility = settings.thumb_visibility
  File "/home/vagrant/Eggs/plone.registry-1.0.2-py2.7.egg/plone/registry/recordsproxy.py", line 33, in __getattr__
    raise AttributeError(name)
AttributeError: thumb_visibility

 - Expression: "python:plone_layout.bodyClass(template, view)"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 45: col 28)
 - Source:     ... e="isRTL portal_state/is_rtl;
                              ^
 - Arguments:  repeat: {...} (0)
               template: <ImplicitAcquisitionWrapper default_error_message at 0x7f015da7c4b0>
               modules: <instance - at 0x7f016ad92050>
               here: <ImplicitAcquisitionWrapper Plone at 0x7f015e106500>
               user: <SpecialUser - at 0x7f0165573750>
               nothing: <NoneType - at 0x7f0177167920>
               container: <ImplicitAcquisitionWrapper Plone at 0x7f015e106500>
               default: <object - at 0x7f017733f4f0>
               request: <instance - at 0x7f0152e0fd88>
               wrapped_repeat: <SafeMapping - at 0x7f015e6020a8>
               traverse_subpath: <list - at 0x7f0152d20d88>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper Plone at 0x7f015e106500>
               translate: <function translate at 0x7f0152b25ed8>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f015e1e1aa0>
               options: {...} (9)
               target_language: de
```

**Comment by tomgross** [comment]
The error occurs directly after site creation.

**Additional there is no upgrade site notification in ZMI or the site.**

**Comment by tomgross** [comment]
Using older **plone.app.layout 2.5.16** instead of 2.5.17 seems to work.

**Comment by fgrcon** [comment]
http://dist.plone.org/release/5.0.1-pending/versions.cfg points to plone.app.upgrade 1.3.18 but should point to 1.3.19. 
I suppose that is the reason.

**Comment by mauritsvanrees** [comment]
It also points to Products.CMFPlone 5.0 instead of 5.0.1. I think @esteele is busy with that.

**Comment by tomgross** [comment]
Works with Plone 5.0.2 now
