### ISSUE TITLE
Issues with migration from 5.0 to 5.0.2

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1327]
pls help the upgrade report attached below. There are 2 sites. In one the migration has successfully taken place. In the 2nd i face following error. Further, in the first I am facing issues in the collection content type. when i use tags to create a collection it shows in search, but vanishes on save. i think the issue maybe related

Dry run selected.
Starting the migration from version: 5011
Ran upgrade step: Unmark installed profiles that are no longer available.
Ran upgrade step: Mark products as installed for installed uninstallable profiles
Ran upgrade step: Cleanup uninstalled products
Ran upgrade step: Cleanup the skins tool.
Ran upgrade step: Remove fake kupu tool and related settings and resources.
Role / permission map imported.
Actions tool imported.
Upgrade aborted. Error:
Traceback (most recent call last):
  File "/opt/plone/buildout-cache/eggs/Products.CMFPlone-5.0.2-py2.7.egg/Products/CMFPlone/MigrationTool.py", line 268, in upgrade
    step['step'].doStep(setup)
  File "/opt/plone/buildout-cache/eggs/Products.GenericSetup-1.8.1-py2.7.egg/Products/GenericSetup/upgrade.py", line 166, in doStep
    self.handler(tool)
  File "/opt/plone/buildout-cache/eggs/plone.app.upgrade-1.3.20-py2.7.egg/plone/app/upgrade/v50/final.py", line 83, in to501
    refresh_getIcon_catalog_metadata(context)
  File "/opt/plone/buildout-cache/eggs/plone.app.upgrade-1.3.20-py2.7.egg/plone/app/upgrade/v50/final.py", line 71, in refresh_getIcon_catalog_metadata
    obj = brain._unrestrictedGetObject()
  File "/opt/plone/buildout-cache/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/ZCatalog/CatalogBrains.py", line 80, in _unrestrictedGetObject
    return parent.unrestrictedTraverse(self.getPath())
  File "/opt/plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/OFS/Traversable.py", line 300, in unrestrictedTraverse
    raise e
KeyError: '025d3bf9-dc6c-40b9-aaeb-daf287e63432'
End of upgrade path, main migration has finished.
The upgrade path did NOT reach current version.
Migration has failed
Dry run selected, transaction aborted

**Comment by davisagli** [comment]
Looks like it's failing to update the catalog metadata for an object because the indexed object no longer exists. Try rebuilding your catalog (Advanced tab on portal_catalog in the ZMI) before running the upgrade.

**Comment by sudhan77** [comment]
Thanks David for the super quick response. Issue resolved as per your solution.
