### ISSUE TITLE
Plone 5 upgrade fails ..  ERROR Zope.SiteErrorLog 1455701440.290.667438289137 

### ISSUE THREAD

**Issue by abadger1406** [plone/Products.CMFPlone#1390]
I run Plone 5 upgrade on a very large (113G Data.fs site), and after correcting duplicate users #1387 and install lynx it appears to run okay, until right a tend I get the following. The web interface still just gives the Upgrade button, like the upgrade has not succeeded.

```
...
2016-02-17 09:30:39 INFO Products.GenericSetup.tool Importing profile profile-plone.app.upgrade.v50:to500 with dependency strategy upgrade.
2016-02-17 09:30:39 INFO Products.GenericSetup.tool Applying main profile profile-plone.app.upgrade.v50:to500
2016-02-17 09:30:39 INFO GenericSetup.rolemap Role / permission map imported.
2016-02-17 09:30:39 ERROR GenericSetup Step loginlockout has an invalid import handler
2016-02-17 09:30:39 INFO GenericSetup.archetypetool Archetype tool imported.
2016-02-17 09:30:39 ERROR GenericSetup Step languagetool has an invalid import handler
2016-02-17 09:30:39 ERROR GenericSetup Step passwordstrength has an invalid import handler
2016-02-17 09:30:39 INFO plone.app.upgrade Ran upgrade step: Run to500 upgrade profile
2016-02-17 09:30:39 INFO plone.app.upgrade Starting upgrade of core addons.
2016-02-17 09:30:39 INFO Products.GenericSetup.tool Profile Products.CMFEditions:CMFEditions upgraded to version ('4',).
2016-02-17 09:30:39 WARNING Products.GenericSetup.tool Version of profile Products.CMFPlacefulWorkflow:CMFPlacefulWorkflow is unknown, refusing to upgrade.
2016-02-17 09:30:39 WARNING Products.GenericSetup.tool Version of profile plone.app.contenttypes:default is unknown, refusing to upgrade.
2016-02-17 09:30:39 WARNING Products.GenericSetup.tool Version of profile plone.app.dexterity:default is unknown, refusing to upgrade.
2016-02-17 09:30:39 INFO GenericSetup.rolemap Role / permission map imported.
2016-02-17 09:30:39 INFO Products.GenericSetup.tool Profile plone.app.discussion:default upgraded to version ('102',).
2016-02-17 09:30:39 INFO Products.GenericSetup.tool No upgrades available for profile plone.app.event:default. Profile stays at version (u'15',).
2016-02-17 09:30:39 WARNING Products.GenericSetup.tool Version of profile plone.app.iterate:plone.app.iterate is unknown, refusing to upgrade.
2016-02-17 09:30:39 WARNING Products.GenericSetup.tool Version of profile plone.app.multilingual:default is unknown, refusing to upgrade.
2016-02-17 09:30:39 INFO Products.GenericSetup.tool No upgrades available for profile plone.app.querystring:default. Profile stays at version ('11',).
2016-02-17 09:30:39 INFO Products.GenericSetup.tool No upgrades available for profile plone.app.theming:default. Profile stays at version (u'1001',).
2016-02-17 09:30:39 WARNING Products.GenericSetup.tool Version of profile plone.app.users:default is unknown, refusing to upgrade.
2016-02-17 09:30:39 INFO plone.app.upgrade Done upgrading core addons.
2016-02-17 09:30:39 INFO plone.app.upgrade End of upgrade path, migration has finished
2016-02-17 09:30:39 INFO plone.app.upgrade Your Plone instance is now up-to-date.
2016-02-17 09:30:40 ERROR Zope.SiteErrorLog 1455701440.290.667438289137 https://big5.netfm.org/MyCollaborator/@@plone-upgrade
Traceback (innermost last):
  Module ZPublisher.Publish, line 146, in publish
  Module Zope2.App.startup, line 301, in commit
  Module transaction._manager, line 89, in commit
  Module transaction._transaction, line 329, in commit
  Module transaction._transaction, line 443, in _commitResources
  Module ZODB.Connection, line 559, in commit
  Module ZODB.Connection, line 1123, in savepoint
  Module ZODB.Connection, line 623, in _commit
  Module ZODB.Connection, line 658, in _store_objects
  Module ZODB.serialize, line 422, in serialize
  Module ZODB.serialize, line 431, in _dump
PicklingError: Can't pickle <class 'plonetheme.classic.browser.interfaces.IThemeSpecific'>: import of module plonetheme.classic.browser.interfaces failed
2016-02-17 09:30:40 ERROR root Exception while rendering an error message
Traceback (most recent call last):
  File "/home/Plone5/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/OFS/SimpleItem.py", line 242, in raise_standardErrorMessage
    v = s(**kwargs)
  File "/home/Plone5/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPythonScript.py", line 127, in __call__
    return Script.__call__(self, *args, **kw)
  File "/home/Plone5/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/Plone5/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/Plone5/buildout-cache/eggs/Products.PythonScripts-2.13.2-py2.7.egg/Products/PythonScripts/PythonScript.py", line 344, in _exec
    result = f(*args, **kw)
  File "Script (Python)", line 35, in standard_error_message
  File "/home/Plone5/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/Plone5/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/Plone5/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 237, in _exec
    result = self.pt_render(extra_context=bound_names)
  File "/home/Plone5/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 177, in pt_render
    self, source, extra_context
  File "/home/Plone5/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Products/PageTemplates/PageTemplate.py", line 87, in pt_render
    showtal=showtal)
  File "/home/Plone5/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/Plone5/buildout-cache/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/Plone5/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "933fe121432f9b76cf05d3a4a7e77ecb.py", line 1492, in render
  File "d2f4c9ea5b02745ebfc5f15246c69cd3.py", line 800, in render_master
  File "/home/Plone5/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/expressions.py", line 71, in render_content_provider
    cp.update()
  File "/home/Plone5/buildout-cache/eggs/zope.viewlet-3.7.2-py2.7.egg/zope/viewlet/manager.py", line 112, in update
    self._updateViewlets()
  File "/home/Plone5/buildout-cache/eggs/zope.viewlet-3.7.2-py2.7.egg/zope/viewlet/manager.py", line 118, in _updateViewlets
    viewlet.update()
  File "/home/Plone5/buildout-cache/eggs/plone.app.layout-2.5.15-py2.7.egg/plone/app/layout/viewlets/common.py", line 131, in update
    self.metatags = plone_utils.listMetaTags(context).items()
  File "/home/Plone5/buildout-cache/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/PloneTool.py", line 967, in listMetaTags
    ISecuritySchema, prefix='plone')
  File "/home/Plone5/buildout-cache/eggs/plone.registry-1.0.2-py2.7.egg/plone/registry/registry.py", line 74, in forInterface
    "for which there is no record." % (interface.__identifier__, name))
KeyError: 'Interface `Products.CMFPlone.interfaces.controlpanel.ISecuritySchema` defines a field `enable_user_folders`, for which there is no record.'

 - Expression: "provider:plone.htmlhead"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 25: col 36)
 - Source:     ... 
                                         ^
 - Arguments:  repeat: {...} (0)
               template: <ImplicitAcquisitionWrapper default_error_message at 0x7f60f15fd3c0>
               modules: <instance - at 0x7f610305a3f8>
               here: <ImplicitAcquisitionWrapper MyCollaborator at 0x7f60f99e0640>
               user: <ImplicitAcquisitionWrapper - at 0x7f60f94ef320>
               nothing: <NoneType - at 0x8f8340>
               container: <ImplicitAcquisitionWrapper MyCollaborator at 0x7f60f99e0640>
               default: <object - at 0x7f610b05b520>
               request: <instance - at 0x7f60f9053368>
               wrapped_repeat: <SafeMapping - at 0x7f60fa65bcb0>
               traverse_subpath: <list - at 0x7f60f2488290>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper MyCollaborator at 0x7f60f99e0640>
               translate: <function translate at 0x7f60deee5cf8>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f60f99e05a0>
               options: {...} (9)
               target_language: <NoneType - at 0x8f8340>
```

**Comment by pbauer** [comment]
@abadger1406 use Plone 5.0.2 which should have fixed this issue. See http://docs.plone.org/manage/upgrading/version_specific_migration/p4x_to_p5x_upgrade.html#general-information that states "Always upgrade from the latest version of 4.x to the latest version of 5.x (at the time of writing 4.3.7 to 5.0.2). This will resolve many migration-specific issues."

**Comment by abadger1406** [comment]
```
2016-02-17T19:19:55 INFO plone.app.upgrade Ran upgrade step: Unmark installed profiles that are no longer available.
------
2016-02-17T19:19:55 INFO plone.app.upgrade Ran upgrade step: Mark products as installed for installed uninstallable profiles
------
2016-02-17T19:19:55 INFO plone.app.upgrade Ran upgrade step: Cleanup uninstalled products
------
2016-02-17T19:19:55 ERROR plone.app.upgrade Upgrade aborted. Error:
Traceback (most recent call last):
  File "/home/Plone5/buildout-cache/eggs/Products.CMFPlone-5.0.2-py2.7.egg/Products/CMFPlone/MigrationTool.py", line 268, in upgrade
    step['step'].doStep(setup)
  File "/home/Plone5/buildout-cache/eggs/Products.GenericSetup-1.8.1-py2.7.egg/Products/GenericSetup/upgrade.py", line 166, in doStep
    self.handler(tool)
  File "/home/Plone5/buildout-cache/eggs/plone.app.upgrade-1.3.20-py2.7.egg/plone/app/upgrade/v40/alphas.py", line 373, in cleanUpSkinsTool
    transaction.savepoint(optimistic=True)
  File "/home/Plone5/buildout-cache/eggs/transaction-1.1.1-py2.7.egg/transaction/_manager.py", line 101, in savepoint
    return self.get().savepoint(optimistic)
  File "/home/Plone5/buildout-cache/eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 260, in savepoint
    self._saveAndRaiseCommitishError() # reraises!
  File "/home/Plone5/buildout-cache/eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 257, in savepoint
    savepoint = Savepoint(self, optimistic, *self._resources)
  File "/home/Plone5/buildout-cache/eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 690, in __init__
    savepoint = savepoint()
  File "/home/Plone5/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 1123, in savepoint
    self._commit(None)
  File "/home/Plone5/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 623, in _commit
    self._store_objects(ObjectWriter(obj), transaction)
  File "/home/Plone5/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 658, in _store_objects
    p = writer.serialize(obj)  # This calls __getstate__ of obj
  File "/home/Plone5/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/serialize.py", line 422, in serialize
    return self._dump(meta, obj.__getstate__())
  File "/home/Plone5/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/serialize.py", line 431, in _dump
    self._p.dump(state)
PicklingError: Can't pickle <class 'plonetheme.classic.browser.interfaces.IThemeSpecific'>: import of module plonetheme.classic.browser.interfaces failed
------
2016-02-17T19:19:55 INFO plone.app.upgrade End of upgrade path, main migration has finished.
------
2016-02-17T19:19:55 ERROR plone.app.upgrade The upgrade path did NOT reach current version.
------
2016-02-17T19:19:55 ERROR plone.app.upgrade Migration has failed
```

**Comment by abadger1406** [comment]
My 4.2.1.1 Plone installation that I'm trying to upgrade has extras of 


```
dave@big:/home/Plone/zeocluster$ more buildout.cfg 
############################################
#
# Buildout Configuration File for ZEO Plone
# -----------------------------------------
#
# After making changes in this configuration file,
# you should run bin/buildout to update the components.
#
# ALWAYS back up all Plone/Zope data and components
# before changing configuration.
#
# Running "bin/buildout" will update your installation,
# installing missing components as necessary.
#
# Use "bin/buildout -n" to update many components here to the newest
# available releases.
# This will update the add-on products you've added in the eggs= lines.
# This will not, however, upgrade Plone itself (or anything else you've
# pinned with a version specification). To upgrade Plone itself, see the
# comments in "Plone Component Versions".
#
# Tutorial instructions for using zc.buildout for
# configuration management are available at:
# http://plone.org/documentation/tutorial/buildout
# Full details at http://pypi.python.org/pypi/zc.buildout
#
############################################


[buildout]

############################################
# Plone Component Versions
# ------------------------
# This version of the Unified Installer has the components of Plone 4
# preloaded so that it can install without an Internet connection.
# If you want to update, uncomment the "http://..." line below,
# edit it to point to the current version URL, comment out the
# "versions.cfg" line and run "bin/buildout" while attached to the
# Internet. Generally, you only want to do that as part of a planned migration.
# Note that if you are updating components, you should also check the versions
# section at the end of this file, since recipes or components other than
# those of Zope and Plone may need updating at the same time.
#
extends =
    base.cfg
    versions.cfg
    http://dist.plone.org/release/4.3-latest/versions.cfg

# If you change your Plone version, you'll also need to update
# the repository below.
find-links +=
    http://dist.plone.org/release/4.3-latest


############################################
# Ports
# -----
# Specify the ports on which your Zope installation
# will listen.
# ZEO Server
zeo-address = 127.0.0.1:8800
# Zope client 1
http-address = 8082
# Additional clients:
client2-address = 8081



# If you try to start Zope as root, it will change user id to run as
# the effective user specified here. This user id must own the var directory
# of your buildout.
effective-user = plone


############################################
# Eggs
# ----
# Add an indented line to the eggs section for any Python
# eggs or packages you wish to include.
#
eggs =
    Plone
    Pillow
    Products.LoginLockout
    Products.PasswordStrength
    collective.quickupload
    collective.localrolesdatatables
    plone4.csrffixes==1.0.8

#plone.app.workflowmanager


############################################
# Optional Functionality
# ----------------------
# Uncomment the indented lines to include these products.
# Documentation on all of them, along with many more products,
# is available at
# http://plone.org/products/
#
# Example products:
# * LinguaPlone provides tools for building multi-lingual sites
# * PloneFormGen provides through-the-web form building
#
#    Products.LinguaPlone==4.0.1
#    Products.PloneFormGen==1.6.0
#
# Note that versions may be specified here or in the [versions]
# section below. You should always specify versions that you know
# are compatible with the Plone release and at an acceptable
# development level.
#
# Commonly used development tools:
# Several excellent development tools are included in the develop.cfg
# buildout extension. Read it to learn how to activate these tools.


############################################
# ZCML Slugs
# ----------
# Some eggs need ZCML slugs to tell Zope to
# use them. Eggs with names beginning with "Products."
# usually don't need this.
zcml =
#    plone.reload


############################################
# Development Eggs
# ----------------
# You can use paster to create "development eggs" to
# develop new products/themes. Put these in the src/
# directory.
# You will also need to add the egg names in the
# eggs section above, and may also need to add them
# to the zcml section.
#
# Provide the *paths* to the eggs you are developing here:
develop =
#    src/my.package


############################################
# Debug Mode
# ----------
# Change debug-mode to "on" to run in development mode.
#
debug-mode = off
# Add-on developers should turn deprecation warnings on
deprecation-warnings = off
# change verbose-security to "on" for useful security errors while developing
verbose-security = off


############################################
# Backup Directory
# ----------------
# Sets the target directory for the bin/backup and bin/snapshotbackup
# commands. Default is inside this project's var directory, but ideally
# this should be on a separate volume or backup server.
#
backups-dir=${buildout:directory}/var


############################################
# Environment Variables
# ---------------------
# Some of the behavior of your Zope/Plone instances are controlled with OS
# environment variables. You may set those here in a key / value format.
# Some common settings:
#    * TZ allows you to set a time zone for systems where it's not
#      automatically available.
#    * zope_i18n_compile_mo_files allows for automatic compilation of
#      missing translation files (may slow startup).
#    * zope_i18n_allowed_languages allows you to limit the available
#      translations.
#    * PYTHON_EGG_CACHE determines where zipped python packages are unpacked
#      for use.
#    * PYTHONHASHSEED determines initial seed for hashes. "random" causes a
#      pseudo-random value is used to seed the hashes of str, bytes and datetime
#      objects.
environment-vars =
    zope_i18n_compile_mo_files true
    PYTHON_EGG_CACHE ${buildout:directory}/var/.python-eggs
    PYTHONHASHSEED random
    #    TZ US/Eastern
    #    zope_i18n_allowed_languages en es de fr


############################################
# Initial User
# ------------
# This is the user id and password that will be used to create the initial
# user id that will allow you to log in and create a Plone site. This only
# sets the initial password; it will not allow you to change an already
# existing password. If you change the admin password via the web interface,
# the one below will no longer be valid.
# If you find yourself locked out of your Zope/Python installation, you may
# add an emergency user via "bin/plonectl client1 client2 adduser".
user=admin:BrwPbrrG


############################################
# Parts Specification
# -------------------
# Specifies the components that should be included in the buildout.
# All the basics are in the base.cfg extension; you may add your
# own if you need them at the end of this file.
parts =
    zeoserver
    client1 client2
    zopepy
    zopeskel
    unifiedinstaller
    backup
    chown-zeo


############################################
# Versions Specification
# ----------------------
# Version information supplied here will "pin" Python packages to a particular
# version number, even when you use the "newest" flag running buildout.
# Specifying versions for all packages is a good idea and can prevent
# accidental changes when you add new packages to your buildout.
# Note that versions specified here will override those specified earlier
# in the configuration, including those from the Plone and Zope version
# config files.
#
[versions]
ZopeSkel = 2.21.2
Cheetah = 2.2.1
Pillow = 1.7.7
Products.DocFinderTab = 1.0.5
collective.recipe.backup = 2.6
plone.recipe.command = 1.1
plone.recipe.unifiedinstaller = 4.1
plone.protect = 3.0.17
plone.keyring = 3.0.1
plone.locking = 2.0.9
```

**Comment by gforcada** [comment]
@abadger1406 the pickling error means that Plone is trying to create/restore a reference to ``plonetheme.classic.browser.interfaces.IThemeSpecific`` and it fails to find it.

You should add it on your eggs section or try to find why it needs it.

**Comment by abadger1406** [comment]
Do you mean on the new buildout.cfg file for Plone5 ? I'll try this

**Comment by abadger1406** [comment]
The upgrade now succeeds ! Thank you for assistance.

Will logg a separate issue on 
```
2016-02-19T00:15:49 ERROR plone.app.viewletmanager rendering of plone.portaltop in plone.header fails: 'TTWViewletRenderer' object has no attribute '__name__'
```

**Comment by tkimnguyen** [comment]
@pbauer I've just encountered the same error reported here originally, but I am going from 4.3.8 (to 5.0.4).

```
2016-06-19 11:28:39 ERROR root Exception while rendering an error message
Traceback (most recent call last):
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/OFS/SimpleItem.py", line 242, in raise_standardErrorMessage
    v = s(**kwargs)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPythonScript.py", line 127, in __call__
    return Script.__call__(self, *args, **kw)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Products.PythonScripts-2.13.2-py2.7.egg/Products/PythonScripts/PythonScript.py", line 344, in _exec
    result = f(*args, **kw)
  File "Script (Python)", line 39, in standard_error_message
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 237, in _exec
    result = self.pt_render(extra_context=bound_names)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 177, in pt_render
    self, source, extra_context
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Products/PageTemplates/PageTemplate.py", line 87, in pt_render
    showtal=showtal)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Chameleon-2.24-py2.7.egg/chameleon/zpt/template.py", line 261, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Chameleon-2.24-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Chameleon-2.24-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "16d2126adc6e55ad1a41043020e2e86a.py", line 1492, in render
  File "6a8208952b4ef01d599e24887795cc57.py", line 800, in render_master
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/expressions.py", line 71, in render_content_provider
    cp.update()
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/zope.viewlet-3.7.2-py2.7.egg/zope/viewlet/manager.py", line 112, in update
    self._updateViewlets()
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/zope.viewlet-3.7.2-py2.7.egg/zope/viewlet/manager.py", line 118, in _updateViewlets
    viewlet.update()
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/plone.app.layout-2.5.19-py2.7.egg/plone/app/layout/viewlets/common.py", line 132, in update
    self.metatags = plone_utils.listMetaTags(context).items()
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/Products.CMFPlone-5.0.4-py2.7.egg/Products/CMFPlone/PloneTool.py", line 968, in listMetaTags
    ISecuritySchema, prefix='plone')
  File "/home/kim/Plone-5.0.4/buildout-cache/eggs/plone.registry-1.0.3-py2.7.egg/plone/registry/registry.py", line 77, in forInterface
    name
KeyError: 'Interface `Products.CMFPlone.interfaces.controlpanel.ISecuritySchema` defines a field `enable_user_folders`, for which there is no record.'

 - Expression: "provider:plone.htmlhead"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 25: col 36)
 - Source:     ... 
                                         ^
 - Arguments:  repeat: {...} (0)
               template: <ImplicitAcquisitionWrapper default_error_message at 0x7f716b73c730>
               modules: <instance - at 0x7f7171274680>
               here: <ImplicitAcquisitionWrapper error_log at 0x7f716b6fdbe0>
               user: <ImplicitAcquisitionWrapper - at 0x7f716b6fddc0>
               nothing: <NoneType - at 0x91a870>
               container: <ImplicitAcquisitionWrapper OshkoshZoo at 0x7f71688dde60>
               default: <object - at 0x7f71788c2520>
               request: <instance - at 0x7f7169ef7cb0>
               wrapped_repeat: <SafeMapping - at 0x7f716b75bec0>
               traverse_subpath: <list - at 0x7f7168befd88>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper error_log at 0x7f716b6fdbe0>
               translate: <function translate at 0x7f71697f71b8>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f716c218b40>
               options: {...} (9)
               target_language: <NoneType - at 0x91a870>
```

**Comment by pbauer** [comment]
It seems like `plone.app.upgrade.v50.betas.upgrade_security_controlpanel_settings` was not run correctly. Probably it could not find settings in line 178 (maybe due to some other error in loading  `plone/app/upgrade/v50/profiles/to_beta1/registry.xml` before that since it creates the ISecuritySchema-records). You can put a pdb in the upgrade-step `upgrade_security_controlpanel_settings` to see if that is true and check the log for warnings that happend before. 

If the upgrade was already run you can try to rerun the step in http://demo.plone.de/portal_setup/manage_upgrades. Select Products.CMFPlone:plone and click Show old upgrades. In the list search for "Upgrade security control panel settings". Selecting it an clicking upgrade will run said step.

**Comment by tkimnguyen** [comment]
Thx @pbauer ... I no longer remember which project I was working on and I don't have that buildout anymore :) but still good to know for the record.

**Comment by pigeonflight** [comment]
The "Upgrade security control panel settings" didn't do it for me. So I'm still looking for a nice way to migrate one of my sites from Plone 4.3.6 to Plone 5.

I went into {my site}/portal_setup/manage > `Upgrades` tab > 
found the profile under `Products.CMFPlone:plone`

![screenshot 2017-05-30 at 6 00 10 am](https://cloud.githubusercontent.com/assets/31827/26580355/4dcae31a-44fd-11e7-904f-37206b1f382b.png)

So I selected it 
![screenshot 2017-05-30 at 6 02 01 am](https://cloud.githubusercontent.com/assets/31827/26580398/8bf2af6a-44fd-11e7-8926-813c7aab768a.png)

And ran / re-ran the upgrade.

But when I visit my site, I still see the error:
```
KeyError('Interface `Products.CMFPlone.interfaces.controlpanel.ISecuritySchema` defines a field `enable_user_folders`, for which there is no record.',) (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: Interface `Products.CMFPlone.interfaces.controlpanel.ISecuritySchema` defines a field `enable_user_folders`, for which there is no record.)
```

**Comment by pbauer** [comment]
Add your own step to reinitializes these values. You should also be able to do that in python only but I'm to lazy to find out so there is a import-step instead:

`profiles/to_1007/registry.xml`:

```xml
<?xml version="1.0"?>
<registry>
  <!-- add missing enable_user_folders field -->
  <records interface="Products.CMFPlone.interfaces.syndication.ISiteSyndicationSettings" />
</registry>
```

register the profile in configure.zcml:

```xml
  <genericsetup:registerProfile
      name="to_1007"
      title="Fix ISiteSyndicationSettings"
      description=""
      directory="profiles/to_1007"
      for="Products.CMFPlone.interfaces.IPloneSiteRoot"
      provides="Products.GenericSetup.interfaces.EXTENSION"
      />
```

run it in a upgarde-step:

```python
    setup.runAllImportStepsFromProfile(
        'profile-my.package:to_1007', purge_old=False)
```

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
