### ISSUE TITLE
 Plone 5 upgrade gives error 'TTWViewletRenderer' object has no attribute '__name__'

### ISSUE THREAD

**Issue by abadger1406** [plone/Products.CMFPlone#1402]
After fresh upgrade to Plone 5.0.2 see following error at top of page

error while rendering plone.header 

The log file looks like

```
root@big5 /home/Plone5/zeocluster # tail -f ./var/client1/event.log
------
2016-02-19T00:15:32 INFO ZEO.ClientStorage zeostorage Connected to storage: ('localhost', 8187)
------
2016-02-19T00:15:32 INFO ZEO.ClientStorage zeostorage No verification necessary -- empty cache
------
2016-02-19T00:15:34 INFO Plone OpenID system packages not installed, OpenID support not available
------
2016-02-19T00:15:36 WARNING OFS.Uninstalled Could not import class 'LoginLockout' from module 'Products.LoginLockout.plugin'
------
2016-02-19T00:15:36 INFO Zope Ready to handle requests


------
2016-02-19T00:15:46 WARNING OFS.Uninstalled Could not import class 'LoginLockoutTool' from module 'Products.LoginLockout.loginlockout_tool'
------
2016-02-19T00:15:46 WARNING OFS.Uninstalled Could not import class 'PasswordStrength' from module 'Products.PasswordStrength.plugin'
------
2016-02-19T00:15:47 WARNING OFS.Uninstalled Could not import class 'WickedSettings' from module 'plone.app.controlpanel.markup'
------
2016-02-19T00:15:47 INFO plone.app.theming.policy local cache invalidated on thread 140445529970432
------
2016-02-19T00:15:47 INFO plone.app.theming.policy initializing local cache on thread 140445529970432 for https://big5.netfm.org/MyCollaborator::barceloneta
------
2016-02-19T00:15:48 ERROR plone.app.viewletmanager rendering of plone.portaltop in plone.header fails: 'TTWViewletRenderer' object has no attribute '__name__'

 - Expression: "provider:plone.portalheader"
 - Filename:   ... .17-py2.7.egg/plone/app/layout/viewlets/portal_header.pt
 - Location:   (line 2: col 32)
 - Source:     ... :replace="structure provider:plone.portalheader" />
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fbbff40ec50>
               views: <ViewMapper - at 0x7fbbfe6cdd10>
               modules: <instance - at 0x7fbc0d390488>
               args: <tuple - at 0x7fbc151f8050>
               here: <ImplicitAcquisitionWrapper front-page at 0x7fbc053bfcd0>
               user: <ImplicitAcquisitionWrapper - at 0x7fbc053bfc30>
               nothing: <NoneType - at 0x8f8340>
               container: <ImplicitAcquisitionWrapper front-page at 0x7fbc053bfcd0>
               request: <instance - at 0x7fbc04b05320>
               wrapped_repeat: <SafeMapping - at 0x7fbbff2fc520>
               traverse_subpath: <list - at 0x7fbbffc4c2d8>
               default: <object - at 0x7fbc15114520>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0x7fbc053bfcd0>
               view: <SimpleViewletClass from /home/Plone5/buildout-cache/eggs/plone.app.layout-2.5.17-py2.7.egg/plone/app/layout/viewlets/portal_header.pt plone.header at 0x7fbbfe841310>
               translate: <function translate at 0x7fbbfe670d70>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fbc053635a0>
               options: {...} (0)
               target_language: <NoneType - at 0x8f8340>
Traceback (most recent call last):
  File "/home/Plone5/buildout-cache/eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/Plone5/buildout-cache/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/simpleviewclass.py", line 44, in __call__
    return self.index(*args, **kw)
  File "/home/Plone5/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/Plone5/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/Plone5/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/Plone5/buildout-cache/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/Plone5/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "c242c498a2a5a48b8425bb70107d4427.py", line 99, in render
  File "/home/Plone5/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/expressions.py", line 74, in render_content_provider
    return cp.render()
  File "/home/Plone5/buildout-cache/eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 194, in render
    return BaseOrderedViewletManager.render(self)
  File "/home/Plone5/buildout-cache/eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 116, in render
    vname = viewlet.__name__
AttributeError: 'TTWViewletRenderer' object has no attribute '__name__'

 - Expression: "provider:plone.portalheader"
 - Filename:   ... .17-py2.7.egg/plone/app/layout/viewlets/portal_header.pt
 - Location:   (line 2: col 32)
 - Source:     ... :replace="structure provider:plone.portalheader" />
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fbbff40ec50>
               views: <ViewMapper - at 0x7fbbfe6cdd10>
               modules: <instance - at 0x7fbc0d390488>
               args: <tuple - at 0x7fbc151f8050>
               here: <ImplicitAcquisitionWrapper front-page at 0x7fbc053bfcd0>
               user: <ImplicitAcquisitionWrapper - at 0x7fbc053bfc30>
               nothing: <NoneType - at 0x8f8340>
               container: <ImplicitAcquisitionWrapper front-page at 0x7fbc053bfcd0>
               request: <instance - at 0x7fbc04b05320>
               wrapped_repeat: <SafeMapping - at 0x7fbbff2fc520>
               traverse_subpath: <list - at 0x7fbbffc4c2d8>
               default: <object - at 0x7fbc15114520>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0x7fbc053bfcd0>
               view: <SimpleViewletClass from /home/Plone5/buildout-cache/eggs/plone.app.layout-2.5.17-py2.7.egg/plone/app/layout/viewlets/portal_header.pt plone.header at 0x7fbbfe841310>
               translate: <function translate at 0x7fbbfe670d70>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fbc053635a0>
               options: {...} (0)
               target_language: <NoneType - at 0x8f8340>


------
2016-02-19T00:15:49 ERROR Zope.SiteErrorLog 1455840949.770.744878198533 https://big5.netfm.org/MyCollaborator/++plone++static/++unique++2014-08-14%2000%3A00%3A00.000003/contenttypes-sprite.png
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 508, in traverse
  Module ZPublisher.BaseRequest, line 344, in traverseName
  Module plone.resource.directory, line 224, in publishTraverse
NotFound
------
2016-02-19T00:15:49 ERROR plone.app.viewletmanager rendering of plone.portaltop in plone.header fails: 'TTWViewletRenderer' object has no attribute '__name__'

 - Expression: "provider:plone.portalheader"
 - Filename:   ... .17-py2.7.egg/plone/app/layout/viewlets/portal_header.pt
 - Location:   (line 2: col 32)
 - Source:     ... :replace="structure provider:plone.portalheader" />
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fbbff40ec50>
               views: <ViewMapper - at 0x7fbbfd7df410>
               modules: <instance - at 0x7fbc0d390488>
               args: <tuple - at 0x7fbc151f8050>
               here: <ImplicitAcquisitionWrapper MyCollaborator at 0x7fbc053b7a00>
               user: <SpecialUser - at 0x7fbc0f3d7350>
               nothing: <NoneType - at 0x8f8340>
               container: <ImplicitAcquisitionWrapper MyCollaborator at 0x7fbc053b7a00>
               request: <instance - at 0x7fbc04932878>
               wrapped_repeat: <SafeMapping - at 0x7fbbfd713db8>
               traverse_subpath: <list - at 0x7fbbfd882e18>
               default: <object - at 0x7fbc15114520>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper MyCollaborator at 0x7fbc053b7a00>
               view: <SimpleViewletClass from /home/Plone5/buildout-cache/eggs/plone.app.layout-2.5.17-py2.7.egg/plone/app/layout/viewlets/portal_header.pt plone.header at 0x7fbbfd7dfa50>
               translate: <function translate at 0x7fbbfd84f2a8>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fbc053bf640>
               options: {...} (0)
               target_language: <NoneType - at 0x8f8340>
Traceback (most recent call last):
  File "/home/Plone5/buildout-cache/eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/Plone5/buildout-cache/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/simpleviewclass.py", line 44, in __call__
    return self.index(*args, **kw)
  File "/home/Plone5/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/Plone5/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/Plone5/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/Plone5/buildout-cache/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/Plone5/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "c242c498a2a5a48b8425bb70107d4427.py", line 99, in render
  File "/home/Plone5/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/expressions.py", line 74, in render_content_provider
    return cp.render()
  File "/home/Plone5/buildout-cache/eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 194, in render
    return BaseOrderedViewletManager.render(self)
  File "/home/Plone5/buildout-cache/eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 116, in render
    vname = viewlet.__name__
AttributeError: 'TTWViewletRenderer' object has no attribute '__name__'

 - Expression: "provider:plone.portalheader"
 - Filename:   ... .17-py2.7.egg/plone/app/layout/viewlets/portal_header.pt
 - Location:   (line 2: col 32)
 - Source:     ... :replace="structure provider:plone.portalheader" />
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fbbff40ec50>
               views: <ViewMapper - at 0x7fbbfd7df410>
               modules: <instance - at 0x7fbc0d390488>
               args: <tuple - at 0x7fbc151f8050>
               here: <ImplicitAcquisitionWrapper MyCollaborator at 0x7fbc053b7a00>
               user: <SpecialUser - at 0x7fbc0f3d7350>
               nothing: <NoneType - at 0x8f8340>
               container: <ImplicitAcquisitionWrapper MyCollaborator at 0x7fbc053b7a00>
               request: <instance - at 0x7fbc04932878>
               wrapped_repeat: <SafeMapping - at 0x7fbbfd713db8>
               traverse_subpath: <list - at 0x7fbbfd882e18>
               default: <object - at 0x7fbc15114520>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper MyCollaborator at 0x7fbc053b7a00>
               view: <SimpleViewletClass from /home/Plone5/buildout-cache/eggs/plone.app.layout-2.5.17-py2.7.egg/plone/app/layout/viewlets/portal_header.pt plone.header at 0x7fbbfd7dfa50>
               translate: <function translate at 0x7fbbfd84f2a8>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fbc053bf640>
               options: {...} (0)
               target_language: <NoneType - at 0x8f8340>
```

**Comment by gforcada** [comment]
Unrelated (maybe) to the error, but those 

```

------
2016-02-19T00:15:46 WARNING OFS.Uninstalled Could not import class 'LoginLockoutTool' from module 'Products.LoginLockout.loginlockout_tool'
------
2016-02-19T00:15:46 WARNING OFS.Uninstalled Could not import class 'PasswordStrength' from module 'Products.PasswordStrength.plugin'
------
2016-02-19T00:15:47 WARNING OFS.Uninstalled Could not import class 'WickedSettings' from module 'plone.app.controlpanel.markup'
```

Are telling you that you either need to do some cleanup so that these packages are no longer needed, or add them somewhere on your buildout so that the errors go away.

Most probably that will not fix you viewlet, but maybe they do.

**Comment by abadger1406** [comment]
Can I remove these packages from the new Plone5 setup ? And if so how ? Or do I need to remove these from the Plone4 setup before I do the upgrade, i.e remove them from buildout.cfg and run buildout ?

Also, found something related to error message, concerning permissions on customisations. So perhaps I need to change 'permissions' on these.

http://plone.293351.n2.nabble.com/After-Plone-4-3-3-upgrade-AttributeError-TTWViewletRenderer-object-has-no-attribute-name-td7571304.html

Thanks again for the fast help...

**Comment by abadger1406** [comment]
Still a bit stuck on getting this Plone 5 upgrade completed. Would the following be useful to help resolve this error "AttributeError: 'TTWViewletRenderer' object has no attribute '__name__' "

https://pypi.python.org/pypi/wildcard.fixpersistentutilities/

Thanks dave

**Comment by MrTango** [comment]
I would first try to remove all customitations from portal_view_customizations. If the error disappears you can try to readd the customizations or move them into a package. 

Am 20. Februar 2016 07:05:21 OEZ, schrieb David Herring <notifications@github.com>:
>
>Still a bit stuck on getting this Plone 5 upgrade completed. Would the
>following be useful to help resolve this error "AttributeError:
>'TTWViewletRenderer' object has no attribute '__name__' "
>
>https://pypi.python.org/pypi/wildcard.fixpersistentutilities/
>
>Thanks dave
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/plone/Products.CMFPlone/issues/1402#issuecomment-186511644

-- 
Mit freundlichen Grüßen 
Maik Derstappen

**Comment by abadger1406** [comment]
Funny, now I cannot bring up my Plone 5 site...in browser see:-

LocationError(None, 'macros') (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: 'TTWViewletRenderer' object has no attribute '__name__')

**Comment by abadger1406** [comment]
Is there an obvious way o remove all the 'yellow highlighted'
customisations ?

thx dave

On 20 February 2016 at 09:06, Maik Derstappen <notifications@github.com>
wrote:

> I would first try to remove all customitations from
> portal_view_customizations. If the error disappears you can try to readd
> the customizations or move them into a package.
>
> Am 20. Februar 2016 07:05:21 OEZ, schrieb David Herring <
> notifications@github.com>:
> >
> >Still a bit stuck on getting this Plone 5 upgrade completed. Would the
> >following be useful to help resolve this error "AttributeError:
> >'TTWViewletRenderer' object has no attribute '__name__' "
> >
> >https://pypi.python.org/pypi/wildcard.fixpersistentutilities/
> >
> >Thanks dave
> >
> >---
> >Reply to this email directly or view it on GitHub:
> >
> https://github.com/plone/Products.CMFPlone/issues/1402#issuecomment-186511644
>
> --
> Mit freundlichen Grüßen
> Maik Derstappen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/Products.CMFPlone/issues/1402#issuecomment-186545722>
> .
>



-- 
David Herring

**Comment by cewing** [comment]
@abadger1406 IIRC, the `contents` tab of the `portal_view_customizations` tool lists the items that have been customized.  From that tab you can delete them.

**Comment by jensens** [comment]
It seems the suggestion by @cewing solved your problem? So I close the issue. If I'am wrong please just reopen it,
