### ISSUE TITLE
Upgrade from plone 4.3.6  to 5.0.2 - help requested

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1428]
i upgraded from plone 4.4.6 to 4.3.7 and then to 5.0.2. getting following errors. buildout runs ok. but the following errors show in fg mode in client 1. (it is a zeocluster install)

ssp@mail:/usr/local/Plone/zeocluster$ sudo bin/client1 fg
2016-03-01 08:04:45 INFO ZServer HTTP server started at Tue Mar  1 08:04:45 2016
        Hostname: 0.0.0.0
        Port: 8080
2016-03-01 08:04:45 INFO Zope Set effective user to "plone_daemon"
2016-03-01 08:04:54 INFO Products.PloneFormGen gpg_subprocess initialized, using /usr/bin/gpg
2016-03-01 08:04:54 INFO Products.PloneHotfix20150910 Applied addMember patch
2016-03-01 08:04:54 INFO Products.PloneHotfix20150910 Applied isURLInPortal patch
2016-03-01 08:04:54 WARNING Products.PloneHotfix20150910 Could not apply kupu
2016-03-01 08:04:54 INFO Products.PloneHotfix20150910 Applied setHeader patch
2016-03-01 08:04:54 INFO Products.PloneHotfix20150910 Hotfix installed
2016-03-01 08:04:55 INFO ZEO.ClientStorage zeostorage ClientStorage (pid=8567) created RW/normal for storage: '1'
2016-03-01 08:04:55 INFO ZEO.cache created temporary cache file '<fdopen>'
2016-03-01 08:04:55 INFO ZEO.ClientStorage zeostorage Testing connection <ManagedClientConnection ('127.0.0.1', 8100)>
2016-03-01 08:04:55 INFO ZEO.zrpc.Connection(C) (127.0.0.1:8100) received handshake 'Z3101'
2016-03-01 08:04:55 INFO ZEO.ClientStorage zeostorage Server authentication protocol None
2016-03-01 08:04:55 INFO ZEO.ClientStorage zeostorage Connected to storage: ('localhost.localdomain', 8100)
2016-03-01 08:04:55 INFO ZEO.ClientStorage zeostorage No verification necessary -- empty cache
2016-03-01 08:04:56 WARNING eea.daviz eea.relations is not installed
2016-03-01 08:04:56 WARNING eea.daviz eea.dataservice is not installed
2016-03-01 08:04:56 INFO collective.easyslider easytemplate not installed. Can not install slider tag
2016-03-01 08:04:56 INFO root Registering /usr/local/Plone/zeocluster/parts/client1/../../zettwerk.ui.downloads as zettwerk.ui.themes
2016-03-01 08:05:11 INFO ZEO.ClientStorage zeostorage Disconnected from storage: "('localhost.localdomain', 8100)"
Traceback (most recent call last):
  File "/usr/local/Plone/zeocluster/parts/client1/bin/interpreter", line 394, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
    self.startZope()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
    Zope2.startup()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/startup.py", line 118, in startup
    load_zcml()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/usr/local/Plone/buildout-cache/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py", line 104, in includePluginsDirective
    includeZCMLGroup(_context, info, filename)
  File "/usr/local/Plone/buildout-cache/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py", line 30, in includeZCMLGroup
    include(_context, filename, includable_package)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 705, in finish
    args = toargs(context, *self.argdata)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 1397, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py", line 137, in fromUnicode
    value = self.context.resolve(name)
  File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 179, in resolve
    mod = __import__(mname, *_import_chickens)
  File "/usr/local/Plone/buildout-cache/eggs/Products.PloneFormGen-1.7.16-py2.7.egg/Products/PloneFormGen/events.py", line 5, in <module>
    from Products.CMFPlone.interfaces import IFactoryTool
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/usr/local/Plone/zeocluster/parts/client1/etc/site.zcml", line 15.2-15.55
    ZopeXMLConfigurationError: File "/usr/local/Plone/zeocluster/parts/client1/etc/package-includes/002-collective.z3cform.widgets-configure.zcml", line 1.0-1.70
    ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/collective.z3cform.widgets-1.0b11-py2.7.egg/collective/z3cform/widgets/configure.zcml", line 13.4-13.45
    ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/plone.app.dexterity-2.1.17-py2.7.egg/plone/app/dexterity/configure.zcml", line 11.2-11.41
    ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/plone.app.z3cform-1.1.8-py2.7.egg/plone/app/z3cform/configure.zcml", line 10.2-10.41
    ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/plone.app.widgets-2.0.2-py2.7.egg/plone/app/widgets/configure.zcml", line 14.2-14.41
    ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/Products.CMFPlone-5.0.2-py2.7.egg/Products/CMFPlone/configure.zcml", line 108.4-112.10
    ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/Products.PloneFormGen-1.7.16-py2.7.egg/Products/PloneFormGen/configure.zcml", line 134.2-134.54
    ImportError: cannot import name IFactoryTool
ssp@mail:/usr/local/Plone/zeocluster$

**Comment by sudhan77** [comment]
**Eggs  **
 Plone
    Pillow
    Products.CMFPlomino
#    plomino.patternslib
   eea.tags
   Products.PloneFormGen
   plone.app.jquerytools
   quintagroup.plonecaptchas==4.2
  collective.z3cform.widgets
    Products.EasyNewsletter
    sc.social.like
#    collective.mediaelementjs==0.4.2
    eea.daviz==9.1
    collective.tablepage
    Products.ECLecture
    collective.easyslider
    eea.geotags
#    collective.geo.bundle [dexterity]
#    collective.geo.bundle
    zettwerk.mobile
    zettwerk.ui

#    plone.app.jquery==1.7.2
    wildcard.media==1.1

    Products.PloneHotfix20150910
#    collective.dancing==0.9.10

    plone.app.widgets[archetypes,dexterity]

    plone.app.widgets[archetypes,dexterity]

#    collective.dancing

#    collective.examples.userdata <0.4
    plone.app.users

#    quintagroup.plonecaptchas >=4.0
#    collective.captcha
#    collective.registrationcaptcha
#    plone.formwidget.captcha
#    collective.z3cform.norobots
#    medialog.mobilethemeTwo
    wildcard.fixmissing
    ftw.upgrade
#    plonethemes.suite
#    plonetheme.diazo_responsivetheme
#    collective.responsivetheme
#    goomdl.theme
    medialog.googlefonts== 2.1

# ZCML Slugs
# ----------
# Some eggs need ZCML slugs to tell Zope to
# use them. This is increasingly rare.
zcml =
#    quintagroup.plonecaptchas
    collective.z3cform.widgets
    eea.geotags
    eea.daviz-overrides
    eea.daviz-full
    collective.geo.bundle
    plone.app.widgets

#    collective.dancing
    collective.examples.userdata
#    quintagroup.plonecaptchas
#    plone.reload
#     collective.captcha
#     collective.registrationcaptcha
#    plone.formwidget.captcha

**Versions
**
setuptools = 0.7.2
zc.buildout = 2.2.1
ZopeSkel = 2.21.2
Cheetah = 2.2.1
Products.DocFinderTab = 1.0.5
buildout.sanitycheck = 1.0b1
collective.recipe.backup = 2.17
plone.recipe.unifiedinstaller = 4.3.1
zopeskel.dexterity = 1.5.4.1
zopeskel.diazotheme = 1.1
collective.examples.userdata = 0.3.1
collective.js.datatables = 2.0.1
z3c.form = 3.2.4

**Comment by ebrehault** [comment]
A big part of your add-ons are not Plone 5 compliant.
You first need to clean up your eggs list, and re-run buildout.

**Comment by hvelarde** [comment]
please open this kind of help requests in https://community.plone.org/

**Comment by gforcada** [comment]
@sudhan77 in this specific error that you have it's due to PloneFormGen expecting some import to exist on CMFPlone which is no longer there. PloneFormGen is still in alpha support for Plone 5.

**Comment by mauritsvanrees** [comment]
Oh, Products.PloneFormGen 1.8.0 is fine with Plone 5:
https://pypi.python.org/pypi/Products.PloneFormGen/1.8.0
(Some more modernisations would be good, but it works.)
