### ISSUE TITLE
Plone 4.3.x - plone.app.iterate - Fix exception for dexterity content types when get working copy

### ISSUE THREAD

**Issue by rodfersou** [plone/Products.CMFPlone#1541]
```
2016-04-20 11:18:43 ERROR plone.app.viewletmanager rendering of plone.abovecontent in plone.app.iterate.baseline_info fails: getBRefs
Traceback (most recent call last):
  File "/srv/cache/eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/srv/cache/eggs/plone.app.iterate-2.1.14-py2.7.egg/plone/app/iterate/browser/info.py", line 98, in render
    working_copy = self.working_copy()
  File "/srv/cache/eggs/plone.memoize-1.1.2-py2.7.egg/plone/memoize/instance.py", line 51, in memogetter
    val = func(*args, **kwargs)
  File "/srv/cache/eggs/plone.app.iterate-2.1.14-py2.7.egg/plone/app/iterate/browser/info.py", line 109, in working_copy
    refs = self.context.getBRefs( WorkingCopyRelation.relationship )
AttributeError: getBRefs
```

**Comment by frapell** [comment]
@rodfersou Next time, when you include something like "fixes gh-1541" in the commit message itself, then not only the commit gets linked with the issue, but the issue gets closed automatically when the PR is merged in :)

**Comment by frapell** [comment]
@rodfersou heh, sorry, they are coming from different packages, I'm not sure if you can link it like I said from the commit msg... too early for me ;)

**Comment by rodfersou** [comment]
@frapell no problem!
