### ISSUE TITLE
Migration 4309 to 5015 fails with umlaute in portal.title

### ISSUE THREAD

**Issue by 2silver** [plone/Products.CMFPlone#1633]
```
Traceback (most recent call last):
  File "/Users/nscgraf/Projects/.buildout/eggs/Products.CMFPlone-5.0.4-py2.7.egg/Products/CMFPlone/MigrationTool.py", line 268, in upgrade
    step['step'].doStep(setup)
  File "/Users/nscgraf/Projects/.buildout/eggs/Products.GenericSetup-1.8.2-py2.7.egg/Products/GenericSetup/upgrade.py", line 166, in doStep
    self.handler(tool)
  File "/Users/nscgraf/Projects/.buildout/eggs/plone.app.upgrade-1.3.24-py2.7.egg/plone/app/upgrade/v50/alphas.py", line 315, in upgrade_site_controlpanel_settings
    settings.site_title = unicode(portal.title)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
```

Plone 4.3.9 > 5.0.4 or
Plone 4.3.9 > 5.0.2

**Comment by tomgross** [comment]
@2silver This should be easy to fix: Two lines in _plone.app.upgrade.v50.alphas.py_ need to be changed:
```
from Products.CMFPlone.utils import safe_unicode
settings.site_title = safe_unicode(portal.title)
settings.webstats_js = unicode(site_properties.webstats_js)
```
As a workaround remove the umlaut and readd it after upgrade in the registry (ISiteSchema) in the control panel

**Comment by davisagli** [comment]
This was fixed in https://github.com/plone/plone.app.upgrade/pull/176
