### ISSUE TITLE
Products.PortalTransforms 2.2.0 ReStructuredText transform breaks Products.Archetypes tests

### ISSUE THREAD

**Issue by seanupton** [plone/Products.CMFPlone#1687]
Products.Archetypes tests are currently failing (as of 2016-07-21) on coredev buildout 5.1 branch, likely due to changes in rest transform in Products.PortalTransforms 2.2.0.

```
Failure in test testSame (Products.Archetypes.tests.test_baseunit.BaseUnitTestSubclass)
Traceback (most recent call last):
  File "/Users/sean/projects/dev43/python/parts/opt/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/sean/projects/buildout.coredev/src/Products.Archetypes/Products/Archetypes/tests/test_baseunit.py", line 68, in testSame
    self.assertEqual(got, expected)
  File "/Users/sean/projects/dev43/python/parts/opt/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/sean/projects/dev43/python/parts/opt/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: '<h2 class="title">Heading 1</h2><p>Some text.</p><div class="section" id="heading-2"><h2>Heading 2</h2><p>Some text, bla ble bli blo blu. Yes, i know this is<a class="reference external" href="http://www.example.com">Stupid</a>.</p></div>' != '<h2 class="title">Heading 1</h2><p>Some text.</p><div class="section" id="heading-2"><h3>Heading 2</h3><p>Some text, bla ble bli blo blu. Yes, i know this is<a class="reference external" href="http://www.example.com">Stupid</a>.</p></div>'
```

Ref:
https://github.com/plone/Products.PortalTransforms/commit/e9ff23b7f56297dadcfe91f4108b0d8b39ed2c6a

https://community.plone.org/t/products-portaltransforms-2-2-0-breaks-products-archetypes-tests-re-restructuredtext-headings/2520

**Comment by seanupton** [comment]
https://github.com/plone/Products.PortalTransforms/pull/15 should solve this.

**Comment by davisagli** [comment]
We are no longer developing Plone 5.1 or Archetypes, so I'll close this.
