### ISSUE TITLE
addPloneSite() causing error with plone.subrequest with old-style jsregistry.xml in Plone 5.0.5

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1731]
I have a custom setup script for a Plone 5 demo site (for XML Director).

https://github.com/xml-director/xmldirector.demo/blob/master/democontent/setup-plone.py#L44

This code leads to an unexpected error

```
-> addPloneSite(app, 'xml-director', extension_ids=['plonetheme.barceloneta:default', 'xmldirector.plonecore:default', 'xmldirector.demo:default', 'pp.client.plone:default'])

```

```
2016-08-27 12:35:23 ERROR plone.subrequest Error handling subrequest to http://nohost/xml-director/++resource++xmldirector.plonecore/ag-grid/dist/ag-grid.js
Traceback (most recent call last):
  File "/home/ajung/.buildout/eggs/plone.subrequest-1.7.0-py2.7.egg/plone/subrequest/__init__.py", line 143, in subrequest
    traversed = request.traverse(path)
  File "/home/ajung/.buildout/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/BaseRequest.py", line 525, in traverse
    return response.notFoundError(URL)
  File "/home/ajung/.buildout/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/HTTPResponse.py", line 718, in notFoundError
    "<p><b>Resource:</b> %s</p>" % escape(entry))
```

https://github.com/xml-director/xmldirector.plonecore/blob/master/xmldirector/plonecore/profiles/plone-5/jsregistry.xml#L8-L12

Where is this subrequest coming from? Why is there a need for a subrequest during the installation/setup of a new site?

**Comment by zopyx** [comment]
```
  <string>(1)<module>()
  /home/ajung/sandboxes/xmldirector.plonecore/src/xmldirector.demo/democontent/setup-plone.py(44)<module>()
-> addPloneSite(app, 'xml-director', extension_ids=['plonetheme.barceloneta:default', 'xmldirector.plonecore:default', 'xmldirector.demo:default', 'pp.client.plone:default'])
  /home/ajung/.buildout/eggs/Products.CMFPlone-5.0.5-py2.7.egg/Products/CMFPlone/factory.py(108)addPloneSite()
-> 'profile-%s' % content_profile_id)
  /home/ajung/.buildout/eggs/Products.GenericSetup-1.8.3-py2.7.egg/Products/GenericSetup/tool.py(379)runAllImportStepsFromProfile()
-> dependency_strategy=dependency_strategy)
  /home/ajung/.buildout/eggs/Products.GenericSetup-1.8.3-py2.7.egg/Products/GenericSetup/tool.py(1414)_runImportStepsFromContext()
-> message = self._doRunImportStep(step, context)
  /home/ajung/.buildout/eggs/Products.GenericSetup-1.8.3-py2.7.egg/Products/GenericSetup/tool.py(1226)_doRunImportStep()
-> return handler(context)
  /home/ajung/.buildout/eggs/Products.CMFPlone-5.0.5-py2.7.egg/Products/CMFPlone/resources/exportimport/cssregistry.py(16)importCSSRegistry()
-> return importResRegistry(context, _REG_ID, _REG_TITLE, _FILENAME)
  /home/ajung/.buildout/eggs/Products.CMFPlone-5.0.5-py2.7.egg/Products/CMFPlone/resources/exportimport/resourceregistry.py(36)importResRegistry()
-> importer.body = body
  /home/ajung/.buildout/eggs/Products.GenericSetup-1.8.3-py2.7.egg/Products/GenericSetup/utils.py(512)_importBody()
-> self._importNode(dom.documentElement)
  /home/ajung/.buildout/eggs/Products.CMFPlone-5.0.5-py2.7.egg/Products/CMFPlone/resources/exportimport/resourceregistry.py(163)_importNode()
-> cookWhenChangingSettings(self.context, legacy)
  /home/ajung/.buildout/eggs/Products.CMFPlone-5.0.5-py2.7.egg/Products/CMFPlone/resources/browser/cook.py(69)cookWhenChangingSettings()
-> response = subrequest(siteUrl + '/' + resource.js)
> /home/ajung/.buildout/eggs/plone.subrequest-1.7.0-py2.7.egg/plone/subrequest/__init__.py(73)subrequest()
-> assert url is not None, 'You must pass a url'
```

**Comment by zopyx** [comment]
I tested the addPloneSite() issue with other add-ons defining a cssregistry.xml or jsregistry.xml: same result. So adding a Plone site programmatically with "old-style" registries is completely broken.

**Comment by jensens** [comment]
I close this one, those registries are gone in 5.2 and wont fix for prior versions.
