### ISSUE TITLE
Upgrade from Plone 4.3.9 to Plone 5.0.6 fails

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#1756]
When trying to upgrade an empty Plone Instance from Plone 4.3.9 to 5.0.6-pending it fails with the following error (It is the standard buildout from collective.solr).

```
2016-09-11 10:23:17 ERROR plone.app.upgrade Upgrade aborted. Error:
Traceback (most recent call last):
  File "/home/tom/.buildout/eggs/Products.CMFPlone-5.0.6rc1-py2.7.egg/Products/CMFPlone/MigrationTool.py", line 268, in upgrade
    step['step'].doStep(setup)
  File "/home/tom/.buildout/eggs/Products.GenericSetup-1.8.2-py2.7.egg/Products/GenericSetup/upgrade.py", line 166, in doStep
    self.handler(tool)
  File "/home/tom/.buildout/eggs/plone.app.upgrade-1.3.27-py2.7.egg/plone/app/upgrade/v50/alphas.py", line 34, in to50alpha3
    loadMigrationProfile(context, 'profile-plone.app.upgrade.v50:to50alpha3')
  File "/home/tom/.buildout/eggs/plone.app.upgrade-1.3.27-py2.7.egg/plone/app/upgrade/utils.py", line 134, in loadMigrationProfile
    context.runAllImportStepsFromProfile(profile, purge_old=False)
  File "/home/tom/.buildout/eggs/Products.GenericSetup-1.8.2-py2.7.egg/Products/GenericSetup/tool.py", line 379, in runAllImportStepsFromProfile
    dependency_strategy=dependency_strategy)
  File "/home/tom/.buildout/eggs/Products.GenericSetup-1.8.2-py2.7.egg/Products/GenericSetup/tool.py", line 1414, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/home/tom/.buildout/eggs/Products.GenericSetup-1.8.2-py2.7.egg/Products/GenericSetup/tool.py", line 1226, in _doRunImportStep
    return handler(context)
  File "/home/tom/.buildout/eggs/Products.CMFPlone-5.0.6rc1-py2.7.egg/Products/CMFPlone/resources/exportimport/bundles.py", line 28, in combine
    combine_bundles(site)
  File "/home/tom/.buildout/eggs/Products.CMFPlone-5.0.6rc1-py2.7.egg/Products/CMFPlone/resources/browser/combine.py", line 109, in combine_bundles
    if PRODUCTION_RESOURCE_DIRECTORY not in container:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by 2silver** [comment]
Hav you tried this:
https://community.plone.org/t/plone-migration-4-3-4-to-5-0-errors/1507/18
