### ISSUE TITLE
KeyError: 'Field IDublinCore.title not found' in Plone 5.1

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1824]
A content-type  defined as

```
class ISmashDocument(model.Schema):
    pass

class SmashDocument(Item):

    implements(ISmashDocument)
```

```
  <property name="behaviors">
     <element value="plone.app.content.interfaces.INameFromTitle" />
     <element value="plone.app.dexterity.behaviors.metadata.IDublinCore"/>
  </property>
```

raises (in Plone 5.1)

```
2016-11-02 17:51:03 ERROR plone.autoform.base No field move possible for non-existing field named IDublinCore.title with target *
Traceback (most recent call last):
  File "/Users/ajung/.buildout/eggs/plone.autoform-1.7.0-py2.7.egg/plone/autoform/base.py", line 243, in _process_field_moves
    move(self, name, before=before, after=after, prefix=prefix)
  File "/Users/ajung/.buildout/eggs/plone.z3cform-0.9.0-py2.7.egg/plone/z3cform/fieldsets/utils.py", line 85, in move
    raise KeyError("Field %s not found" % field_name)
KeyError: 'Field IDublinCore.title not found'
```

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
