### ISSUE TITLE
Memory leaks while deleting user

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1829]
Plone 4.3.6 instance running in ZEO client configuration, ZODB with some hundreds users on it; when the following code is reached:

```python
    def remove_subscriber(self, email):
        logger.info(u'Removing user "{0}"'.format(email))
        with api.env.adopt_roles(['Manager']):
            api.user.delete(username=email)
```

a memory leak occurs as you can see from this [memmon](http://superlance.readthedocs.io/en/latest/memmon.html) log:

```
Checking groups app=1310720000
RSS of app:instance1 is 814948352
RSS of app:instance2 is 816472064
...
Checking groups app=1310720000
RSS of app:instance1 is 829448192
RSS of app:instance2 is 1014804480
Checking groups app=1310720000
RSS of app:instance1 is 840863744
RSS of app:instance2 is 1149530112
Checking groups app=1310720000
RSS of app:instance1 is 840998912
RSS of app:instance2 is 1290305536
Checking groups app=1310720000
RSS of app:instance1 is 841093120
RSS of app:instance2 is 1438318592
Restarting app:instance2
```

**Comment by hvelarde** [comment]
this is the last thing I see in the event log before the instance restarts:

```python
2016-11-07T20:25:01 ERROR Zope.SiteErrorLog 1478557501.960.304891657693 http://www.example.com/remove_notification
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module my.package.browser.notification, line 67, in __call__
  Module my.package.browser.notification, line 112, in remove_subscriber
  Module plone.api.user, line 2, in delete
  Module plone.api.validation, line 100, in wrapped
  Module plone.api.user, line 2, in delete
  Module plone.api.validation, line 131, in wrapped
  Module plone.api.user, line 192, in delete
  Module <string>, line 4, in deleteMembers
  Module plone.protect.utils, line 56, in _curried
  Module <string>, line 4, in deleteMembers
  Module AccessControl.requestmethod, line 70, in _curried
  Module Products.CMFCore.MembershipTool, line 520, in deleteMembers
  Module <string>, line 4, in deleteLocalRoles
  Module plone.protect.utils, line 56, in _curried
  Module <string>, line 4, in deleteLocalRoles
  Module AccessControl.requestmethod, line 70, in _curried
  Module Products.CMFCore.MembershipTool, line 462, in deleteLocalRoles
  Module <string>, line 4, in deleteLocalRoles
  Module plone.protect.utils, line 56, in _curried
  Module <string>, line 4, in deleteLocalRoles
  Module AccessControl.requestmethod, line 70, in _curried
  Module Products.CMFCore.MembershipTool, line 462, in deleteLocalRoles
  Module <string>, line 4, in deleteLocalRoles
  Module plone.protect.utils, line 56, in _curried
  Module <string>, line 4, in deleteLocalRoles
  Module AccessControl.requestmethod, line 70, in _curried
  Module Products.CMFCore.MembershipTool, line 461, in deleteLocalRoles
  Module Products.CMFCore.PortalFolder, line 195, in contentValues
  Module Products.CMFCore.PortalFolder, line 180, in contentItems
  Module plone.folder.ordered, line 76, in objectIds
  Module plone.folder.default, line 144, in idsInOrder
  Module plone.folder.default, line 156, in _order
  Module zope.annotation.attribute, line 44, in get
  Module ZODB.Connection, line 860, in setstate
  Module ZODB.Connection, line 901, in _setstate
AttributeError: 'NoneType' object has no attribute 'load'
```

I'm updating Plone to latest version (4.3.11) to see if that fixes the issue.

**Comment by hvelarde** [comment]
maybe related with https://github.com/plone/plone.protect/issues/52

**Comment by hvelarde** [comment]
I disabled CSRF protection using the following:

```python
     def remove_subscriber(self, email):
        from plone.protect.interfaces import IDisableCSRFProtection
        from zope.interface import alsoProvides
        alsoProvides(self.request, IDisableCSRFProtection)
         logger.info(u'Removing user "{0}"'.format(email))
         with api.env.adopt_roles(['Manager']):
             api.user.delete(username=email)
```

the leak is still present:

```
2016-11-08T10:19:41 INFO my.package Removing user "user@example.com"
------
2016-11-08T10:24:01 INFO SignalHandler Caught signal SIGTERM
------
2016-11-08T10:24:01 INFO Z2 Shutting down fast
------
2016-11-08T10:24:01 INFO ZServer closing HTTP to new connections
------
2016-11-08T10:24:01 INFO ZEO.ClientStorage zeostorage Disconnected from storage: "('10.133.255.48', 8100)"
------
2016-11-08T10:24:01 ERROR ZODB.Connection Couldn't load state for 0x2ad64c
Traceback (most recent call last):
  File "/home/my/package/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/home/my/package/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 901, in _setstate
    p, serial = self._storage.load(obj._p_oid, '')
  File "/home/my/package/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZEO/ClientStorage.py", line 833, in load
    data, tid = self._server.loadEx(oid)
  File "/home/my/package/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZEO/ServerStub.py", line 176, in loadEx
    return self.rpc.call("loadEx", oid)
  File "/home/my/package/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZEO/zrpc/connection.py", line 763, in call
    r_args = self.wait(msgid)
  File "/home/my/package/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZEO/zrpc/connection.py", line 783, in wait
    raise DisconnectedError()
DisconnectedError
------
2016-11-08T10:24:01 ERROR ZODB.Connection Couldn't load state for 0x2ae10e
Traceback (most recent call last):
  File "/home/my/package/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/home/my/package/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 901, in _setstate
    p, serial = self._storage.load(obj._p_oid, '')
AttributeError: 'NoneType' object has no attribute 'load'
------
2016-11-08T10:24:01 ERROR ZODB.Connection Couldn't load state for 0x2ae10e
Traceback (most recent call last):
  File "/home/my/package/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/home/my/package/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 901, in _setstate
    p, serial = self._storage.load(obj._p_oid, '')
AttributeError: 'NoneType' object has no attribute 'load'
```

**Comment by hvelarde** [comment]
seems an expected behavior: https://community.plone.org/t/alternate-way-do-delete-users/3009/2?u=hvelarde
