### ISSUE TITLE
ImportError: No module named fieldsets.fieldsets

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1897]
### What I did:

I'm trying to test an add-on ([sc.embedder](https://github.com/simplesconsultoria/sc.embedder)) in Plone 5.1; I modified the buildout to include Plone 5.1 instead of the standard Plone 4.3.

I ran the buildout without issues.

### What I expect to happen:

Start a working instance.

### What actually happened:

When trying to start the instance, the following traceback is shown:

```python
$ bin/instance fg
2017-01-06 14:57:12 INFO ZServer HTTP server started at Fri Jan  6 14:57:12 2017
	Hostname: 0.0.0.0
	Port: 8080
/home/hvelarde/.buildout/eggs/plone.app.dexterity-2.3.2-py2.7.egg/plone/app/dexterity/__init__.py:12: DeprecationWarning: Name clash, now use '_' as usal. Will be removed in Plone 5.2
  DeprecationWarning)
/home/hvelarde/.buildout/eggs/plone.app.multilingual-4.0.3-py2.7.egg/plone/app/multilingual/browser/migrator.py:11: DeprecationWarning: LanguageRootFolder: LanguageRootFolders should be migrate to DexterityContainers
  from plone.app.multilingual.content.lrf import LanguageRootFolder
/home/hvelarde/.buildout/eggs/plone.portlet.collection-3.1-py2.7.egg/plone/portlet/collection/collection.py:2: DeprecationWarning: isDefaultPage is deprecated. Import from Products.CMFPlone instead
  from plone.app.layout.navigation.defaultpage import isDefaultPage
/home/hvelarde/.buildout/eggs/Products.CMFPlone-5.1a2-py2.7.egg/Products/CMFPlone/browser/syndication/views.py:16: DeprecationWarning: wrap_form is deprecated. Import from plone.z3cform.layout instead.
  from plone.app.z3cform.layout import wrap_form
2017-01-06 14:57:16 INFO Plone OpenID system packages not installed, OpenID support not available
/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py:179: DeprecationWarning: plone.app.z3cform.object has moved to plone.app.z3cform.objectsubform. Import of plone.app.z3cform.object will become unsupported in Version 3.0, because "object" in a builtin
  mod = __import__(mname, *_import_chickens)
Traceback (most recent call last):
  File "/home/hvelarde/collective/sc.embedder/parts/instance/bin/interpreter", line 292, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/hvelarde/.buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/hvelarde/.buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/hvelarde/.buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/home/hvelarde/.buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/home/hvelarde/.buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/hvelarde/.buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/App/startup.py", line 118, in startup
    load_zcml()
  File "/home/hvelarde/.buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/home/hvelarde/.buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/hvelarde/.buildout/eggs/Zope2-2.13.24-py2.7.egg/OFS/metaconfigure.py", line 46, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/home/hvelarde/collective/buildout.python/parts/opt/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 705, in finish
    args = toargs(context, *self.argdata)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 1397, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py", line 137, in fromUnicode
    value = self.context.resolve(name)
  File "/home/hvelarde/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 179, in resolve
    mod = __import__(mname, *_import_chickens)
  File "/home/hvelarde/.buildout/eggs/Products.TinyMCE-1.4.3-py2.7.egg/Products/TinyMCE/browser/controlpanel.py", line 7, in <module>
    from plone.fieldsets.fieldsets import FormFieldsets
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/hvelarde/collective/sc.embedder/parts/instance/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/home/hvelarde/.buildout/eggs/Products.TinyMCE-1.4.3-py2.7.egg/Products/TinyMCE/configure.zcml", line 15.2-15.32
    ZopeXMLConfigurationError: File "/home/hvelarde/.buildout/eggs/Products.TinyMCE-1.4.3-py2.7.egg/Products/TinyMCE/browser/configure.zcml", line 11.4-16.10
    ImportError: No module named fieldsets.fieldsets
```

Seems like a missing dependency.

### What version of Plone/ Addons I am using:

Plone 5.1a2.

**Comment by hvelarde** [comment]
happens also in Plone 5.0.6; seems to be a missing dependency in Products.TinyMCE 1.4.3.

**Comment by hvelarde** [comment]
my bad, Products.TinyMCE is no longer a dependency of Plone 5.
