### ISSUE TITLE
Robot tests with Zope 4: WebDriverException: Message: $ is not defined

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1933]
This is with Plone coredev 5.1 with `plip-zope4.cfg`. Locally the robot tests run fine, but on Jenkins there are problems. See for example http://jenkins.plone.org/view/PLIPs/job/plip-zope4/89/testReport/junit/Products.CMFPlone.tests.test_robot/RobotTestCase/Scenario_Create_new_group/

```
WebDriverException: Message: $ is not defined
Stacktrace:
    at anonymous (http://localhost:46259/plone/@@usergroup-groupdetails line 69 > Function:1)
    at handleEvaluateEvent (http://localhost:46259/plone/@@usergroup-groupdetails:69)

  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jenkins/.buildout/eggs/robotsuite-2.0.0-py2.7.egg/robotsuite/__init__.py", line 458, in runTest
    assert last_status == 'PASS', last_message
```

So `$` is not available for Selenium to use. I tried switching this to `jQuery` or to `window.jQuery`, which was also fine locally, but this did not help on Jenkins.
I fixed half of those by removing some use of jQuery in c11527bf12093011d19fadd477a970c31ae4c118.
But the robot tests use it in more cases.

This is what the robot report looks like on Jenkins:

<img width="845" alt="screen shot 2017-02-04 at 11 30 16" src="https://cloud.githubusercontent.com/assets/210587/22617809/ec53696a-eacd-11e6-9d59-8de33f94df8c.png">

And this is the screen shot that is created during the test teardown:

![robot_test_controlpanel_usergroups_scenario_create_new_group_selenium-screenshot-1](https://cloud.githubusercontent.com/assets/210587/22617812/0ac57b4a-eace-11e6-9c9d-5a16216ea01f.png)

**Comment by mauritsvanrees** [comment]
@davisagli saw that the html does not contain any css or javascript, which can be seen in the screen shot above too. It *has* gone through Diazo transform, as it contains html from the theme. But it does not contain an element with id `portal-top`, which means Diazo does not insert the css and javascript.

And: locally I now see the failure too. Running all tests for `Products.CMFPlone` is fine, but it fails when using `bin/alltests --xml --all`.

**Comment by mauritsvanrees** [comment]
I had a theory that this might be caused by an integration test that does a commit, which we currently allow in our branch of `plone.testing`, but this is not the case.

**Comment by mauritsvanrees** [comment]
When I add this to `alltests` it already goes wrong locally during the `plone.app.dexterity` tests:

```
alltests]
default-policy = exclude
include-groups = plone_app_testing
plone_app_testing =
    borg.localrole
    collective.monkeypatcher
    diazo
    icalendar
    plone.alterego
    plone.api
    plone.app.caching
    plone.app.content
    plone.app.contentlisting
    plone.app.contentmenu
    plone.app.contentrules
#    plone.app.contenttypes
    plone.app.customerize
    plone.app.dexterity
    plone.app.discussion
    plone.app.event
    plone.app.i18n
    plone.app.intid
    plone.app.iterate
    plone.app.layout
    plone.app.linkintegrity
    plone.app.portlets
    plone.app.querystring
    plone.app.redirector
    plone.app.registry
    plone.app.relationfield
    plone.app.testing
    plone.app.textfield
    plone.app.theming
    plone.app.upgrade
    plone.app.users
    plone.app.uuid
    plone.app.viewletmanager
    plone.app.vocabularies
    plone.app.workflow
    plone.app.z3cform
    plonetheme.barceloneta
    Products.CMFPlone
    Products.ExtendedPathIndex
    Products.PlacelessTranslationService
    Products.PlonePAS
    repoze.xmliter
    z3c.pt
    z3c.relationfield
```

I'm not sure what the order is. For example, the `plone.app.upgrade` are run before `plone.app.dexterity`.

**Comment by mauritsvanrees** [comment]
With this smaller list it also fails:

```
[alltests]
default-policy = exclude
include-groups = plone_app_testing
plone_app_testing =
    borg.localrole
    collective.monkeypatcher
#    diazo
    icalendar
    plone.alterego
    plone.api
    plone.app.caching
    plone.app.content
    plone.app.contentlisting
    plone.app.contentmenu
    plone.app.contentrules
#    plone.app.contenttypes
    plone.app.customerize
    plone.app.dexterity
```

A bit strange is that I commented out diazo, but its tests still get run, with one failure.

**Comment by mauritsvanrees** [comment]
Okay, apparently the way I try to restrict the packages that are being included in `alltests` is totally not working...

**Comment by mauritsvanrees** [comment]
Ah, I need to restrict it like this:

```
[test-groups]
plone_app_testing =
    borg.localrole
    collective.monkeypatcher
    plone.app.dexterity

[alltests]
default-policy = exclude
include-groups = plone_app_testing
```

With those single three all is fine.

**Comment by mauritsvanrees** [comment]
This still works:

```
[test-groups]
plone_app_testing =
    borg.localrole
    collective.monkeypatcher
#    diazo
    icalendar
    plone.alterego
    plone.api
    plone.app.caching
    plone.app.content
    plone.app.contentlisting
    plone.app.contentmenu
    plone.app.contentrules
#    plone.app.contenttypes
    plone.app.customerize
    plone.app.dexterity
```

This works too, at least for the `plone.app.contenttypes` tests:

```
plone_app_testing =
    diazo
    plone.app.contenttypes
    plone.app.customerize
    plone.app.dexterity
```

I broke the test run off after the first robot test passed.

It gets more interesting with this list:

```
[test-groups]
plone_app_testing =
    borg.localrole
    collective.monkeypatcher
#    diazo
    icalendar
    plone.alterego
    plone.api
    plone.app.caching
    plone.app.content
    plone.app.contentlisting
    plone.app.contentmenu
    plone.app.contentrules
#    plone.app.contenttypes
    plone.app.customerize
    plone.app.dexterity
    plone.app.discussion
    plone.app.event
    plone.app.i18n
    plone.app.intid
    plone.app.iterate
    plone.app.layout
    plone.app.linkintegrity
    plone.app.portlets
    plone.app.querystring
    plone.app.redirector
    plone.app.registry
    plone.app.relationfield
    plone.app.testing
    plone.app.textfield
    plone.app.theming
    plone.app.upgrade
    plone.app.users
    plone.app.uuid
    plone.app.viewletmanager
    plone.app.vocabularies
    plone.app.workflow
    plone.app.z3cform
    plonetheme.barceloneta
    Products.CMFPlone
    Products.ExtendedPathIndex
    Products.PlacelessTranslationService
    Products.PlonePAS
    repoze.xmliter
    z3c.pt
    z3c.relationfield
```

Then I quickly get lots of errors like this:

```
#### Running tests for group plone_app_testing ####
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:
                    
  Ran 267 tests with 0 failures, 0 errors, 0 skipped in 59.734 seconds.
Running plone.app.customerize.testing.PloneAppCustomerize:Functional tests:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
  Set up plone.testing.zca.LayerCleanup in 0.002 seconds.
  Set up plone.testing.z2.Startup in 0.060 seconds.
  Set up plone.app.customerize.testing.PloneAppCustomerize Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/5.1/src/zope.testrunner/src/zope/testrunner/runner.py", line 400, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/Users/maurits/community/plone-coredev/5.1/src/zope.testrunner/src/zope/testrunner/runner.py", line 708, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/Users/maurits/community/plone-coredev/5.1/src/zope.testrunner/src/zope/testrunner/runner.py", line 713, in setup_layer
    layer.setUp()
  File "/Users/maurits/community/plone-coredev/5.1/src/plone.app.testing/plone/app/testing/layers.py", line 108, in setUp
    self.setUpDefaultContent(app)
  File "/Users/maurits/community/plone-coredev/5.1/src/plone.app.testing/plone/app/testing/layers.py", line 234, in setUpDefaultContent
    extension_ids=self.extensionProfiles,
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.CMFPlone/Products/CMFPlone/factory.py", line 146, in addPloneSite
    setup_tool.runAllImportStepsFromProfile('profile-%s' % profile_id)
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.GenericSetup/Products/GenericSetup/tool.py", line 388, in runAllImportStepsFromProfile
    dependency_strategy=dependency_strategy)
   - __traceback_info__: profile-Products.CMFPlone:plone
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.GenericSetup/Products/GenericSetup/tool.py", line 1442, in _runImportStepsFromContext
    self._doRunHandler(post_handler)
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.GenericSetup/Products/GenericSetup/tool.py", line 1289, in _doRunHandler
    return handler_function(self)
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.CMFPlone/Products/CMFPlone/setuphandlers.py", line 168, in importFinalSteps
    "profile-Products.CMFPlone:dependencies")
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.GenericSetup/Products/GenericSetup/tool.py", line 388, in runAllImportStepsFromProfile
    dependency_strategy=dependency_strategy)
   - __traceback_info__: profile-Products.CMFPlone:dependencies
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.GenericSetup/Products/GenericSetup/tool.py", line 1433, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.GenericSetup/Products/GenericSetup/tool.py", line 1245, in _doRunImportStep
    return handler(context)
   - __traceback_info__: combine-bundles
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.CMFPlone/Products/CMFPlone/resources/exportimport/bundles.py", line 27, in combine
    combine_bundles(site)
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.CMFPlone/Products/CMFPlone/resources/browser/combine.py", line 169, in combine_bundles
    write_js(context, production_folder, 'default')
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.CMFPlone/Products/CMFPlone/resources/browser/combine.py", line 83, in write_js
    registry.records['plone.resources/jquery.js'].value
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.CMFPlone/Products/CMFPlone/resources/browser/combine.py", line 48, in get_resource
    resource = context.unrestrictedTraverse(path)
  File "/Users/maurits/community/plone-coredev/5.1/src/Zope2/src/OFS/Traversable.py", line 340, in unrestrictedTraverse
    raise e
   - __traceback_info__: (['jquery.min.js', 'dist', 'jquery', 'components'], '++plone++static')
AttributeError: 'TestRequest' object has no attribute 'environ'
```

**Comment by mauritsvanrees** [comment]
Almost out of power, so I'm going to have to investigate this another time.

**Comment by davisagli** [comment]
I finally managed to hit a pdb in a request where this is happening. Turns out the problem is that the plone.transformchain.zpublisher.applyTransformOnSuccess event handler is registered twice (due to a leak from another test, I guess). The first time it runs Diazo replaces #portal-top with its contents from the theme. The second time it runs it finds no #portal-top so skips some of the theming rules due to a condition in the Barceloneta theme's rule.

So the question remains: which test is leaking this event handler?

**Comment by davisagli** [comment]
The failing layer setup for the plone.app.upgrade RealUpgrade fixture was leaving things behind. I modified it to avoid throwing an exception during layer setup even if the zexp fails to import, and now all but a few of the robot tests are passing.

**Comment by mauritsvanrees** [comment]
Great job finding that one out! Thanks!
