### ISSUE TITLE
Plone 5.1b3 error KeyError: 'styles.css'

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2029]
I am currently trying to get

https://github.com/zopyx/pappnasen-plone5/tree/plone-5.1

running on Plone 5.1 (worked on Plone 5.0).

The buildout process is not the problem.

I have two additional setup scripts

```
bin/instance run setup-plone.py
bin/instance run setup-smashdocs.py
````

Loading the frontpage fails now with:

```
2017-04-24 10:02:01 ERROR plone.app.viewletmanager Error while rendering viewlet-manager=plone.htmlhead.links, viewlet=plone.resourceregistries.styles
Traceback (most recent call last):
  File "/home/docker/src/pappnasen-plone5/eggs/plone.app.viewletmanager-2.0.10-py2.7.egg/plone/app/viewletmanager/manager.py", line 112, in render
    html.append(viewlet.render())
  File "/home/docker/src/pappnasen-plone5/eggs/plone.app.layout-2.6.5-py2.7.egg/plone/app/layout/viewlets/common.py", line 59, in render
    return self.index()
  File "/home/docker/src/pappnasen-plone5/eggs/Zope2-2.13.26-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/docker/src/pappnasen-plone5/eggs/Zope2-2.13.26-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/docker/src/pappnasen-plone5/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/docker/src/pappnasen-plone5/eggs/five.pt-2.2.4-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/home/docker/src/pappnasen-plone5/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/docker/src/pappnasen-plone5/eggs/Chameleon-2.25-py2.7.egg/chameleon/zpt/template.py", line 261, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/docker/src/pappnasen-plone5/eggs/Chameleon-2.25-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/docker/src/pappnasen-plone5/eggs/Chameleon-2.25-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "a18fbbbd17778f1a3f5048f1a40ae396.py", line 88, in render
  File "/home/docker/src/pappnasen-plone5/eggs/five.pt-2.2.4-py2.7.egg/five/pt/expressions.py", line 161, in __call__
    return base()
  File "/home/docker/src/pappnasen-plone5/eggs/Products.CMFPlone-5.1b3-py2.7.egg/Products/CMFPlone/resources/browser/styles.py", line 90, in styles
    result = self.ordered_bundles_result()
  File "/home/docker/src/pappnasen-plone5/eggs/Products.CMFPlone-5.1b3-py2.7.egg/Products/CMFPlone/resources/browser/resource.py", line 222, in ordered_bundles_result
    self.get_data(bundle, result)
  File "/home/docker/src/pappnasen-plone5/eggs/Products.CMFPlone-5.1b3-py2.7.egg/Products/CMFPlone/resources/browser/styles.py", line 55, in get_data
    if not bundle.last_compilation\
  File "/home/docker/src/pappnasen-plone5/eggs/Products.CMFPlone-5.1b3-py2.7.egg/Products/CMFPlone/resources/bundle.py", line 79, in last_compilation
    loc, path = self._real_path(ctx)
  File "/home/docker/src/pappnasen-plone5/eggs/Products.CMFPlone-5.1b3-py2.7.egg/Products/CMFPlone/resources/bundle.py", line 36, in _real_path
    resource = getSite().restrictedTraverse(resource_path)
  File "/home/docker/src/pappnasen-plone5/eggs/Zope2-2.13.26-py2.7.egg/OFS/Traversable.py", line 317, in restrictedTraverse
    return self.unrestrictedTraverse(path, default, restricted=True)
  File "/home/docker/src/pappnasen-plone5/eggs/Zope2-2.13.26-py2.7.egg/OFS/Traversable.py", line 300, in unrestrictedTraverse
    raise e
KeyError: 'styles.css'

 - Expression: "view/styles"
 - Filename:   ... -py2.7.egg/Products/CMFPlone/resources/browser/styles.pt
 - Location:   (line 1: col 26)
 - Source:     <tal:styles repeat="style view/styles"
                                         ^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7efee7b20450>
               views: <ViewMapper - at 0x7efee70a3510>
               modules: <instance - at 0x7efef6689fc8>
               args: <tuple - at 0x7eff03873050>
               here: <ImplicitAcquisitionWrapper front-page at 0x7efee9c45050>
               user: <ImplicitAcquisitionWrapper - at 0x7efee9f274b0>
               nothing: <NoneType - at 0x7eff0365adc0>
               container: <ImplicitAcquisitionWrapper front-page at 0x7efee9c45050>
               request: <instance - at 0x7efee93fca70>
               wrapped_repeat: <SafeMapping - at 0x7efee5bf1418>
               traverse_subpath: <list - at 0x7efee74fdbd8>
               default: <object - at 0x7eff03849540>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0x7efee9c45050>
               view: <SimpleViewletClass from /home/docker/src/pappnasen-plone5/eggs/Products.CMFPlone-5.1b3-py2.7.egg/Products/CMFPlone/resources/browser/styles.pt plone.resourceregistries.styles at 0x7efee6ebbdd0>
               translate: <function translate at 0x7efee6ee6500>
               root: <ImplicitAcquisitionWrapper Zope at 0x7efee9f856e0>
               options: {...} (0)
               target_language: <NoneType - at 0x7eff0365adc0>

```

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
