### ISSUE TITLE
IFilterSchema defines a field valid_tags, for which there is no record

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2129]
When migrating from Plone 4.3.15 to the coredev (currently Plone 5.1b5.dev0 that includes the new safe_html transform from https://github.com/plone/Products.PortalTransforms/pull/20) the migration fails with the following traceback:

```
2017-08-29 13:17:30 ERROR plone.app.upgrade Upgrade aborted. Error:
Traceback (most recent call last):
  File "/Users/pbauer/workspace/netstal/src-mrd/Products.CMFPlone/Products/CMFPlone/MigrationTool.py", line 268, in upgrade
    step['step'].doStep(setup)
  File "/Users/pbauer/.cache/buildout/eggs/Products.GenericSetup-1.8.8-py2.7.egg/Products/GenericSetup/upgrade.py", line 166, in doStep
    self.handler(tool)
  File "/Users/pbauer/workspace/netstal/src-mrd/plone.app.upgrade/plone/app/upgrade/v50/betas.py", line 367, in to50rc1
    migrate_linkintegrity_relations(portal)
  File "/Users/pbauer/.cache/buildout/eggs/plone.app.linkintegrity-3.3.2-py2.7.egg/plone/app/linkintegrity/upgrades.py", line 36, in migrate_linkintegrity_relations
    modified(source_obj)
  File "/Users/pbauer/.cache/buildout/eggs/zope.lifecycleevent-3.6.2-py2.7.egg/zope/lifecycleevent/__init__.py", line 101, in modified
    notify(ObjectModifiedEvent(object, *descriptions))
  File "/Users/pbauer/.cache/buildout/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/Users/pbauer/.cache/buildout/eggs/zope.component-4.3.0-py2.7.egg/zope/component/event.py", line 27, in dispatch
    component_subscribers(event, None)
  File "/Users/pbauer/.cache/buildout/eggs/zope.component-4.3.0-py2.7.egg/zope/component/_api.py", line 139, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/pbauer/.cache/buildout/eggs/zope.interface-4.4.0-py2.7-macosx-10.12-x86_64.egg/zope/interface/registry.py", line 442, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/pbauer/.cache/buildout/eggs/zope.interface-4.4.0-py2.7-macosx-10.12-x86_64.egg/zope/interface/adapter.py", line 598, in subscribers
    subscription(*objects)
  File "/Users/pbauer/.cache/buildout/eggs/zope.component-4.3.0-py2.7.egg/zope/component/event.py", line 36, in objectEventNotify
    component_subscribers((event.object, event), None)
  File "/Users/pbauer/.cache/buildout/eggs/zope.component-4.3.0-py2.7.egg/zope/component/_api.py", line 139, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/pbauer/.cache/buildout/eggs/zope.interface-4.4.0-py2.7-macosx-10.12-x86_64.egg/zope/interface/registry.py", line 442, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/pbauer/.cache/buildout/eggs/zope.interface-4.4.0-py2.7-macosx-10.12-x86_64.egg/zope/interface/adapter.py", line 598, in subscribers
    subscription(*objects)
  File "/Users/pbauer/.cache/buildout/eggs/plone.app.linkintegrity-3.3.2-py2.7.egg/plone/app/linkintegrity/handlers.py", line 111, in modifiedContent
    links = retriever.retrieveLinks()
  File "/Users/pbauer/.cache/buildout/eggs/plone.app.linkintegrity-3.3.2-py2.7.egg/plone/app/linkintegrity/retriever.py", line 36, in retrieveLinks
    value = accessor()
  File "/Users/pbauer/.cache/buildout/eggs/Products.Archetypes-1.14.2-py2.7.egg/Products/Archetypes/ClassGen.py", line 57, in generatedAccessor
    return schema[name].get(self, **kw)
  File "/Users/pbauer/.cache/buildout/eggs/Products.Archetypes-1.14.2-py2.7.egg/Products/Archetypes/Field.py", line 1561, in get
    encoding=kwargs.get('encoding', None))
  File "/Users/pbauer/.cache/buildout/eggs/Products.Archetypes-1.14.2-py2.7.egg/Products/Archetypes/BaseUnit.py", line 102, in transform
    filename=self.filename)
  File "/Users/pbauer/workspace/netstal/src-mrd/Products.PortalTransforms/Products/PortalTransforms/TransformEngine.py", line 171, in convertTo
    usedby=usedby, **kwargs)
  File "/Users/pbauer/workspace/netstal/src-mrd/Products.PortalTransforms/Products/PortalTransforms/chain.py", line 45, in convert
    data = transform.convert(orig, data, **kwargs)
  File "/Users/pbauer/workspace/netstal/src-mrd/Products.PortalTransforms/Products/PortalTransforms/Transform.py", line 196, in convert
    return self._v_transform.convert(*args, **kwargs)
  File "/Users/pbauer/workspace/netstal/src-mrd/Products.PortalTransforms/Products/PortalTransforms/transforms/safe_html.py", line 2390, in convert
    IFilterSchema, prefix="plone")
  File "/Users/pbauer/.cache/buildout/eggs/plone.registry-1.1.2-py2.7.egg/plone/registry/registry.py", line 82, in forInterface
    name
KeyError: 'Interface `Products.CMFPlone.interfaces.controlpanel.IFilterSchema` defines a field `valid_tags`, for which there is no record.'
```
The reason is that the registry settings needed for safe_html do not jet exists but are used when get the value of a textfield, in this case because linkintegrity-migration calls the tansform when retrieving links in html. 

My plan is to fix this by registering the new settings at a earlier stage if Products.PortalTransforms is >= 3.0.1.dev0.

**Comment by pbauer** [comment]
Does anyone know how to initialize regitry-setting in python without a egneric-setup?

I want do the same as the following, only in python:

```xml
<?xml version="1.0"?>
<registry>
  <records interface="Products.CMFPlone.interfaces.IFilterSchema"
           prefix="plone" />
</registry>
```

**Comment by pbauer** [comment]
I figured it out:

```python
from plone.registry.interfaces import IRegistry
from Products.CMFPlone.interfaces import IFilterSchema
from zope.component import getUtility

registry = getUtility(IRegistry)
registry.registerInterface(IFilterSchema, prefix='plone')
```

**Comment by hvelarde** [comment]
I just tried upgrading a site from Plone 5.0.4 to Plone 5.1.1 and stumble with this error.

**Comment by hvelarde** [comment]
seems the errors are logged just before the upgrade.
