### ISSUE TITLE
Jenkins 5.2 Python: failure on test teardown

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#2192]
The 5.2 Python job on Jenkins finally has [zero failures](http://jenkins.plone.org/job/plone-5.2-python-2.7/55/). But one of the test teardowns fails:

```
Running plone.app.testing.bbb.PloneTestCase:Functional tests:
  Tear down plone.app.relationfield.testing.plone.app.relationfield:Functional in 0.000 seconds.
  Tear down plone.app.relationfield.testing.PloneAppRelationfieldFixture in 0.004 seconds.
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes in 0.240 seconds.
  Tear down plone.app.event.testing.PAEventLayer in 0.003 seconds.
  Set up plone.app.testing.bbb.PloneTestCaseFixture in 1.163 seconds.
  Set up plone.app.testing.bbb.PloneTestCase:Functional in 0.000 seconds.
/home/jenkins/workspace/plone-5.2-python-2.7/src/Products.CMFCore/Products/CMFCore/DirectoryView.py:424: UserWarning: DirectoryView classic_ecmascript refers to a non-existing path 'plonetheme.classic:skins/classic_ecmascript'
  (self.id, reg_key), UserWarning)
Traceback (most recent call last):
  File "/home/jenkins/workspace/plone-5.2-python-2.7/bin/test", line 428, in <module>
    '--test-path', '/home/jenkins/.buildout/eggs/zope.globalrequest-1.4-py2.7.egg',
  File "/home/jenkins/.buildout/eggs/collective.xmltestreport-1.3.4-py2.7.egg/collective/xmltestreport/runner.py", line 60, in run
    failed = run_internal(defaults, args, script_parts=script_parts)
  File "/home/jenkins/.buildout/eggs/collective.xmltestreport-1.3.4-py2.7.egg/collective/xmltestreport/runner.py", line 73, in run_internal
    runner.run()
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 160, in run
    self.run_tests()
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 242, in run_tests
    self.skipped, self.import_errors)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 411, in run_layer
    import_errors)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 331, in run_tests
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 370, in run
    result.stopTest(self)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 839, in stopTest
    self.testTearDown()
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 764, in testTearDown
    layer.testTearDown()
  File "/home/jenkins/workspace/plone-5.2-python-2.7/src/plone.app.testing/plone/app/testing/layers.py", line 279, in testTearDown
    self.tearDownEnvironment(self['portal'])
  File "/home/jenkins/workspace/plone-5.2-python-2.7/src/plone.app.testing/plone/app/testing/layers.py", line 316, in tearDownEnvironment
    cache = queryUtility(IRAMCache)
  File "/home/jenkins/.buildout/eggs/zope.component-4.4.1-py2.7.egg/zope/component/_api.py", line 172, in queryUtility
    return getSiteManager(context).queryUtility(interface, name, default)
  File "/home/jenkins/.buildout/eggs/zope.interface-4.4.3-py2.7-linux-x86_64.egg/zope/interface/registry.py", line 281, in queryUtility
    return self.utilities.lookup((), provided, name, default)
AttributeError: 'PersistentAdapterRegistry' object has no attribute 'lookup'
#### Finished tests for group plone_app_testing ####
```

I guess it makes sense that a failure during teardown gives a broken build, even though all tests have passed.
I restarted the build to see if this is just a temporary problem, but it failed again.

It is a `plone.app.relationfield` test, but locally that passes fine. Maybe `bin/alltests` locally would fail too, but it takes long.
It is in the teardown of a `plone.app.testing.bbb.PloneTestCase:Functional` test, which probably should be converted to standard `plone.app.testing` at some point, but I can't say if that will fix it.
  Tear down

**Comment by pbauer** [comment]
I traced it back to `TestFactoryPloneSite`. When I transformed these tests from `PlonetestCase` to a proper TestCase in https://github.com/plone/Products.CMFPlone/commit/79e6d415d2484917e12dfd06416cffdd55e1fff7 the error disappeared. I hope jenkins thinks so too.

**Comment by pbauer** [comment]
My fix for this issue unearthed a bunch of tests that were not running before because of the error during teardown. We now run 5817 tests instead of 3534 in the plone-5.2-python-2.7 job. Ans since some of them fail we're now at 35 failing tests. But 2248 more tests are now passing.

Migrating a weirdly failing test away from `PloneTestCase` might be a viable option in some other cases as well.

**Comment by pbauer** [comment]
Oh, by the way. I found out about the faioing test by running `./bin/test --layer plone.app.testing.bbb.PloneTestCase` with a conditional pdb in queryUtility ands then inspecting the locals in the stacks above:

```python
    def queryUtility(self, provided, name=u'', default=None):
        if not getattr(self.utilities, 'lookup', None):
            import pdb; pdb.set_trace()
        return self.utilities.lookup((), provided, name, default)
```
