### ISSUE TITLE
Error messages from GS XML sanity check misleading (Plone 5.1)

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2303]
It seems that Plone 5.1 (or GenericSetup) performs a sanity check on the XML files of profiles of the installed add-ons. 

I received the following startup error (for configure.zcml) for an error in `profiles/default/metadata.xml`.

This is error message is misleading. It is correct that there is an error with the particular profile but GenericSetup should really report an invalid XML file with the full path of the related XML file

```
 line 735, in registerProfile
    metadata = ProfileMetadata(path, product=product)()
  File "/home/plone/sandboxes/dynamore.buildout.plone5/eggs/Products.GenericSetup-1.8.8-py2.7.egg/Products/GenericSetup/metadata.py", line 56, in __call__
    return self.parseXML( file.read() )
  File "/home/plone/sandboxes/dynamore.buildout.plone5/eggs/Products.GenericSetup-1.8.8-py2.7.egg/Products/GenericSetup/utils.py", line 176, in parseXML
    dom = parseString(xml)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
zope.configuration.config.ConfigurationExecutionError: <class 'xml.parsers.expat.ExpatError'>: mismatched tag: line 7, column 58
  in:
  File "/home/plone/sandboxes/dynamore.buildout.plone5/src/dynamore.policy/src/dynamore/policy/configure.zcml", line 22.2-29.8
    <genericsetup:registerProfile
        name="default"
        title="dynamore.policy"
        directory="profiles/default"
        description="Installs the dynamore.policy add-on."
        provides="Products.GenericSetup.interfaces.EXTENSION"
        post_handler=".setuphandlers.post_install"
        />
```

**Comment by mauritsvanrees** [comment]
This is in `Products.GenericSetup`. The error is caught and reraised as a `ConfigurationExecutionError` by [zope.configuration](https://github.com/zopefoundation/zope.configuration/blob/3.7.4/src/zope/configuration/config.py#L625-L633).
Looks easy enough to change GenericSetup so it passes the file name along. When I try it, the traceback becomes something like this:

```
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/5.1/./parts/instance/bin/interpreter", line 287, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.26-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.26-py2.7.egg/Zope2/App/startup.py", line 120, in startup
    load_zcml()
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.26-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.26-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/Users/maurits/shared-eggs/cp27m/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 651, in file
    context.execute_actions()
  File "/Users/maurits/shared-eggs/cp27m/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 626, in execute_actions
    callable(*args, **kw)
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.GenericSetup/Products/GenericSetup/registry.py", line 735, in registerProfile
    metadata = ProfileMetadata(path, product=product)()
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.GenericSetup/Products/GenericSetup/metadata.py", line 61, in __call__
    raise ExpatError('%s: %s' % (full_path, e))
zope.configuration.config.ConfigurationExecutionError: <class 'xml.parsers.expat.ExpatError'>: /Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.0.1-py2.7.egg/Products/CMFPlone/profiles/default/metadata.xml: unclosed token: line 4, column 0
  in:
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.0.1-py2.7.egg/Products/CMFPlone/profiles.zcml", line 6.2-13.8
    <genericsetup:registerProfile
        name="plone"
        title="Plone Site"
        directory="profiles/default"
        description="Profile for a default Plone."
        for="Products.CMFPlone.interfaces.IPloneSiteRoot"
        post_handler="Products.CMFPlone.setuphandlers.importFinalSteps"
        />
```

That still looks a bit confusing, but at least the path of the `metadata.xml` is in there.
Let me whip up a PR.
