### ISSUE TITLE
Creating a Plone 5.1-pending site programmatically:   Sorry, the requested resource does not exist. - jquery.highlightsearchterms.js  

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2317]
I have this browser view for creating a fresh Plone 5.1-pending site through a browser view
(intended usage is as a provisioning endpoint in plone.restapi):

https://github.com/zopyx/plone.restapi/blob/master/src/plone/restapi/services/provisioning/provisioning.py

```
2018-02-22 13:19:14 INFO Products.GenericSetup.tool Importing profile profile-Products.CMFPlone:plone with dependency strategy upgrade.
2018-02-22 13:19:14 INFO Products.GenericSetup.tool Applying main profile profile-Products.CMFPlone:plone
2018-02-22 13:19:14 INFO Products.GenericSetup.tool Profile upgrade versions purged.
2018-02-22 13:19:14 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:14 INFO GenericSetup.properties Site properties imported.
2018-02-22 13:19:14 INFO GenericSetup.toolset Toolset imported.
2018-02-22 13:19:14 INFO GenericSetup.componentregistry Adapters purged.
2018-02-22 13:19:14 INFO GenericSetup.componentregistry Subscribers purged.
2018-02-22 13:19:14 INFO GenericSetup.componentregistry Utilities purged.
2018-02-22 13:19:14 INFO GenericSetup.componentregistry Adapters registered.
2018-02-22 13:19:14 INFO GenericSetup.componentregistry Utilities registered.
2018-02-22 13:19:14 INFO GenericSetup.skins Skins tool imported.
2018-02-22 13:19:14 INFO GenericSetup.actions Actions tool imported.
2018-02-22 13:19:14 INFO GenericSetup.controlpanel Control panel imported.
2018-02-22 13:19:14 INFO GenericSetup.memberdata MemberData tool imported.
2018-02-22 13:19:14 INFO GenericSetup.contenttypes Content type registry imported.
2018-02-22 13:19:14 INFO GenericSetup.mailhost Mailhost imported.
2018-02-22 13:19:14 INFO GenericSetup.propertiestool Properties tool imported.
2018-02-22 13:19:14 INFO GenericSetup.plone.app.viewletmanager Imported.
2018-02-22 13:19:14 INFO GenericSetup.types Types tool imported.
2018-02-22 13:19:14 INFO GenericSetup.types 'Discussion Item' type info imported.
2018-02-22 13:19:14 INFO GenericSetup.types 'Plone Site' type info imported.
2018-02-22 13:19:14 INFO GenericSetup.types 'TempFolder' type info imported.
2018-02-22 13:19:14 INFO GenericSetup.plone.app.registry Cannot find registry
2018-02-22 13:19:14 INFO GenericSetup.bundles Cannot find registry
2018-02-22 13:19:14 INFO GenericSetup.repositorytool Nothing to import.
2018-02-22 13:19:14 INFO GenericSetup.catalog Catalog imported.
2018-02-22 13:19:14 INFO GenericSetup.workflow Workflow tool imported.
2018-02-22 13:19:14 INFO Products.GenericSetup.tool Importing profile profile-Products.CMFPlone:dependencies with dependency strategy upgrade.
2018-02-22 13:19:14 INFO Products.GenericSetup.tool Applying profile profile-Products.CMFFormController:CMFFormController
2018-02-22 13:19:14 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:14 INFO GenericSetup.toolset Toolset imported.
2018-02-22 13:19:14 INFO GenericSetup.plone.app.registry Cannot find registry
2018-02-22 13:19:14 INFO GenericSetup.bundles Cannot find registry
2018-02-22 13:19:14 INFO GenericSetup.repositorytool Nothing to import.
2018-02-22 13:19:14 INFO Products.GenericSetup.tool Applying profile profile-Products.MimetypesRegistry:MimetypesRegistry
2018-02-22 13:19:14 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:15 INFO GenericSetup.toolset Toolset imported.
2018-02-22 13:19:15 INFO GenericSetup.componentregistry Adapters registered.
2018-02-22 13:19:15 INFO GenericSetup.componentregistry Utilities registered.
2018-02-22 13:19:15 INFO GenericSetup.plone.app.registry Cannot find registry
2018-02-22 13:19:15 INFO GenericSetup.bundles Cannot find registry
2018-02-22 13:19:15 INFO GenericSetup.repositorytool Nothing to import.
2018-02-22 13:19:15 INFO Products.GenericSetup.tool Applying profile profile-Products.PortalTransforms:PortalTransforms
2018-02-22 13:19:15 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:15 INFO GenericSetup.toolset Toolset imported.
2018-02-22 13:19:15 INFO GenericSetup.componentregistry Adapters registered.
2018-02-22 13:19:15 INFO GenericSetup.componentregistry Utilities registered.
2018-02-22 13:19:15 INFO GenericSetup.plone.app.registry Cannot find registry
2018-02-22 13:19:15 INFO GenericSetup.bundles Cannot find registry
2018-02-22 13:19:15 INFO GenericSetup.repositorytool Nothing to import.
2018-02-22 13:19:15 INFO Products.GenericSetup.tool Applying profile profile-Products.CMFEditions:CMFEditions
2018-02-22 13:19:15 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:15 INFO GenericSetup.toolset Toolset imported.
2018-02-22 13:19:15 INFO GenericSetup.componentregistry Adapters registered.
2018-02-22 13:19:15 INFO GenericSetup.componentregistry Utilities registered.
2018-02-22 13:19:15 INFO GenericSetup.skins Skins tool imported.
2018-02-22 13:19:15 INFO GenericSetup.plone.app.registry Cannot find registry
2018-02-22 13:19:15 INFO GenericSetup.bundles Cannot find registry
2018-02-22 13:19:15 INFO GenericSetup. RepositoryTool settings imported.
2018-02-22 13:19:15 INFO GenericSetup.catalog Catalog imported.
2018-02-22 13:19:15 INFO Products.GenericSetup.tool Applying profile profile-Products.PlonePAS:PlonePAS
2018-02-22 13:19:15 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:15 INFO GenericSetup.plone.app.registry Cannot find registry
2018-02-22 13:19:15 INFO GenericSetup.bundles Cannot find registry
2018-02-22 13:19:15 INFO Products.GenericSetup.tool Applying profile profile-plone.app.z3cform:default
2018-02-22 13:19:15 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:15 INFO GenericSetup.browserlayer Browser layers imported
2018-02-22 13:19:15 INFO GenericSetup.plone.app.registry Cannot find registry
2018-02-22 13:19:15 INFO GenericSetup.bundles Cannot find registry
2018-02-22 13:19:15 INFO Products.GenericSetup.tool Applying profile profile-plone.app.registry:default
2018-02-22 13:19:15 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:15 INFO GenericSetup.toolset Toolset imported.
2018-02-22 13:19:15 INFO GenericSetup.componentregistry Adapters registered.
2018-02-22 13:19:15 INFO GenericSetup.componentregistry Utilities registered.
2018-02-22 13:19:16 INFO GenericSetup.controlpanel Control panel imported.
2018-02-22 13:19:16 INFO Products.GenericSetup.tool Applying profile profile-plone.app.discussion:default
2018-02-22 13:19:16 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:16 INFO GenericSetup.actions Actions tool imported.
2018-02-22 13:19:16 INFO GenericSetup.controlpanel Control panel imported.
2018-02-22 13:19:16 INFO GenericSetup.browserlayer Browser layers imported
2018-02-22 13:19:16 INFO GenericSetup.types Types tool imported.
2018-02-22 13:19:16 INFO GenericSetup.types 'Discussion Item' type info imported.
2018-02-22 13:19:16 INFO GenericSetup.resourceregistry Javascript registry imported.
2018-02-22 13:19:16 INFO GenericSetup.catalog Catalog imported.
2018-02-22 13:19:16 INFO GenericSetup.workflow Workflow tool imported.
2018-02-22 13:19:16 INFO Products.GenericSetup.tool Applying profile profile-plone.app.intid:default
2018-02-22 13:19:16 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:16 INFO Products.GenericSetup.tool Applying profile profile-plone.app.relationfield:default
2018-02-22 13:19:16 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:16 INFO Products.GenericSetup.tool Applying profile profile-plone.app.linkintegrity:default
2018-02-22 13:19:16 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:16 INFO Products.GenericSetup.tool Applying profile profile-plone.resource:default
2018-02-22 13:19:16 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:16 INFO GenericSetup.toolset Toolset imported.
2018-02-22 13:19:16 INFO GenericSetup.componentregistry Adapters registered.
2018-02-22 13:19:16 INFO GenericSetup.componentregistry Utilities registered.
2018-02-22 13:19:16 INFO Products.GenericSetup.tool Applying profile profile-plone.app.theming:default
2018-02-22 13:19:16 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:16 INFO GenericSetup.controlpanel Control panel imported.
2018-02-22 13:19:16 INFO GenericSetup.browserlayer Browser layers imported
2018-02-22 13:19:17 INFO Products.GenericSetup.tool Applying profile profile-plone.app.users:default
2018-02-22 13:19:17 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:17 INFO plone.app.users.setuphandlers Imported schema
2018-02-22 13:19:17 INFO Products.GenericSetup.tool Applying profile profile-plone.outputfilters:default
2018-02-22 13:19:17 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:17 INFO Products.GenericSetup.tool Applying profile profile-plone.app.querystring:default
2018-02-22 13:19:17 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:17 INFO Products.GenericSetup.tool Applying profile profile-plone.portlet.collection:default
2018-02-22 13:19:17 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:17 INFO GenericSetup.portlets Portlets imported
2018-02-22 13:19:17 INFO Products.GenericSetup.tool Applying profile profile-plone.portlet.static:default
2018-02-22 13:19:17 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:17 INFO GenericSetup.portlets Portlets imported
2018-02-22 13:19:17 INFO Products.GenericSetup.tool Applying profile profile-plone.keyring:default
2018-02-22 13:19:17 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:17 INFO GenericSetup.componentregistry Utilities registered.
2018-02-22 13:19:17 INFO Products.GenericSetup.tool Applying profile profile-plone.protect:default
2018-02-22 13:19:17 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:17 INFO Products.GenericSetup.tool Applying main profile profile-Products.CMFPlone:dependencies
2018-02-22 13:19:17 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:17 INFO GenericSetup.controlpanel Control panel imported.
2018-02-22 13:19:19 INFO GenericSetup.portlets Portlets imported
2018-02-22 13:19:19 INFO Products.GenericSetup.tool Importing profile profile-plone.app.contenttypes:plone-content with dependency strategy upgrade.
2018-02-22 13:19:19 INFO Products.GenericSetup.tool No upgrades available for profile profile-plone.app.z3cform:default. Profile stays at version (u'3',).
2018-02-22 13:19:19 INFO Products.GenericSetup.tool Applying profile profile-plone.app.dexterity:default
2018-02-22 13:19:19 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:19 INFO GenericSetup.controlpanel Control panel imported.
2018-02-22 13:19:19 INFO Products.GenericSetup.tool No upgrades available for profile profile-plone.app.registry:default. Profile stays at version (u'1', u'0a1').
2018-02-22 13:19:19 INFO Products.GenericSetup.tool Applying profile profile-plone.formwidget.recurrence:default
2018-02-22 13:19:19 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:19 INFO Products.GenericSetup.tool Applying profile profile-plone.app.event:default
2018-02-22 13:19:19 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:19 INFO GenericSetup.actions Actions tool imported.
2018-02-22 13:19:19 INFO GenericSetup.controlpanel Control panel imported.
2018-02-22 13:19:19 INFO GenericSetup.browserlayer Browser layers imported
2018-02-22 13:19:19 INFO GenericSetup.types Types tool imported.
2018-02-22 13:19:19 INFO GenericSetup.types 'Plone Site' type info imported.
2018-02-22 13:19:19 INFO GenericSetup.types 'Folder' type info imported.
2018-02-22 13:19:19 INFO GenericSetup.types 'Collection' type info imported.
2018-02-22 13:19:19 INFO Products.CMFPlone Cooking js ++resource++plone.app.discussion.javascripts/comments.js
2018-02-22 13:19:19 ERROR plone.subrequest Error handling subrequest to http://localhost:5080/plone/jquery.highlightsearchterms.js
Traceback (most recent call last):
  File "/home/ajung/sandboxes/plone-server-buildout-plone5/eggs/plone.subrequest-1.8.5-py2.7.egg/plone/subrequest/__init__.py", line 146, in subrequest
    traversed = request.traverse(path)
  File "/home/ajung/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/BaseRequest.py", line 525, in traverse
    return response.notFoundError(URL)
  File "/home/ajung/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/HTTPResponse.py", line 718, in notFoundError
    "<p><b>Resource:</b> %s</p>" % escape(entry))
NotFound:   <h2>Site Error</h2>
  <p>An error was encountered while publishing this resource.
  </p>
  <p><strong>Resource not found</strong></p>

  Sorry, the requested resource does not exist.<p>Check the URL and try again.</p><p><b>Resource:</b> http://localhost:5080/plone/jquery.highlightsearchterms.js</p>
  <hr noshade="noshade"/>

  <p>Troubleshooting Suggestions</p>

  <ul>
  <li>The URL may be incorrect.</li>
  <li>The parameters passed to this resource may be incorrect.</li>
  <li>A resource that this resource relies on may be
      encountering an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>
2018-02-22 13:19:19 WARNING Products.CMFPlone Could not find resource: jquery.highlightsearchterms.js
2018-02-22 13:19:19 INFO Products.CMFPlone Cooking css ++resource++plone.app.event/event.css
2018-02-22 13:19:19 INFO Products.CMFPlone Writing cooked resource: static/plone-legacy-compiled.js
2018-02-22 13:19:19 INFO Products.CMFPlone Writing cooked resource: static/plone-legacy-compiled.css
2018-02-22 13:19:20 INFO GenericSetup.resourceregistry Stylesheet registry imported.
2018-02-22 13:19:20 INFO plone.app.event.setuphandlers Old catalog DateIndex start deleted.
2018-02-22 13:19:20 INFO plone.app.event.setuphandlers Catalog DateRecurringIndex start created.
2018-02-22 13:19:20 INFO plone.app.event.setuphandlers Catalog metadata column start already exists.
2018-02-22 13:19:20 INFO plone.app.event.setuphandlers Old catalog DateIndex end deleted.
2018-02-22 13:19:20 INFO plone.app.event.setuphandlers Catalog DateRecurringIndex end created.
2018-02-22 13:19:20 INFO plone.app.event.setuphandlers Catalog metadata column end already exists.
2018-02-22 13:19:20 INFO plone.app.event.setuphandlers Catalog FieldIndex sync_uid created.
2018-02-22 13:19:20 INFO plone.app.event.setuphandlers Catalog metadata column sync_uid created.
2018-02-22 13:19:20 INFO Products.CMFPlone Cooking js ++resource++plone.app.discussion.javascripts/comments.js
2018-02-22 13:19:20 ERROR plone.subrequest Error handling subrequest to http://localhost:5080/plone/jquery.highlightsearchterms.js
Traceback (most recent call last):
  File "/home/ajung/sandboxes/plone-server-buildout-plone5/eggs/plone.subrequest-1.8.5-py2.7.egg/plone/subrequest/__init__.py", line 146, in subrequest
    traversed = request.traverse(path)
  File "/home/ajung/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/BaseRequest.py", line 525, in traverse
    return response.notFoundError(URL)
  File "/home/ajung/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/HTTPResponse.py", line 718, in notFoundError
    "<p><b>Resource:</b> %s</p>" % escape(entry))
NotFound:   <h2>Site Error</h2>
  <p>An error was encountered while publishing this resource.
  </p>
  <p><strong>Resource not found</strong></p>

  Sorry, the requested resource does not exist.<p>Check the URL and try again.</p><p><b>Resource:</b> http://localhost:5080/plone/jquery.highlightsearchterms.js</p>
  <hr noshade="noshade"/>

  <p>Troubleshooting Suggestions</p>

  <ul>
  <li>The URL may be incorrect.</li>
  <li>The parameters passed to this resource may be incorrect.</li>
  <li>A resource that this resource relies on may be
      encountering an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>
2018-02-22 13:19:20 WARNING Products.CMFPlone Could not find resource: jquery.highlightsearchterms.js
2018-02-22 13:19:20 INFO Products.CMFPlone Cooking css ++resource++plone.app.event/event.css
2018-02-22 13:19:20 INFO Products.CMFPlone Cooking js ++resource++plone.app.event/event.js
2018-02-22 13:19:20 INFO Products.CMFPlone Writing cooked resource: static/plone-legacy-compiled.js
2018-02-22 13:19:20 INFO Products.CMFPlone Writing cooked resource: static/plone-legacy-compiled.css
2018-02-22 13:19:20 INFO GenericSetup.resourceregistry Javascript registry imported.
2018-02-22 13:19:20 INFO GenericSetup.portlets Portlets imported
2018-02-22 13:19:20 INFO Products.GenericSetup.tool No upgrades available for profile profile-plone.app.querystring:default. Profile stays at version (u'13',).
2018-02-22 13:19:20 INFO Products.GenericSetup.tool No upgrades available for profile profile-plone.app.intid:default. Profile stays at version (u'1',).
2018-02-22 13:19:20 INFO Products.GenericSetup.tool No upgrades available for profile profile-plone.app.relationfield:default. Profile stays at version (u'1',).
2018-02-22 13:19:20 INFO Products.GenericSetup.tool Applying profile profile-plone.app.versioningbehavior:default
2018-02-22 13:19:20 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:20 INFO Products.GenericSetup.tool Applying profile profile-plone.app.contenttypes:default
2018-02-22 13:19:20 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:20 INFO GenericSetup. DiffTool settings imported.
2018-02-22 13:19:20 INFO GenericSetup. DiffTool settings imported.
2018-02-22 13:19:20 INFO GenericSetup.browserlayer Browser layers imported
2018-02-22 13:19:20 INFO GenericSetup.types Types tool imported.
2018-02-22 13:19:20 INFO GenericSetup.types 'Plone Site' type info imported.
2018-02-22 13:19:20 INFO GenericSetup.types 'Collection' type info imported.
2018-02-22 13:19:20 INFO GenericSetup.types 'Document' type info imported.
2018-02-22 13:19:20 INFO GenericSetup.types 'Folder' type info imported.
2018-02-22 13:19:20 INFO GenericSetup.types 'Link' type info imported.
2018-02-22 13:19:20 INFO GenericSetup.types 'File' type info imported.
2018-02-22 13:19:20 INFO GenericSetup.types 'Image' type info imported.
2018-02-22 13:19:20 INFO GenericSetup.types 'News Item' type info imported.
2018-02-22 13:19:20 INFO GenericSetup.types 'Event' type info imported.
2018-02-22 13:19:20 INFO Products.GenericSetup.tool Applying main profile profile-plone.app.contenttypes:plone-content
2018-02-22 13:19:20 INFO GenericSetup.rolemap Role / permission map imported.
2018-02-22 13:19:20 INFO GenericSetup.portlets Portlets imported

```

**Comment by cdw9** [comment]
related to #1811

**Comment by jensens** [comment]
but https://github.com/plone/Products.CMFPlone/blob/5.1.x/Products/CMFPlone/skins/plone_ecmascript/jquery.highlightsearchterms.js is still there.

**Comment by zopyx** [comment]
How to reproduce:

git clone git@github.com:zopyx/dynamore.policy.git
and run buildout

```
bin/zeo start
bin/instance fg
```

On different terminal start

```
python api.py
```

**Comment by zopyx** [comment]
I wonder why this fatal error is being swallowed and ignore by Plone. A proper error handling would raise an exception and abort the transaction all together.

**Comment by sunew** [comment]
fixed in https://github.com/plone/Products.CMFPlone/pull/2509
