### ISSUE TITLE
Using ZEO in Plone 5.1 fragile and unstable

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2353]
As part of a migration I have a Plone 5.1 instance with REST API up and running. At some point I decided to stop and restart the related app server because of some code changes in my policy package.
Plone refuses to start after the shutdown with

```
018-03-26 14:24:35 INFO ZEO.asyncio.base Connected Protocol(('127.0.0.1', 5200), '1', False)
Traceback (most recent call last):
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/parts/instance/bin/interpreter", line 307, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/startup.py", line 83, in startup
    DB = dbtab.getDatabase('/', is_root=1)
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/datatypes.py", line 287, in getDatabase
    db = factory.open(name, self.databases)
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/datatypes.py", line 185, in open
    DB = self.createDB(database_name, databases)
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/datatypes.py", line 182, in createDB
    return ZODBDatabase.open(self, databases)
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/ZODB-5.3.0-py2.7.egg/ZODB/config.py", line 131, in open
    storage = section.storage.open()
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/ZODB-5.3.0-py2.7.egg/ZODB/config.py", line 250, in open
    **options)
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/ZEO-5.1.1-py2.7.egg/ZEO/ClientStorage.py", line 279, in __init__
    self._wait()
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/ZEO-5.1.1-py2.7.egg/ZEO/asyncio/client.py", line 825, in wait
    self.wait_for_result(self.client.connected, timeout)
  File "/home/andreas.jung.extern/sandboxes/plone-server-buildout-plone5/eggs/ZEO-5.1.1-py2.7.egg/ZEO/asyncio/client.py", line 759, in wait_for_result
    raise ClientDisconnected("timed out waiting for connection")
ZEO.Exceptions.ClientDisconnected: timed out waiting for connection

```

There is only the message in the zeo.log:

```
2018-03-26T11:23:11 received handshake 'Z5'
2018-03-26T12:09:21 (:5200) disconnected
2018-03-26T12:12:37 Connected server protocol
2018-03-26T12:12:37 received handshake 'Z5'
2018-03-26T12:25:44 Connected server protocol
2018-03-26T12:25:44 (:5200) disconnected during locked transaction
2018-03-26T12:25:44 Connected server protocol
2018-03-26T12:25:44 (unconnected) disconnected
2018-03-26T12:25:44 (unconnected) disconnected
```

The ZEO server itself was still running and `bin/zeo status` reported `running`

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.

And probably solved. i never had ZEO issues.
