### ISSUE TITLE
WSGI does not start up with `No module named 'zc.buildout'` 

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#2374]
because zc.buildout was not importable. I worked around that by adding the path of zc.buildout to `bin/wsgi.py`.
For me that was:
`'/Users/pbauer/.cache/buildout/eggs/zc.buildout-2.11.2-py3.6.egg',`

Might be a broken setuptools/buildout combination.

**Comment by tomgross** [comment]
Most likely this is a buildout issue: https://github.com/buildout/buildout/issues/410

There is a workaround proposed there to use bootstrap-buildout.py (from https://bootstrap.pypa.io/bootstrap-buildout.py), which works for me.

**Comment by tomgross** [comment]
See also https://github.com/buildout/buildout/issues/434

**Comment by pbauer** [comment]
This is also the reason why https://jenkins.plone.org/view/PLIPs/job/plip-py3/ fails:

```
+ ./bin/instance run test.py
Traceback (most recent call last):
  File "./bin/instance", line 240, in <module>
    import plone.recipe.zope2instance.ctl
  File "/home/jenkins/workspace/plip-py3/src/plone.recipe.zope2instance/src/plone/recipe/zope2instance/__init__.py", line 17, in <module>
    from zc.recipe.egg.egg import Egg
  File "/home/jenkins/.buildout/eggs/zc.recipe.egg-2.0.5-py3.5.egg/zc/recipe/egg/__init__.py", line 1, in <module>
    from zc.recipe.egg.egg import Egg, Scripts, Eggs
  File "/home/jenkins/.buildout/eggs/zc.recipe.egg-2.0.5-py3.5.egg/zc/recipe/egg/egg.py", line 24, in <module>
    import zc.buildout.easy_install
ImportError: No module named 'zc.buildout'
```

The workaround does not work for me:

```
$ python3.6 -m venv .
$ ./bin/python bootstrap.py
[...]
Installing _mr.developer.
While:
  Installing _mr.developer.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/pbauer/.cache/buildout/eggs/zc.buildout-2.11.3-py3.6.egg/zc/buildout/buildout.py", line 2128, in main
    getattr(buildout, command)(args)
  File "/Users/pbauer/.cache/buildout/eggs/zc.buildout-2.11.3-py3.6.egg/zc/buildout/buildout.py", line 797, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/pbauer/.cache/buildout/eggs/zc.buildout-2.11.3-py3.6.egg/zc/buildout/buildout.py", line 1558, in _call
    return f()
  File "/Users/pbauer/.cache/buildout/eggs/zc.recipe.egg-2.0.5-py3.6.egg/zc/recipe/egg/egg.py", line 221, in install
    reqs, ws = self.working_set()
  File "/Users/pbauer/.cache/buildout/eggs/zc.recipe.egg-2.0.5-py3.6.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts,
  File "/Users/pbauer/.cache/buildout/eggs/zc.recipe.egg-2.0.5-py3.6.egg/zc/recipe/egg/egg.py", line 168, in _working_set
    return copy.deepcopy(cache_storage[cache_key])
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle zipimport.zipimporter objects
```
When I install buildout with pip and add the path to the `wsgi.py` script it works.

**Comment by tschorr** [comment]
As another you can copy the definition of `waitress_main` to the `bin/wsgi.py` script, so it looks like this after the `sys.path` definition:

```
from Zope2.Startup.run import make_wsgi_app
wsgiapp = make_wsgi_app({}, '/home/thomas/devel/plone/buildout.coredev/parts/wsgi.py/etc/zope.conf')
def application(*args, **kwargs):return wsgiapp(*args, **kwargs)
  
from paste.deploy.loadwsgi import APP
from paste.deploy.loadwsgi import ConfigLoader
from paste.deploy.loadwsgi import SERVER
  
def waitress_main(args=None):
      ini_filename = args[-1]
      config_loader = ConfigLoader(ini_filename)
      server_config = config_loader.get_context(SERVER)
      serve = server_config.create()
      app_config = config_loader.get_context(APP)
      zope_conf = app_config.local_conf['zope_conf']
      wsgiapp = make_wsgi_app(app_config.global_conf, zope_conf)
      serve(wsgiapp)
  
  
  if __name__ == '__main__':
      sys.exit(waitress_main(
          []
          + sys.argv[1:]))
```

Like this you get rid of the dependency on zc.recipe.egg which is otherwise unnecessary for all the startup scripts.

I wonder wether we should convince `p.r.zope2instance` to produce the above output or put wsgi.py (and maybe also `instance` script) generation somewhere else altogether.

**Comment by tschorr** [comment]
Note also that the instructions in https://github.com/plone/buildout.coredev/blob/5.2/py3.cfg#L34 on how to start Plone are wrong, because the `waitress.ini` command line argument is missing. https://github.com/plone/buildout.coredev/blob/5.2/py3.cfg#L63 though is correct.

**Comment by tomgross** [comment]
This seems OK now.
