### ISSUE TITLE
py3 tests aborts on some errors

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2459]
In some cases (I could not pinpoint when exactly but it happend a lot of time during the course of the py3 porting effort) the test-run aborts with this traceback. 

We're obviously in some cases passing a string instead of a exception. That case needs to be dealt with.

```
Traceback (most recent call last):
  File "/home/jenkins/.buildout/eggs/zope.configuration-4.1.0-py3.6.egg/zope/configuration/config.py", line 371, in execute_actions
    callable(*args, **kw)
  File "/home/jenkins/workspace/plip-py3/src/Products.GenericSetup/Products/GenericSetup/registry.py", line 437, in registerStep
    if already and already['version'] > version:
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py3.6.egg/zope/testrunner/runner.py", line 449, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py3.6.egg/zope/testrunner/runner.py", line 765, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py3.6.egg/zope/testrunner/runner.py", line 765, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py3.6.egg/zope/testrunner/runner.py", line 765, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py3.6.egg/zope/testrunner/runner.py", line 770, in setup_layer
    layer.setUp()
  File "/home/jenkins/workspace/plip-py3/src/plone.app.testing/src/plone/app/testing/layers.py", line 99, in setUp
    self.setUpZCML()
  File "/home/jenkins/workspace/plip-py3/src/plone.app.testing/src/plone/app/testing/layers.py", line 162, in setUpZCML
    loadAll('configure.zcml')
  File "/home/jenkins/workspace/plip-py3/src/plone.app.testing/src/plone/app/testing/layers.py", line 157, in loadAll
    xmlconfig.file(filename, package, context=context)
  File "/home/jenkins/.buildout/eggs/zope.configuration-4.1.0-py3.6.egg/zope/configuration/xmlconfig.py", line 500, in file
    context.execute_actions()
  File "/home/jenkins/.buildout/eggs/zope.configuration-4.1.0-py3.6.egg/zope/configuration/config.py", line 380, in execute_actions
    None, tb)
  File "/home/jenkins/.buildout/eggs/zope.configuration-4.1.0-py3.6.egg/zope/configuration/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/jenkins/.buildout/eggs/zope.configuration-4.1.0-py3.6.egg/zope/configuration/config.py", line 371, in execute_actions
    callable(*args, **kw)
  File "/home/jenkins/workspace/plip-py3/src/Products.GenericSetup/Products/GenericSetup/registry.py", line 437, in registerStep
    if already and already['version'] > version:
zope.configuration.config.ConfigurationExecutionError: <class 'TypeError'>: '>' not supported between instances of 'NoneType' and 'NoneType'
  in:
  File "/home/jenkins/workspace/plip-py3/src/Products.GenericSetup/Products/GenericSetup/configure.zcml", line 75.2-80.8
    <genericsetup:importStep
        name="toolset"
        title="Required Tools"
        description="Create required tools, replacing any of the wrong class, and remove forbidden ones."
        handler="Products.GenericSetup.tool.importToolset"
        />


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/test", line 401, in <module>
    '--test-path', '/home/jenkins/workspace/plip-py3/src/plone.app.robotframework/src',
  File "/home/jenkins/workspace/plip-py3/src/collective.xmltestreport/collective/xmltestreport/runner.py", line 60, in run
    failed = run_internal(defaults, args, script_parts=script_parts)
  File "/home/jenkins/workspace/plip-py3/src/collective.xmltestreport/collective/xmltestreport/runner.py", line 73, in run_internal
    runner.run()
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py3.6.egg/zope/testrunner/runner.py", line 189, in run
    self.run_tests()
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py3.6.egg/zope/testrunner/runner.py", line 291, in run_tests
    self.skipped, self.import_errors)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py3.6.egg/zope/testrunner/runner.py", line 454, in run_layer
    traceback.print_exc(file=f)
  File "/srv/python3.6/lib/python3.6/traceback.py", line 159, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py3.6.egg/zope/testrunner/tb_format.py", line 68, in print_exception
    file.writelines(format_exception(t, v, tb, limit))
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py3.6.egg/zope/testrunner/tb_format.py", line 57, in format_exception
    return fmt.formatException(t, v, tb)
  File "/home/jenkins/.buildout/eggs/zope.exceptions-4.2.0-py3.6.egg/zope/exceptions/exceptionformatter.py", line 198, in formatException
    exc_line = self.formatExceptionOnly(etype, value)
  File "/home/jenkins/.buildout/eggs/zope.exceptions-4.2.0-py3.6.egg/zope/exceptions/exceptionformatter.py", line 170, in formatExceptionOnly
    result = ''.join(traceback.format_exception_only(etype, value))
  File "/srv/python3.6/lib/python3.6/traceback.py", line 136, in format_exception_only
    return list(TracebackException(etype, value, None).format_exception_only())
  File "/srv/python3.6/lib/python3.6/traceback.py", line 465, in __init__
    if (exc_value and exc_value.__cause__ is not None
AttributeError: 'str' object has no attribute '__cause__'
```

**Comment by davisagli** [comment]
Fixed in https://github.com/zopefoundation/zope.testrunner/tree/fix-tb-format

**Comment by pbauer** [comment]
The branch was merged in https://github.com/zopefoundation/zope.testrunner/pull/74
