### ISSUE TITLE
test isolation problem between plone.z3cform and Products.CMFPlone

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#2581]
if tests run in combinations the following occurs:

```
File "/home/workspacejensens/cdev/plone5.2/src/plone.z3cform/src/plone/z3cform/layout.rst", line 186, in layout.rst
Failed example:
    print(view())  # doctest: +ELLIPSIS +NORMALIZE_WHITESPACE
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest layout.rst[61]>", line 1, in <module>
        print(view())  # doctest: +ELLIPSIS +NORMALIZE_WHITESPACE
      File "/home/workspacejensens/cdev/plone5.2/src/plone.z3cform/src/plone/z3cform/layout.py", line 65, in __call__
        self.update()
      File "/home/workspacejensens/cdev/plone5.2/src/plone.z3cform/src/plone/z3cform/layout.py", line 59, in update
        self.contents = self.form_instance.render()
      File "/home/workspacejensens/cdev/plone5.2/src/z3c.form/src/z3c/form/form.py", line 162, in render
        return template(self)
      File "/home/jensens/.buildout/shared-eggs/zope.browserpage-4.2.0-py3.6.egg/zope/browserpage/viewpagetemplatefile.py", line 49, in __call__
        sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
      File "/home/jensens/.buildout/shared-eggs/zope.pagetemplate-4.3.0-py3.6.egg/zope/pagetemplate/pagetemplate.py", line 134, in pt_render
        strictinsert=0, sourceAnnotations=sourceAnnotations
      File "/home/workspacejensens/cdev/plone5.2/src/Zope/src/Products/PageTemplates/engine.py", line 85, in __call__
        return self.template.render(**kwargs)
      File "/home/jensens/.buildout/shared-eggs/z3c.pt-3.1.0-py3.6.egg/z3c/pt/pagetemplate.py", line 158, in render
        return base_renderer(**context)
      File "/home/jensens/.buildout/shared-eggs/Chameleon-3.4-py3.6.egg/chameleon/zpt/template.py", line 297, in render
        return super(PageTemplate, self).render(**_kw)
      File "/home/jensens/.buildout/shared-eggs/Chameleon-3.4-py3.6.egg/chameleon/template.py", line 203, in render
        raise_with_traceback(exc, tb)
      File "/home/jensens/.buildout/shared-eggs/Chameleon-3.4-py3.6.egg/chameleon/utils.py", line 75, in raise_with_traceback
        raise exc
      File "/home/jensens/.buildout/shared-eggs/Chameleon-3.4-py3.6.egg/chameleon/template.py", line 183, in render
        self._render(stream, econtext, rcontext)
      File "67b2b9feb3f7d1bca3007655d29a1508.py", line 98, in render
    AttributeError: 'list' object has no attribute 'include'

     - Expression: "context/@@ploneform-macros/titlelessform"
     - Filename:   ... e.z3cform/src/plone/z3cform/pagetemplates/wrappedform.pt
     - Location:   (line 1: col 22)
     - Source:     ... e use-macro="context/@@ploneform-macros/titlelessform" />
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     - Arguments:  template: <ViewPageTemplateFile - at 0x7f0eeb2ca2b0>
                   options: {...} (0)
                   args: <tuple - at 0x7f0efa830048>
                   nothing: <NoneType - at 0x9dcd40>
                   modules: <TraversableModuleImporter - at 0x7f0ef1fcf860>
                   request: <TestRequest - at 0x7f0ee797ad18>
                   view: <MyLabelledForm None at 0x7f0ee717bba8>
                   context: <Bar - at 0x7f0ee6d49358>
                   views: <ViewMapper - at 0x7f0ee9fcfc88>
                   default: <object - at 0x7f0efa82b990>
                   repeat: {...} (0)
                   loop: {...} (0)
                   wrapped_repeat: {...} (0)
                   target_language: <NoneType - at 0x9dcd40>
                   translate: <function translate at 0x7f0ee7876c80>
                   macroname: titlelessform
```

to reproduce I was able to narrow this down to the following call::

```
./bin/test --layer plone.z3cform:Functional --layer  Products.CMFPlone.testing.CMFPloneLayer:Integration  -t plone.z3cform    -t Products.CMFPlone.controlpanel.tests.test_controlpanel_usergroups.TypesRegistryIntegrationTest
```

It can be resolved by skipping the test at:
https://github.com/plone/Products.CMFPlone/blob/442a7c0d100240ec6758cfb19217cc0175c26997/Products/CMFPlone/controlpanel/tests/test_controlpanel_usergroups.py#L27-L40

if the view is rendered, the problem occurs.

Needs deeper investigation.

**Comment by petschki** [comment]
skipping this test only resolves the issue with ``test_controlpanel_usergroups.py``. If you add another controlpanel test (regardless which one) the failure in `plone.z3cform` comes up again since all the controlpanel tests render the `plone.z3cform.layout` view ... I've investigated a little more into the problem and could narrow the AttributeError down to the stream object in `chameleon/template.py`. I've set the Chameleon rendering to DEBUG mode (with `chameleon_debug=1 ./bin/test ...`) and got those lines in the streamed file: (codesnipped)

```
...
 98:           # <Value u'context/@@ploneform-macros/titlelessform' (1:22)> -> __macro
 99:            __token = 22
100:           __macro = _static_4672423632(getitem('context'), econtext, True, ('@@ploneform-macros', 'titlelessform', ))
101:            __token = 22
102:            __m = __macro.include
103:            __m(__stream, econtext.copy(), rcontext, __i18n_domain)
...
```

so since `__macro` is a list instead of a `PageTemplate` object it seems to me, that are more than one macros named "titlelessform" on the context and therefore are returned as list? but this is a wild guess ...

**Comment by petschki** [comment]
@jensens  @pbauer I've fixe the failing tests but need advice if this fix is valid. Due to the fact, that `five.pt` is deprecated and the `<include package="five.pt" />` here https://github.com/zopefoundation/plone.z3cform/blob/test-cleanups/src/plone/z3cform/templates.zcml#L7 never gets valid, the page templates from plone.z3cform are somehow broken. If you add

```
  <configure zcml:condition="installed Products.PageTemplates">
      <include package="Products.PageTemplates" />
  </configure>
```

to `plone.z3cform.templates.zcml` everything works without failure.
If this include is valid, we can close this ticket ...

**Comment by petschki** [comment]
PS: I've added the lines in the open pull request here https://github.com/zopefoundation/plone.z3cform/pull/20 ... lets see what travis is saying

**Comment by jensens** [comment]
Yes, this makes sense to me. Looks like a very good catch!
