### ISSUE TITLE
[Python 3] UnicodeError caused by `wsgi.py adduser ...`

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2655]
Python 3.6, Plone 5.2a1: possibly a ZODB error

```
bin/wsgi.py adduser admin admin
Class Products.CMFCore.PortalContent.PortalContent has a security declaration for nonexistent method 'manage_FTPstat'
Class Products.CMFCore.PortalContent.PortalContent has a security declaration for nonexistent method 'manage_FTPlist'
Class Products.CMFCore.PortalContent.PortalContent has a security declaration for nonexistent method 'manage_FTPstat'
Class Products.CMFCore.PortalContent.PortalContent has a security declaration for nonexistent method 'manage_FTPlist'
Class Products.CMFFormController.ControllerPythonScript.ControllerPythonScript has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
Class Products.CMFFormController.ControllerValidator.ControllerValidator has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
loading index
Traceback (most recent call last):
  File "/home/ajung/.buildout/eggs/ZODB-5.5.1-py3.6.egg/ZODB/FileStorage/FileStorage.py", line 465, in _restore_index
    info = fsIndex.load(index_name)
  File "/home/ajung/.buildout/eggs/ZODB-5.5.1-py3.6.egg/ZODB/fsIndex.py", line 134, in load
    v = unpickler.load()
Unicode: 'ascii' codec can't decode byte 0x80 in position 257: ordinal not in range(128)

```

**Comment by ale-rt** [comment]
I cannot reproduce with current buildout.coredev:
```
[ale@emily buildout.coredev.alpine]$ ./bin/instance adduser nimda nimda
...
Created user: nimda
```
