### ISSUE TITLE
broken GopipIndex breaks upgrade from 5.0.9 to 5.2

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2728]
When upgrading a database created in Plone 5.0.9 to Plone 5.2 (coredev) the upgrade fails during `update_social_media_fields` for Plone 5.1b4. The reason is that `GopipIndex`was moved from `plone.app.folder`to `plone.folder` for Plone 5.2 but the old upgrade-step populates the vocabulary `SyndicatableFeedItems`.

```
(Pdb++) self.indexes[name]
<persistent broken plone.app.folder.nogopip.GopipIndex instance '\x00\x00\x00\x00\x00\x00\rg'>
```

Traceback

```
2019-02-06 16:38:19,912 ERROR [plone.app.upgrade:38][waitress] Upgrade aborted. Error:
Traceback (most recent call last):
  File "/Users/pbauer/workspace/coredev/src/Products.CMFPlone/Products/CMFPlone/MigrationTool.py", line 291, in upgrade
    step['step'].doStep(setup)
  File "/Users/pbauer/.cache/buildout/eggs/Products.GenericSetup-2.0b5-py2.7.egg/Products/GenericSetup/upgrade.py", line 168, in doStep
    self.handler(tool)
  File "/Users/pbauer/workspace/coredev/src/plone.app.upgrade/plone/app/upgrade/v51/betas.py", line 133, in update_social_media_fields
    loadMigrationProfile(context, 'profile-plone.app.upgrade.v51:to51beta4')
  File "/Users/pbauer/workspace/coredev/src/plone.app.upgrade/plone/app/upgrade/utils.py", line 203, in loadMigrationProfile
    context.runAllImportStepsFromProfile(profile, purge_old=False)
  File "/Users/pbauer/.cache/buildout/eggs/Products.GenericSetup-2.0b5-py2.7.egg/Products/GenericSetup/tool.py", line 391, in runAllImportStepsFromProfile
    dependency_strategy=dependency_strategy)
  File "/Users/pbauer/.cache/buildout/eggs/Products.GenericSetup-2.0b5-py2.7.egg/Products/GenericSetup/tool.py", line 1463, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/Users/pbauer/.cache/buildout/eggs/Products.GenericSetup-2.0b5-py2.7.egg/Products/GenericSetup/tool.py", line 1275, in _doRunImportStep
    return handler(context)
  File "/Users/pbauer/.cache/buildout/eggs/plone.app.registry-1.7.2-py2.7.egg/plone/app/registry/exportimport/handler.py", line 79, in importRegistry
    importer.importDocument(body)
  File "/Users/pbauer/.cache/buildout/eggs/plone.app.registry-1.7.2-py2.7.egg/plone/app/registry/exportimport/handler.py", line 127, in importDocument
    self.importRecords(node)
  File "/Users/pbauer/.cache/buildout/eggs/plone.app.registry-1.7.2-py2.7.egg/plone/app/registry/exportimport/handler.py", line 394, in importRecords
    prefix=prefix
  File "/Users/pbauer/.cache/buildout/eggs/plone.registry-1.1.5-py2.7.egg/plone/registry/registry.py", line 121, in registerInterface
    bound_field = persistent_field.bind(existing_record)
  File "/Users/pbauer/.cache/buildout/eggs/zope.schema-4.9.3-py2.7.egg/zope/schema/_field.py", line 806, in bind
    clone.value_type = clone.value_type.bind(context)
  File "/Users/pbauer/.cache/buildout/eggs/plone.registry-1.1.5-py2.7.egg/plone/registry/field.py", line 292, in bind
    clone._vocabulary = vr.get(object, self.vocabularyName)
  File "/Users/pbauer/.cache/buildout/eggs/Zope-4.0b8-py2.7.egg/Zope2/App/schema.py", line 32, in get
    return factory(context)
  File "/Users/pbauer/.cache/buildout/eggs/plone.app.vocabularies-4.0.7-py2.7.egg/plone/app/vocabularies/syndication.py", line 60, in __call__
    for brain in catalog(**query):
  File "/Users/pbauer/workspace/coredev/src/Products.CMFPlone/Products/CMFPlone/CatalogTool.py", line 457, in searchResults
    return ZCatalog.searchResults(self, query, **kw)
  File "/Users/pbauer/.cache/buildout/eggs/Products.ZCatalog-4.2-py2.7.egg/Products/ZCatalog/ZCatalog.py", line 612, in searchResults
    return self._catalog.searchResults(query, **kw)
  File "/Users/pbauer/.cache/buildout/eggs/Products.ZCatalog-4.2-py2.7.egg/Products/ZCatalog/Catalog.py", line 1091, in searchResults
    return self.search(query, sort_indexes, reverse, sort_limit, _merge)
  File "/Users/pbauer/.cache/buildout/eggs/Products.ZCatalog-4.2-py2.7.egg/Products/ZCatalog/Catalog.py", line 617, in search
    query = self.make_query(query)
  File "/Users/pbauer/.cache/buildout/eggs/Products.ZCatalog-4.2-py2.7.egg/Products/ZCatalog/Catalog.py", line 485, in make_query
    index = self.getIndex(iid)
  File "/Users/pbauer/.cache/buildout/eggs/Products.ZCatalog-4.2-py2.7.egg/Products/ZCatalog/Catalog.py", line 283, in getIndex
    return self.indexes[name].__of__(self)
AttributeError: 'GopipIndex' object has no attribute '__of__'
```

That could be fixed by adding a bbb to `plone.app.upgrade.__init__py` like this:

```python
try:
    from plone.app.folder.nogopip import GopipIndex
    GopipIndex  # pyflakes
except ImportError:
    from plone.folder.nogopip import GopipIndex
    alias_module('plone.app.folder.nogopip.GopipIndex', GopipIndex)
```

Or a we could remove the index during `update_social_media_fields`:

```python
try:
    from plone.app.folder.nogopip import GopipIndex
    GopipIndex  # pyflakes
except ImportError:
    # In Plone 5.2 there the GopipIndex moved. This makes sure that it is
    # migrated during a upgrade from 5.0 to 5.2
    from plone.app.upgrade.v52.alphas import migrate_gopipindex
    migrate_gopipindex(context)
```

**Comment by ale-rt** [comment]
The second option looks like a proper fix, the first one as a workaround.
The first one is more reliable (it will work also for third party projects that will try to import the GopipIndex).
Anyway I prefer the second because it is an actual cleanup.

**Comment by pbauer** [comment]
We had a fun poll at the Alpine City Sprint and the overwhelming mayority voted for option 1 because is can not be guaranteed that option 2 will cover all poossible cases. Without a lot of testing we cannot find out in which other upgrade-steps when migration from other versions this same issue would appear as well.
