### ISSUE TITLE
Flaky doctest for Python 3.6

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#2734]
I saw this test failing randomly on Python 3.6 (never in other Python versions):
```
Failed doctest test for layers.rst
  File "/home/jenkins/.buildout/eggs/cp36m/plone.app.testing-6.1.1-py3.6.egg/plone/app/testing/layers.rst", line 0

----------------------------------------------------------------------
File "/home/jenkins/.buildout/eggs/cp36m/plone.app.testing-6.1.1-py3.6.egg/plone/app/testing/layers.rst", line 377, in layers.rst
Failed example:
    conn = urlopen(portal_url + '/folder1', timeout=5) # doctest: +IGNORE_EXCEPTION_DETAIL
Expected:
    Traceback (most recent call last):
    ...
    urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
Got:
    Traceback (most recent call last):
      File "/srv/python3.6/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest layers.rst[105]>", line 1, in <module>
        conn = urlopen(portal_url + '/folder1', timeout=5) # doctest: +IGNORE_EXCEPTION_DETAIL
      File "/srv/python3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/srv/python3.6/lib/python3.6/urllib/request.py", line 526, in open
        response = self._open(req, data)
      File "/srv/python3.6/lib/python3.6/urllib/request.py", line 544, in _open
        '_open', req)
      File "/srv/python3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/srv/python3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
        return self.do_open(http.client.HTTPConnection, req)
      File "/srv/python3.6/lib/python3.6/urllib/request.py", line 1321, in do_open
        r = h.getresponse()
      File "/srv/python3.6/lib/python3.6/http/client.py", line 1331, in getresponse
        response.begin()
      File "/srv/python3.6/lib/python3.6/http/client.py", line 297, in begin
        version, status, reason = self._read_status()
      File "/srv/python3.6/lib/python3.6/http/client.py", line 258, in _read_status
        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
      File "/srv/python3.6/lib/python3.6/socket.py", line 586, in readinto
        return self._sock.recv_into(b)
    ConnectionResetError: [Errno 104] Connection reset by peer


  File "/srv/python3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/srv/python3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/srv/python3.6/lib/python3.6/doctest.py", line 2199, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
```

**Comment by ale-rt** [comment]
I made an experimental PR that uses requests instead of urlopen to see if tests get more reliable
