### ISSUE TITLE
Flaky doctest for plone/testing/zope.rst

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#2746]
Sometimes I see failing tests for plone.testing-7.0.0-py2.7.egg/plone/testing/zope.rst in jenkins builds:
```
Failed doctest test for zope.rst
  File "/home/jenkins/.buildout/eggs/cp27m/plone.testing-7.0.0-py2.7.egg/plone/testing/zope.rst", line 0

----------------------------------------------------------------------
File "/home/jenkins/.buildout/eggs/cp27m/plone.testing-7.0.0-py2.7.egg/plone/testing/zope.rst", line 526, in zope.rst
Failed example:
    conn = urlopen(app_url + '/folder1', timeout=5)
Expected:
    Traceback (most recent call last):
    ...
    URLError: <urlopen error [Errno ...] Connection refused>
Got:
    Traceback (most recent call last):
      File "/srv/python2.7/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zope.rst[137]>", line 1, in <module>
        conn = urlopen(app_url + '/folder1', timeout=5)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 429, in open
        response = self._open(req, data)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 447, in _open
        '_open', req)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 1228, in http_open
        return self.do_open(httplib.HTTPConnection, req)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 1201, in do_open
        r = h.getresponse(buffering=True)
      File "/srv/python2.7/lib/python2.7/httplib.py", line 1121, in getresponse
        response.begin()
      File "/srv/python2.7/lib/python2.7/httplib.py", line 438, in begin
        version, status, reason = self._read_status()
      File "/srv/python2.7/lib/python2.7/httplib.py", line 394, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/srv/python2.7/lib/python2.7/socket.py", line 480, in readline
        data = self._sock.recv(self._rbufsize)
    error: [Errno 104] Connection reset by peer


  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/srv/python2.7/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
```

Reminds me #2734. In that case the problem was (apparently) solved by using requests instead of urllib2.urlopen.

**Comment by mauritsvanrees** [comment]
Fixed with https://github.com/plone/plone.testing/pull/61 a few days ago.
