### ISSUE TITLE
KeyError: 'Interface `Products.CMFPlone.interfaces.controlpanel.INavigationSchema` defines a field `navigation_depth`, for which there is no record.'

### ISSUE THREAD

**Issue by d-maurer** [plone/Products.CMFPlone#2749]
"core.buildout" as of Feb 11 11:13; Python 3; newly created Plone portal.

```
2019-02-14 08:59:32,570 ERROR [portlets:33][waitress] Error while determining renderer availability of portlet ('context' '/Plone-IDP' 'navigation'): 'Interface `Products.CMFPlone.interfaces.controlpanel.INavigationSchema` defines a field `navigation_depth`, for which there is no record.'
Traceback (most recent call last):
  File "/home/dieter/plone/py3/plone-5.2/eggs/plone.portlets-2.3.1-py3.6.egg/plone/portlets/manager.py", line 119, in _lazyLoadPortlets
    isAvailable = renderer.available
  File "/home/dieter/plone/py3/plone-5.2/eggs/plone.app.portlets-4.4.1-py3.6.egg/plone/app/portlets/portlets/navigation.py", line 218, in available
    tree = self.getNavTree()
  File "/home/dieter/plone/py3/plone-5.2/eggs/plone.memoize-2.0.0-py3.6.egg/plone/memoize/instance.py", line 53, in memogetter
    val = func(*args, **kwargs)
  File "/home/dieter/plone/py3/plone-5.2/eggs/plone.app.portlets-4.4.1-py3.6.egg/plone/app/portlets/portlets/navigation.py", line 321, in getNavTree
    queryBuilder = getMultiAdapter((context, self.data), INavigationQueryBuilder)
  File "/home/dieter/plone/py3/plone-5.2/eggs/zope.component-4.5-py3.6.egg/zope/component/_api.py", line 95, in getMultiAdapter
    adapter = queryMultiAdapter(objects, interface, name, context=context)
  File "/home/dieter/plone/py3/plone-5.2/eggs/zope.component-4.5-py3.6.egg/zope/component/_api.py", line 108, in queryMultiAdapter
    return sitemanager.queryMultiAdapter(objects, interface, name, default)
  File "/home/dieter/plone/py3/plone-5.2/eggs/zope.interface-4.6.0-py3.6-linux-i686.egg/zope/interface/registry.py", line 359, in queryMultiAdapter
    objects, interface, name, default)
  File "/home/dieter/plone/py3/plone-5.2/eggs/zope.interface-4.6.0-py3.6-linux-i686.egg/zope/interface/adapter.py", line 552, in queryMultiAdapter
    result = factory(*objects)
  File "/home/dieter/plone/py3/plone-5.2/eggs/plone.app.portlets-4.4.1-py3.6.egg/plone/app/portlets/portlets/navigation.py", line 452, in __init__
    prefix="plone"
  File "/home/dieter/plone/py3/plone-5.2/eggs/plone.registry-1.1.5-py3.6.egg/plone/registry/registry.py", line 82, in forInterface
    name
KeyError: 'Interface `Products.CMFPlone.interfaces.controlpanel.INavigationSchema` defines a field `navigation_depth`, for which there is no record.'

### What I did:
Create a portal, visit its front page

### What I expect to happen:
No exceptions

### What actually happened:
KeyError: 'Interface `Products.CMFPlone.interfaces.controlpanel.INavigationSchema` defines a field `navigation_depth`, for which there is no record.'

### What version of Plone/ Addons I am using:
"core.buildout" as of Feb 11 11:13; addons not responsible

**Comment by d-maurer** [comment]
Apparently, code has changed since the creation of the Plone site object -- and various things are broken in my site. The problem is likely caused by this -- and therefore invalid.
