### ISSUE TITLE
Upgrade step (exclude_from_nav index) 5201 -> 5201 not working

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2767]
```
Starting the migration from version: 5201
Role / permission map imported.
Not creating required tool portal_css, because class Products.ResourceRegistries.tools.CSSRegistry.CSSRegistryTool is not found.
Not creating required tool portal_javascripts, because class Products.ResourceRegistries.tools.JSRegistry.JSRegistryTool is not found.
Toolset imported.
Actions tool imported.
Control panel imported.
RepositoryTool settings imported.
Removed record plone.resources/expect.url.
Removed record plone.resources/expect.js.
Removed record plone.resources/expect.css.
Removed record plone.resources/expect.init.
Removed record plone.resources/expect.deps.
Removed record plone.resources/expect.export.
Removed record plone.resources/expect.conf.
Removed record plone.resources/js-shortcuts.url.
Removed record plone.resources/js-shortcuts.js.
Removed record plone.resources/js-shortcuts.css.
Removed record plone.resources/js-shortcuts.init.
Removed record plone.resources/js-shortcuts.deps.
Removed record plone.resources/js-shortcuts.export.
Removed record plone.resources/js-shortcuts.conf.
Removed record plone.resources/marked.url.
Removed record plone.resources/marked.js.
Removed record plone.resources/marked.css.
Removed record plone.resources/marked.init.
Removed record plone.resources/marked.deps.
Removed record plone.resources/marked.export.
Removed record plone.resources/marked.conf.
Removed record plone.resources/rjs.url.
Removed record plone.resources/rjs.js.
Removed record plone.resources/rjs.css.
Removed record plone.resources/rjs.init.
Removed record plone.resources/rjs.deps.
Removed record plone.resources/rjs.export.
Removed record plone.resources/rjs.conf.
Removed record plone.resources/react.url.
Removed record plone.resources/react.js.
Removed record plone.resources/react.css.
Removed record plone.resources/react.init.
Removed record plone.resources/react.deps.
Removed record plone.resources/react.export.
Removed record plone.resources/react.conf.
Removed record plone.resources/JSXTransformer.url.
Removed record plone.resources/JSXTransformer.js.
Removed record plone.resources/JSXTransformer.css.
Removed record plone.resources/JSXTransformer.init.
Removed record plone.resources/JSXTransformer.deps.
Removed record plone.resources/JSXTransformer.export.
Removed record plone.resources/JSXTransformer.conf.
Removed record plone.resources/sinon.url.
Removed record plone.resources/sinon.js.
Removed record plone.resources/sinon.css.
Removed record plone.resources/sinon.init.
Removed record plone.resources/sinon.deps.
Removed record plone.resources/sinon.export.
Removed record plone.resources/sinon.conf.
Added BooleanIndex for field exclude_from_nav.
Indexing new indexes exclude_from_nav.
Upgrade aborted. Error:
Traceback (most recent call last):
  File "/home/dgho-test/onkopedia_buildout/eggs/Products.CMFPlone-5.2b1-py3.6.egg/Products/CMFPlone/MigrationTool.py", line 291, in upgrade
    step['step'].doStep(setup)
  File "/home/dgho-test/onkopedia_buildout/eggs/Products.GenericSetup-2.0b5-py3.6.egg/Products/GenericSetup/upgrade.py", line 168, in doStep
    self.handler(tool)
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.upgrade-2.0.21-py3.6.egg/plone/app/upgrade/v52/betas.py", line 102, in to52beta1
    remove_legacy_resource_registries(context)
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.upgrade-2.0.21-py3.6.egg/plone/app/upgrade/v52/betas.py", line 48, in remove_legacy_resource_registries
    portal.manage_delObjects(tools)
  File "/home/dgho-test/onkopedia_buildout/eggs/Products.CMFPlone-5.2b1-py3.6.egg/Products/CMFPlone/Portal.py", line 126, in manage_delObjects
    "Do not have permissions to remove this object")
AccessControl.unauthorized.Unauthorized: Do not have permissions to remove this object
End of upgrade path, main migration has finished.
The upgrade path did NOT reach current version.
Migration has failed
```

**Comment by zopyx** [comment]
```
> /home/dgho-test/onkopedia_buildout/eggs/Products.CMFPlone-5.2b1-py3.6.egg/Products/CMFPlone/Portal.py(126)manage_delObjects()
-> raise Unauthorized(
(Pdb) pp item
<persistent broken Products.ResourceRegistries.tools.CSSRegistry.CSSRegistryTool instance b'\x00\x00\x00\x00\x00\x1e\x9b4'>
```

**Comment by zopyx** [comment]
Removing portal_css+javascript manually through the ZMI also does not work

```

19-02-20 10:37:33,945 ERROR [plone.app.viewletmanager:118][waitress] Error while rendering viewlet-manager=plone.mainnavigation, viewlet=plone.global_sections
Traceback (most recent call last):
  File "/home/dgho-test/onkopedia_buildout/eggs/Zope-4.0b8-py3.6.egg/ZPublisher/WSGIPublisher.py", line 128, in transaction_pubevents
    yield
  File "/home/dgho-test/onkopedia_buildout/eggs/Zope-4.0b8-py3.6.egg/ZPublisher/WSGIPublisher.py", line 276, in publish_module
    response = _publish(request, new_mod_info)
  File "/home/dgho-test/onkopedia_buildout/eggs/Zope-4.0b8-py3.6.egg/ZPublisher/WSGIPublisher.py", line 210, in publish
    bind=1)
  File "/home/dgho-test/onkopedia_buildout/eggs/Zope-4.0b8-py3.6.egg/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/home/dgho-test/onkopedia_buildout/eggs/Zope-4.0b8-py3.6.egg/ZPublisher/WSGIPublisher.py", line 57, in call_object
    return obj(*args)
  File "/home/dgho-test/onkopedia_buildout/eggs/Products.CMFPlone-5.2b1-py3.6.egg/Products/CMFPlone/Portal.py", line 126, in manage_delObjects
    "Do not have permissions to remove this object")
AccessControl.unauthorized.Unauthorized: Do not have permissions to remove this object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dgho-test/onkopedia_buildout/eggs/Chameleon-3.5-py3.6.egg/chameleon/template.py", line 183, in render
    self._render(stream, econtext, rcontext)
  File "a487ef060361eaedebc337c5a5c2de97.py", line 240, in render
  File "/home/dgho-test/onkopedia_buildout/eggs/z3c.pt-3.1.0-py3.6.egg/z3c/pt/expressions.py", line 72, in render_content_provider
    return cp.render()
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 500, in render
    return self.build_tree(self.navtree_path)
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 492, in build_tree
    for item in self.navtree.get(path, []):
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.memoize-2.0.0-py3.6.egg/plone/memoize/view.py", line 48, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 412, in navtree
    generate_tabs = self.settings.generate_tabs
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.memoize-2.0.0-py3.6.egg/plone/memoize/view.py", line 48, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 392, in settings
    settings = registry.forInterface(INavigationSchema, prefix='plone')
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.registry-1.1.5-py3.6.egg/plone/registry/registry.py", line 82, in forInterface
    name
KeyError: 'Interface `Products.CMFPlone.interfaces.controlpanel.INavigationSchema` defines a field `navigation_depth`, for which there is no record.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.viewletmanager-3.0.0-py3.6.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/viewlets/common.py", line 64, in render
    return self.index()
  File "/home/dgho-test/onkopedia_buildout/eggs/Zope-4.0b8-py3.6.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.__func__(__self__, *args, **kw)
  File "/home/dgho-test/onkopedia_buildout/eggs/Zope-4.0b8-py3.6.egg/Products/Five/browser/pagetemplatefile.py", line 60, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/dgho-test/onkopedia_buildout/eggs/zope.pagetemplate-4.4.1-py3.6.egg/zope/pagetemplate/pagetemplate.py", line 135, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/dgho-test/onkopedia_buildout/eggs/Zope-4.0b8-py3.6.egg/Products/PageTemplates/engine.py", line 85, in __call__
    return self.template.render(**kwargs)
  File "/home/dgho-test/onkopedia_buildout/eggs/z3c.pt-3.1.0-py3.6.egg/z3c/pt/pagetemplate.py", line 158, in render
    return base_renderer(**context)
  File "/home/dgho-test/onkopedia_buildout/eggs/Chameleon-3.5-py3.6.egg/chameleon/zpt/template.py", line 305, in render
    return super(PageTemplate, self).render(**_kw)
  File "/home/dgho-test/onkopedia_buildout/eggs/Chameleon-3.5-py3.6.egg/chameleon/template.py", line 203, in render
    raise_with_traceback(exc, tb)
  File "/home/dgho-test/onkopedia_buildout/eggs/Chameleon-3.5-py3.6.egg/chameleon/utils.py", line 75, in raise_with_traceback
    raise exc
  File "/home/dgho-test/onkopedia_buildout/eggs/Chameleon-3.5-py3.6.egg/chameleon/template.py", line 183, in render
    self._render(stream, econtext, rcontext)
  File "a487ef060361eaedebc337c5a5c2de97.py", line 240, in render
  File "/home/dgho-test/onkopedia_buildout/eggs/z3c.pt-3.1.0-py3.6.egg/z3c/pt/expressions.py", line 72, in render_content_provider
    return cp.render()
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 500, in render
    return self.build_tree(self.navtree_path)
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 492, in build_tree
    for item in self.navtree.get(path, []):
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.memoize-2.0.0-py3.6.egg/plone/memoize/view.py", line 48, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 412, in navtree
    generate_tabs = self.settings.generate_tabs
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.memoize-2.0.0-py3.6.egg/plone/memoize/view.py", line 48, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 392, in settings
    settings = registry.forInterface(INavigationSchema, prefix='plone')
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.registry-1.1.5-py3.6.egg/plone/registry/registry.py", line 82, in forInterface
    name
KeyError: 'Interface `Products.CMFPlone.interfaces.controlpanel.INavigationSchema` defines a field `navigation_depth`, for which there is no record.'

 - Expression: "provider:plone.navtree"
 - Filename:   ... ut-3.1.0-py3.6.egg/plone/app/layout/viewlets/sections.pt
 - Location:   (line 24: col 42)
 - Source:     ... al:replace="structure provider:plone.navtree" />
                                         ^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  template: <ViewPageTemplateFile - at 0x7f71b4f76358>
               options: {...} (0)
               args: <tuple - at 0x7f71d26fe048>
               nothing: <NoneType - at 0x9d34e0>
               modules: <_SecureModuleImporter - at 0x7f71cb8b84a8>
               request: <WSGIRequest - at 0x7f71b49dd710>
               view: <GlobalSectionsViewlet plone.global_sections at 0x7f71bb57bbe0>
               context: <ImplicitAcquisitionWrapper onkopedia at 0x7f71bb462d80>
               views: <ViewMapper - at 0x7f71bb3e9438>
               here: <ImplicitAcquisitionWrapper onkopedia at 0x7f71bb462d80>
               container: <ImplicitAcquisitionWrapper onkopedia at 0x7f71bb462d80>
               root: <ImplicitAcquisitionWrapper  at 0x7f71bb4f68b8>
               traverse_subpath: <list - at 0x7f71b83d7788>
               user: <ImplicitAcquisitionWrapper - at 0x7f71bb4d9c18>
               default: <object - at 0x7f71d26f9aa0>
               repeat: {...} (0)
               loop: {...} (0)
               wrapped_repeat: <SafeMapping - at 0x7f71b4ee6b08>
               target_language: <NoneType - at 0x9d34e0>
               translate: <function translate at 0x7f71b4f80b70>
               portal_tabs: <list - at 0x7f71b4d07688>
               selected_tab: index_html
2019-02-20 10:37:34,900 ERROR [plone.app.viewletmanager:118][waitress] Error while rendering viewlet-manager=plone.mainnavigation, viewlet=plone.global_sections
Traceback (most recent call last):
  File "/home/dgho-test/onkopedia_buildout/eggs/Chameleon-3.5-py3.6.egg/chameleon/template.py", line 183, in render
    self._render(stream, econtext, rcontext)
  File "a487ef060361eaedebc337c5a5c2de97.py", line 240, in render
  File "/home/dgho-test/onkopedia_buildout/eggs/z3c.pt-3.1.0-py3.6.egg/z3c/pt/expressions.py", line 72, in render_content_provider
    return cp.render()
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 500, in render
    return self.build_tree(self.navtree_path)
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 492, in build_tree
    for item in self.navtree.get(path, []):
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.memoize-2.0.0-py3.6.egg/plone/memoize/view.py", line 48, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 412, in navtree
    generate_tabs = self.settings.generate_tabs
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.memoize-2.0.0-py3.6.egg/plone/memoize/view.py", line 48, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.app.layout-3.1.0-py3.6.egg/plone/app/layout/navigation/navtree.py", line 392, in settings
    settings = registry.forInterface(INavigationSchema, prefix='plone')
  File "/home/dgho-test/onkopedia_buildout/eggs/plone.registry-1.1.5-py3.6.egg/plone/registry/registry.py", line 82, in forInterface
    name
KeyError: 'Interface `Products.CMFPlone.interfaces.controlpanel.INavigationSchema` defines a field `navigation_depth`, for which there is no record.'

```

**Comment by petschki** [comment]
is this a duplicate of https://github.com/plone/Products.CMFPlone/issues/2755 ?

**Comment by zopyx** [comment]
Yes, it's a dupe.
