### ISSUE TITLE
verifydb fails with debug in some cases

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2792]
Using `./bin/instance verifydb -D` to check the `Data.fs` it fails in some cases:

```
Traceback (most recent call last):
  File "/Users/pbauer/.cache/buildout/eggs/Products.CMFPlone-5.2rc1-py3.7.egg/Products/CMFPlone/_scripts/verifydb.py", line 68, in verify_record
    class_info = unpickler.load()
  File "/Users/pbauer/.cache/buildout/eggs/ZODB-5.5.1-py3.7.egg/ZODB/_compat.py", line 62, in find_class
    return super(Unpickler, self).find_class(modulename, name)
ModuleNotFoundError: No module named 'Products.Archetypes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/instance", line 262, in <module>
    + sys.argv[1:]))
  File "/Users/pbauer/.cache/buildout/eggs/plone.recipe.zope2instance-6.1.3-py3.7.egg/plone/recipe/zope2instance/ctl.py", line 937, in main
    c.onecmd(' '.join(options.args))
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/pbauer/.cache/buildout/eggs/Products.CMFPlone-5.2rc1-py3.7.egg/Products/CMFPlone/_scripts/verifydb.py", line 31, in zopectl_entry
    verify_zodb(app, debug=options.debug)
  File "/Users/pbauer/.cache/buildout/eggs/Products.CMFPlone-5.2rc1-py3.7.egg/Products/CMFPlone/_scripts/verifydb.py", line 50, in verify_zodb
    success = verify_record(oid, data, debug)
  File "/Users/pbauer/.cache/buildout/eggs/Products.CMFPlone-5.2rc1-py3.7.egg/Products/CMFPlone/_scripts/verifydb.py", line 82, in verify_record
    pickletools.dis(pickle[pos:])
UnboundLocalError: local variable 'pos' referenced before assignment
```

**Comment by pbauer** [comment]
Another uncaught error when trying to unpickle:

```
INFO:zodbverify:Traceback (most recent call last):
  File "/Users/pbauer/.cache/buildout/eggs/Products.CMFPlone-5.2rc1-py3.7.egg/Products/CMFPlone/_scripts/verifydb.py", line 71, in verify_record
    unpickler.load()
  File "/Users/pbauer/.cache/buildout/eggs/ZODB-5.5.1-py3.7.egg/ZODB/_compat.py", line 62, in find_class
    return super(Unpickler, self).find_class(modulename, name)
ModuleNotFoundError: No module named 'plone.app.blob'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pbauer/.cache/buildout/eggs/Products.CMFPlone-5.2rc1-py3.7.egg/Products/CMFPlone/_scripts/verifydb.py", line 83, in verify_record
    pickletools.dis(pickle[pos:])
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pickletools.py", line 2453, in dis
    raise ValueError(errormsg)
ValueError: memo key 0 has never been stored into
```

**Comment by davisagli** [comment]
The 2nd errors in each of these cases are from pickletools.dis which is used to print out the disassembled pickle if it couldn't be loaded. I'm not sure if this is due to a bug in pickletools or a bad pickle, but it's just meant as a debugging aid. The real problem in both of these cases is that the pickle references a module that is no longer available.

It might make sense to just catch and ignore errors while disassembling the pickle.

**Comment by pbauer** [comment]
Ok, I'll change it to ignore these.
