### ISSUE TITLE
Fix redirection-tests that fail with Zope master

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2852]
https://github.com/plone/buildout.coredev/pull/582 tests the Zope master and six tests fail because the url in redicrections is handled differently. See https://jenkins.plone.org/job/pull-request-5.2-3.6/115/

This is probably related to the discussion in https://github.com/zopefoundation/Zope/issues/575. We should wait until that issue is resolved and then check if we need to adapt our tests.

Here is a example for the failing test:

```
Failure in test test_redirects_for_views_plus_params_plus_querystring_works (plone.rest.tests.test_redirects.TestRedirects)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/pbauer/.cache/buildout/eggs/plone.rest-1.4.0-py3.7.egg/plone/rest/tests/test_redirects.py", line 136, in test_redirects_for_views_plus_params_plus_querystring_works
    response.headers['Location'])
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: 'http://localhost:56258/plone/folder-new/@@some-view/param?k=v' != 'http://localhost:56258/plone/folder-new/%40%40some-view/param?k=v'
- http://localhost:56258/plone/folder-new/@@some-view/param?k=v
?                                         ^^
+ http://localhost:56258/plone/folder-new/%40%40some-view/param?k=v
?                                         ^^^^^^
```

**Comment by icemac** [comment]
This issue is adressed in zopefoundation/Zope#586.
@pbauer I am adding you as reviewer there.

**Comment by pbauer** [comment]
Fixed with https://github.com/zopefoundation/Zope/pull/586
