### ISSUE TITLE
Editing items very old-style DiscussionItem breaks

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2877]
After migration of DB to py3: Editing a old item with revisions that had a very old-style `DiscussionItem` breaks.

In my case the DB was migrated from 4.3 to 5.2 and then to Python 3.

`DiscussionItem` used to be in `Products.CMFDefault` which is gone since Plone 5.1. 

The issue is similar to https://github.com/plone/Products.CMFPlone/issues/2800 but in this case there is no valid replacement. 

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 142, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 295, in publish_module
  Module ZPublisher.WSGIPublisher, line 229, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module Products.PDBDebugMode.wsgi_runcall, line 60, in pdb_runcall
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.dexterity.browser.edit, line 58, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 22, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.edit, line 30, in handleApply
  Module z3c.form.group, line 126, in applyChanges
  Module zope.event, line 32, in notify
  Module zope.component.event, line 27, in dispatch
  Module zope.component._api, line 124, in subscribers
  Module zope.interface.registry, line 442, in subscribers
  Module zope.interface.adapter, line 607, in subscribers
  Module zope.component.event, line 36, in objectEventNotify
  Module zope.component._api, line 124, in subscribers
  Module zope.interface.registry, line 442, in subscribers
  Module zope.interface.adapter, line 607, in subscribers
  Module plone.app.versioningbehavior.subscribers, line 62, in create_version_on_save
  Module Products.CMFEditions.CopyModifyMergeRepositoryTool, line 336, in save
  Module Products.CMFEditions.CopyModifyMergeRepositoryTool, line 500, in _recursiveSave
  Module Products.CMFEditions.ArchivistTool, line 269, in prepare
  Module Products.CMFEditions.ArchivistTool, line 223, in _cloneByPickle
  Module ZODB.broken, line 331, in __reduce__
ZODB.broken.BrokenModified: <persistent broken Products.CMFDefault.DiscussionItem.DiscussionItemContainer instance b'\x00\x00\x00\x00\x00\x02O\x07'>
```

My workaround so far is to disable versioning for this item. We might still want to have a better fix that basically ignores the DiscussionItem. Maybe by adding a alias in `plone.app.upgrade`.

**Comment by fulv** [comment]
@pbauer I confirm that disabling versioning for an item does permit saving the item and the traceback no longer appears.  However, this would be required for every item.  Is there already a quick solution to disabling versioning for all items at once, or do I have to write my own?  I'm sure it's not hard to do, but just wondering if anyone has already done this.

**Comment by davisagli** [comment]
@tkimnguyen It looks like the problem here is not the mere existence of the broken DiscussionItemContainer, but the fact that creating a new revision tries to store a new copy of it.

If you don't care about the old comment data you could probably fix it with a script that visits each content item and deletes the `talkback` attribute of the object (if it has it)

**Comment by tkimnguyen** [comment]
@davisagli thanks, I would have thought that the upgrade would have included migration of those discussion items to plone.app.discussion. The buildout does not include Products.CMFDefault, so would you recommend I try this approach? https://github.com/plone/Products.CMFPlone/issues/800#issuecomment-319932671 

I don't think removing old comment data will fix the fact that new revisions are still trying to create a DiscussionItemContainer...

**Comment by davisagli** [comment]
@tkimnguyen There was an upgrade available to do that at some point. It sounds like it wasn't run on this site, or it was incomplete.

The approach you linked sounds like it is trying to solve a different but related problem (interfaces from CMFDefault in the local component registry). If you also have errors which indicate that problem, maybe it would help with them.

But your error is about trying to pickle a DiscussionItemContainer instance while trying to save a new revision. That is the object which is attached to content items as the `talkback` attribute. So I think deleting that attribute (from the current version of the object, not old versions) would mean it no longer needs to be copied.

**Comment by tkimnguyen** [comment]
Thanks @davisagli that worked!

**Comment by tkimnguyen** [comment]
As per discussion at https://community.plone.org/t/using-the-catalog-to-find-all-items-in-a-site/17573/9 the above query does not return all objects in the site and had to be tweaked to call getAllBrains().

Interestingly, when I went back to try it, I got this strange behaviour in which the attribute exists but cannot be deleted, so I just set it to `''` and that seems to do the trick:

```
# bin/client_reserved debug
>>> site=app.Site
>>> all_count=0
>>> deleted_talkback_count=0
>>> for brain in site.portal_catalog.getAllBrains():
...   all_count+=1
...   item=brain.getObject()
...   if hasattr(item, 'talkback'):
...     print('about to delete talkback attr for', item.absolute_url_path())
...     del item.talkback
...     print('deleted talkback attr for', item.absolute_url_path())
...     deleted_talkback_count+=1
...
('about to delete talkback attr for', '/Site/bla/page')
Traceback (most recent call last):
  File "<console>", line 6, in <module>
AttributeError: talkback
>>>
>>> item
<Document at /Site/blah/page>
>>> hasattr(item, 'talkback')
True
>>> item.talkback
<persistent broken Products.CMFDefault.DiscussionItem.DiscussionItemContainer instance '\x00\x00\x00\x00\x00\x03\x87P'>
>>> del item.talkback
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: talkback
>>> item.talkback
<persistent broken Products.CMFDefault.DiscussionItem.DiscussionItemContainer instance '\x00\x00\x00\x00\x00\x03\x87P'>
>>> item.talkback=''
>>> item.talkback
''
>>> import transaction
>>> transaction.commit()
>>> exit()
```

**Comment by davisagli** [comment]
@tkimnguyen That could happen if `talkback` was acquired. I would check `hasattr(aq_base(item), 'talkback')` rather than `hasattr(item, 'talkback')`

**Comment by jensens** [comment]
Closing as outdated (4 years old). Old DiscussionItem migration edge case from Plone 4.3. Workaround documented in comments. Not actionable in CMFPlone.
If you think this issue is still relevant please reopen it. Thank you for the original report!
