### ISSUE TITLE
Issue in a robot-test prevents updating version

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2888]
A issue with a robot-test in `test_datetime_widget.robot` in `plone.app.widgets` prevents us from upgrading to the newest version of robotframework in Plone 5.2 (https://github.com/plone/buildout.coredev/pull/591).

```
Failure in test As a contributor I can enter the date and time (test_datetime_widget.robot)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/pbauer/.cache/buildout/eggs/robotsuite-2.0.0-py3.7.egg/robotsuite/__init__.py", line 458, in runTest
    assert last_status == 'PASS', last_message
AssertionError: Variable '${xpath_day_list}' is string, not list or dictionary, and thus accessing item 'text()='${day}'' from it is not possible.
```

`xpath_day_list` is defined as follows:

```
${xpath_day_list}  //div[contains(concat(' ',normalize-space(@class),' '),'picker__day')][contains(concat(' ',normalize-space(@class),' '),'picker__day--infocus')]
```

Here is the test:

```
Fill date field
  [Arguments]  ${fieldlabel}  ${year}  ${month}  ${day}
  ${xpath_pattern} =  Convert to String  //div[label[text()[normalize-space(.)="${fieldlabel}"]]]
  ${month} =  Evaluate  str(int(${month}) - 1)

  Click Element  xpath=${xpath_pattern}${xpath_date_field}
  Select from list by value  xpath=${xpath_pattern}${xpath_month_select}  ${month}
  Select from list  xpath=${xpath_pattern}${xpath_year_select}  ${year}
  Click Element  xpath=${xpath_pattern}${xpath_day_list}[text()='${day}']
```

I'm clueless since contrary to popular belief I think robot-tests are not human-readable at all.

**Comment by ale-rt** [comment]
It is related to this issue:
https://github.com/robotframework/robotframework/issues/3004

Long story short when this happens escape the initial `[`

For example this patch seems to solve it:
```
index 96d44ef..93bac91 100644
--- a/plone/app/widgets/tests/robot/test_datetime_widget.robot
+++ b/plone/app/widgets/tests/robot/test_datetime_widget.robot
@@ -51,13 +51,13 @@ Fill date field
   Click Element  xpath=${xpath_pattern}${xpath_date_field}
   Select from list by value  xpath=${xpath_pattern}${xpath_month_select}  ${month}
   Select from list  xpath=${xpath_pattern}${xpath_year_select}  ${year}
-  Click Element  xpath=${xpath_pattern}${xpath_day_list}[text()='${day}']
+  Click Element  xpath=${xpath_pattern}${xpath_day_list}\[text()='${day}']
 
 Fill time field
   [Arguments]  ${fieldlabel}  ${time}
   ${xpath_pattern} =  Convert to String  //div[label[text()[normalize-space(.)="${fieldlabel}"]]]
   Click Element  xpath=${xpath_pattern}${xpath_time_field}
-  ${xpath_time} =  Convert to String  ${xpath_pattern}${xpath_time_list}[text()='${time}']
+  ${xpath_time} =  Convert to String  ${xpath_pattern}${xpath_time_list}\[text()='${time}']
   Wait until page contains Element  xpath=${xpath_time}
   Click Element  xpath=${xpath_time}
```

```
[ale@emily buildout.coredev.alpine]$ ZSERVER_HOST=localhost ZSERVER_PORT=55001 ./bin/pybot --variable BROWSER:chrome -t 'As a contributor I can enter the date and time' src/plone.app.widgets/plone/app/widgets/tests/robot/test_datetime_widget.robot
==============================================================================
Test Datetime Widget                                                          
==============================================================================
[ WARN ] Keyword 'Selenium2Library.Select From List' is deprecated. Use `Select From List By Label/Value/Index` instead.
As a contributor I can enter the date and time                        | PASS |
------------------------------------------------------------------------------
Test Datetime Widget                                                  | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  /home/ale/Code/plone/buildout.coredev.alpine/output.xml
Log:     /home/ale/Code/plone/buildout.coredev.alpine/log.html
Report:  /home/ale/Code/plone/buildout.coredev.alpine/report.html
```

**Comment by ale-rt** [comment]
I submitted a PR to plone.app.widgets to adapt the test to the new syntax:
- https://github.com/plone/plone.app.widgets/pull/198

**Comment by ale-rt** [comment]
Tests are passing for 5.2 in Python3.6:
https://github.com/plone/plone.app.widgets/pull/198

The other variants fail on robot tests for reasons I think are unrelated. I am anyway rerunning those jobs.
Once the above PR is merged this the branch in plone/buildout.coredev#591 should be updated and the test should pass.

**Comment by mauritsvanrees** [comment]
It seems that all relevant branches have been merged, so I close this.
Thanks!
