### ISSUE TITLE
Unable to install persistent==4.5.0 from Plone 5.2rc4-pending

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2900]
Upgrading my sandbox from 5.2RC3 to 5.2RC4-pending on a Debian 9 box with Python 3.7.3
throws this installation issue (however works on a different box).

```
Getting distribution for 'persistent==4.5.0'.
warning: no previously-included files found matching 'setup.pyc'
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
zip_safe flag not set; analyzing archive contents...
pycparser.ply.__pycache__.lex.cpython-37: module references __file__
pycparser.ply.__pycache__.lex.cpython-37: module MAY be using inspect.getsourcefile
pycparser.ply.__pycache__.yacc.cpython-37: module references __file__
pycparser.ply.__pycache__.yacc.cpython-37: module MAY be using inspect.getsourcefile
pycparser.ply.__pycache__.yacc.cpython-37: module MAY be using inspect.stack
pycparser.ply.__pycache__.ygen.cpython-37: module references __file__

Installed /tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/pycparser-2.19-py3.7.egg
Traceback (most recent call last):
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-v1hmvwte/persistent-4.5.0/setup.py", line 137, in <module>
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python-3.7.3/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/dist.py", line 444, in __init__
    k: v for k, v in attrs.items()
  File "/opt/python-3.7.3/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/dist.py", line 732, in finalize_options
    ep.load()(self, ep.name, value)
  File "/tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 217, in cffi_modules
  File "/tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
  File "/tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
  File "persistent/_ring_build.py", line 22, in <module>
  File "/tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/api.py", line 48, in __init__
ImportError: /tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/_cffi_backend.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 2316, in main
    **kw
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python-3.7.3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python-3.7.3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/python-3.7.3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/opt/python-3.7.3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/opt/python-3.7.3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-v1hmvwte/persistent-4.5.0/setup.py", line 137, in <module>
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python-3.7.3/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/dist.py", line 444, in __init__
    k: v for k, v in attrs.items()
  File "/opt/python-3.7.3/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/dist.py", line 732, in finalize_options
    ep.load()(self, ep.name, value)
  File "/tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 217, in cffi_modules
  File "/tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
  File "/tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
  File "persistent/_ring_build.py", line 22, in <module>
  File "/tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/api.py", line 48, in __init__
ImportError: /tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/_cffi_backend.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object
An error occurred when trying to install /tmp/tmp2v88xyakget_dist/persistent-4.5.0.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing.
  Getting section instance.
  Initializing section instance.
  Getting option instance:zeo-address.
  Getting section zeo.
  Initializing section zeo.
  Installing recipe plone.recipe.zeoserver.
  Getting distribution for 'persistent==4.5.0'.
```

Never seen this error before:

```
ImportError: /tmp/easy_install-v1hmvwte/persistent-4.5.0/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/_cffi_backend.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object
```

**Comment by zopyx** [comment]
Installation of   `persistent=4.4.3` using pip works, 4.5.0 with pip fails.

**Comment by zopyx** [comment]
Perhaps more related to the persistent module itself and its latest release but an issue for Plone..will bring this to the persistent tracker

**Comment by zopyx** [comment]
Issue with /tmp mounted with noexec option:

https://github.com/zopefoundation/persistent/issues/114

**Comment by vincentfretin** [comment]
Related to #3083 and https://github.com/zopefoundation/Zope/issues/856 apparently. I'm closing the issue here as duplicate. 
zopefoundation/persistent#114 is still open.
