### ISSUE TITLE
file with umlauts

### ISSUE THREAD

**Issue by iham** [plone/Products.CMFPlone#2907]
### What I did:

- create vanilla instance;
- add a file content object with a image that has umlauts in its name (not the title! the actual image binary file name)
- click the link to initialise a download of that binary

### What I expect to happen:
download the file without console errors

### What actually happened:
download is fine; downloaded file too, but console says:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/Users/plone/eggs/ZConfig-3.4.0-py2.7.egg/ZConfig/components/logger/formatter.py", line 342, in format
    s = self.formatMessage(record)
  File "/Users/plone/eggs/ZConfig-3.4.0-py2.7.egg/ZConfig/components/logger/formatter.py", line 323, in formatMessage
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 145: ordinal not in range(128)
Logged from file AccessLogger.py, line 34
```

### What version of Plone/ Addons I am using:

vanilla Plone5.2rc4; python2.7.x;

**Comment by zopyx** [comment]
Works with Python 3.x

**Comment by jensens** [comment]
work in 5.2.10 and 6.0.2
