### ISSUE TITLE
ZEO cache AssertionError caused or causing by Plone 5.1.5

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2929]
Out of the sudden (like always) I see this error (caused by login) into a Plone 5.1.5 site.

ZODB 3.11.0
ZODB 5.3.0

```2019-08-01T14:22:24 ERROR plone.app.textfield Transform exception
Traceback (most recent call last):
  File "/home/production/instances/lsoptsupport.com/eggs/plone.app.textfield-1.2.11-py2.7.egg/plone/app/textfield/transform.py", line 46, in __call__
    encoding=value.encoding)
  File "/home/production/instances/lsoptsupport.com/eggs/Products.PortalTransforms-3.1.5-py2.7.egg/Products/PortalTransforms/TransformEngine.py", line 173, in convertTo
    usedby=usedby, **kwargs)
  File "/home/production/instances/lsoptsupport.com/eggs/Products.PortalTransforms-3.1.5-py2.7.egg/Products/PortalTransforms/chain.py", line 49, in convert
    data = transform.convert(orig, data, **kwargs)
  File "/home/production/instances/lsoptsupport.com/eggs/Products.PortalTransforms-3.1.5-py2.7.egg/Products/PortalTransforms/Transform.py", line 202, in convert
    return self._v_transform.convert(*args, **kwargs)
  File "/home/production/instances/lsoptsupport.com/eggs/plone.outputfilters-3.0.5-py2.7.egg/plone/outputfilters/transforms/html_to_plone_outputfilters_html.py", line 33, in convert
    res = apply_filters(filters, orig)
  File "/home/production/instances/lsoptsupport.com/eggs/plone.outputfilters-3.0.5-py2.7.egg/plone/outputfilters/__init__.py", line 7, in apply_filters
    res = filter(data)
  File "/home/production/instances/lsoptsupport.com/eggs/plone.outputfilters-3.0.5-py2.7.egg/plone/outputfilters/filters/resolveuid_and_caption.py", line 119, in __call__
    self.feed(data)
  File "/usr/lib/python2.7/sgmllib.py", line 104, in feed
    self.goahead(0)
  File "/usr/lib/python2.7/sgmllib.py", line 138, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib/python2.7/sgmllib.py", line 296, in parse_starttag
    self.finish_starttag(tag, attrs)
  File "/usr/lib/python2.7/sgmllib.py", line 338, in finish_starttag
    self.unknown_starttag(tag, attrs)
  File "/home/production/instances/lsoptsupport.com/eggs/plone.outputfilters-3.0.5-py2.7.egg/plone/outputfilters/filters/resolveuid_and_caption.py", line 365, in unknown_starttag
    image, fullimage, src, description = self.resolve_image(src)
  File "/home/production/instances/lsoptsupport.com/eggs/plone.outputfilters-3.0.5-py2.7.egg/plone/outputfilters/filters/resolveuid_and_caption.py", line 237, in resolve_image
    image = traverse_path(fullimage, subpath)
  File "/home/production/instances/lsoptsupport.com/eggs/plone.outputfilters-3.0.5-py2.7.egg/plone/outputfilters/filters/resolveuid_and_caption.py", line 228, in traverse_path
    stack = traversal_stack(base, path)
  File "/home/production/instances/lsoptsupport.com/eggs/plone.outputfilters-3.0.5-py2.7.egg/plone/outputfilters/filters/resolveuid_and_caption.py", line 208, in traversal_stack
    child = obj.scale(child_id, components.pop())
  File "/home/production/instances/lsoptsupport.com/eggs/plone.namedfile-4.2.6-py2.7.egg/plone/namedfile/scaling.py", line 434, in scale
    **parameters
  File "/home/production/instances/lsoptsupport.com/eggs/plone.scale-3.0.3-py2.7.egg/plone/scale/storage.py", line 178, in scale
    info = self.get_info_by_hash(key)
  File "/home/production/instances/lsoptsupport.com/eggs/plone.scale-3.0.3-py2.7.egg/plone/scale/storage.py", line 171, in get_info_by_hash
    for value in self.storage.values():
  File "/home/production/instances/lsoptsupport.com/eggs/ZODB-5.3.0-py2.7.egg/ZODB/Connection.py", line 796, in setstate
    p, serial = self._storage.load(oid)
  File "/home/production/instances/lsoptsupport.com/eggs/ZODB-5.3.0-py2.7.egg/ZODB/mvccadapter.py", line 143, in load
    r = self._storage.loadBefore(oid, self._start)
  File "/home/production/instances/lsoptsupport.com/eggs/ZEO-5.1.1-py2.7.egg/ZEO/ClientStorage.py", line 518, in loadBefore
    result = self._cache.loadBefore(oid, tid)
  File "/home/production/instances/lsoptsupport.com/eggs/ZEO-5.1.1-py2.7.egg/ZEO/cache.py", line 546, in loadBefore
    result = self.load(oid, before_tid)
  File "/home/production/instances/lsoptsupport.com/eggs/ZEO-5.1.1-py2.7.egg/ZEO/cache.py", line 495, in load
    assert status == b'a', (ofs, self.f.tell(), oid)
AssertionError: (38911201, 38911202, '\x00\x00\x00\x00\x006\xf0\x0b')
```

**Comment by davisagli** [comment]
@zopyx Is this still an issue? It seems the ZEO cache somehow has a corrupted index, but I have no idea how to reproduce it.
