### ISSUE TITLE
KeyError: 'plone.resources.development' for Products.ResourceRegistries 3.0.1 with Plone 5.0a3

### ISSUE THREAD

**Issue by kaerumy** [plone/Products.CMFPlone#296]
After upgrading from 5.0a2, I get this error and traceback.

```
2014-11-06 19:17:59 ERROR plone.app.viewletmanager rendering of plone.scripts in plone.resourceregistries.scripts fails: 'plone.resources.development'

 - Expression: "view/scripts"
 - Filename:   ... py2.7.egg/Products/CMFPlone/resources/browser/scripts.pt
 - Location:   (1:28)
 - Source:     ... tal:scripts repeat="script view/scripts"
                                              ^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7f4db5c7dc10>
               views: <ViewMapper - at 0x7f4dafd8d610>
               modules: <instance - at 0x7f4dbc049a28>
               args: <tuple - at 0x7f4dc37bc050>
               here: <ImplicitAcquisitionWrapper kaerumy at 0x7f4db71638c0>
               user: <SpecialUser - at 0x7f4dbd8e7b50>
               nothing: <NoneType - at 0x920190>
               container: <ImplicitAcquisitionWrapper kaerumy at 0x7f4db71638c0>
               request: <instance - at 0x7f4dafd527e8>
               wrapped_repeat: <SafeMapping - at 0x7f4db406ed08>
               traverse_subpath: <list - at 0x7f4dafca6bd8>
               default: <object - at 0x7f4dc36d54e0>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper kaerumy at 0x7f4db71638c0>
               view: <SimpleViewletClass from /home/kaeru/kaeru.my/eggs/Products.CMFPlone-5.0a3-py2.7.egg/Products/CMFPlone/resources/browser/scripts.pt plone.resourceregistries.scripts at 0x7f4db40709d0>
               translate: <function translate at 0x7f4daff7aa28>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f4db71633c0>
               options: {...} (0)
               target_language: <NoneType - at 0x920190>
Traceback (most recent call last):
  File "/home/kaeru/kaeru.my/eggs/plone.app.viewletmanager-2.0.6-py2.7.egg/plone/app/viewletmanager/manager.py", line 105, in render
    html.append(viewlet.render())
  File "/home/kaeru/kaeru.my/eggs/plone.app.layout-2.5.3-py2.7.egg/plone/app/layout/viewlets/common.py", line 57, in render
    return self.index()
  File "/home/kaeru/kaeru.my/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/kaeru/kaeru.my/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/kaeru/kaeru.my/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/kaeru/kaeru.my/eggs/five.pt-2.2.2-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/kaeru/kaeru.my/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/kaeru/kaeru.my/eggs/Chameleon-2.11-py2.7.egg/chameleon/zpt/template.py", line 257, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/kaeru/kaeru.my/eggs/Chameleon-2.11-py2.7.egg/chameleon/template.py", line 190, in render
    raise_with_traceback(exc, tb)
  File "/home/kaeru/kaeru.my/eggs/Chameleon-2.11-py2.7.egg/chameleon/template.py", line 172, in render
    self._render(stream, econtext, rcontext)
  File "55e00ab2f431264997d2c5e2a80ce338c09e30ad.py", line 88, in render
  File "/home/kaeru/kaeru.my/eggs/five.pt-2.2.2-py2.7.egg/five/pt/expressions.py", line 161, in __call__
    return base()
  File "/home/kaeru/kaeru.my/eggs/Products.CMFPlone-5.0a3-py2.7.egg/Products/CMFPlone/resources/browser/scripts.py", line 63, in scripts
    if self.development:
  File "/home/kaeru/kaeru.my/eggs/Products.CMFPlone-5.0a3-py2.7.egg/Products/CMFPlone/resources/browser/resource.py", line 25, in development
    return self.registry.records['plone.resources.development'].value
  File "/home/kaeru/kaeru.my/eggs/plone.registry-1.0.2-py2.7.egg/plone/registry/registry.py", line 186, in __getitem__
    field = self._getField(name)
  File "/home/kaeru/kaeru.my/eggs/plone.registry-1.0.2-py2.7.egg/plone/registry/registry.py", line 243, in _getField
    field = self._fields[name]
KeyError: 'plone.resources.development'

```

**Comment by vangheem** [comment]
I've tested this in latest to be fix.
