### ISSUE TITLE
UnicodeDecodeError  plone-overview.pt after zodbupdate migration to Plone 5.2

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2983]
The default sites overview page fails under Plone 5.2 after an in-place migration from Plone 5.1.5.

``` 
2019-11-19 10:24:29,235 ERROR   [ZODB.Connection:809][waitress] Couldn't load state for OFS.Image.Image 0x0c
Traceback (most recent call last):
  File "/home/ajung/sandboxes/dynamore-plone-5.2-upgrade/eggs/ZODB-5.5.1-py3.7.egg/ZODB/Connection.py", line 795, in setstate
    self._reader.setGhostState(obj, p)
  File "/home/ajung/sandboxes/dynamore-plone-5.2-upgrade/eggs/ZODB-5.5.1-py3.7.egg/ZODB/serialize.py", line 633, in setGhostState
    state = self.getState(pickle)
  File "/home/ajung/sandboxes/dynamore-plone-5.2-upgrade/eggs/ZODB-5.5.1-py3.7.egg/ZODB/serialize.py", line 626, in getState
    return unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 34: ordinal not in range(128)
2019-11-19 10:24:29,244 ERROR   [Zope.SiteErrorLog:251][waitress] 1574155469.24186440.8863765109086195 http://dev2.zopyx.de:5080/index_html
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module zope.browserpage.simpleviewclass, line 41, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 88, in __call__
  Module z3c.pt.pagetemplate, line 173, in render
  Module chameleon.zpt.template, line 306, in render
  Module chameleon.template, line 209, in render
  Module chameleon.utils, line 75, in raise_with_traceback
  Module chameleon.template, line 187, in render
  Module b5a2936258ee7ef12ef892d1f5463aa6, line 241, in render
  Module Products.PageTemplates.expression, line 101, in __call__
  Module Products.CMFPlone.browser.admin, line 60, in sites
  Module ZODB.Connection, line 795, in setstate
  Module ZODB.serialize, line 633, in setGhostState
  Module ZODB.serialize, line 626, in getState
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 34: ordinal not in range(128)

 - Stream:     ...  hh�   �6
  ...
                                                 ^
 - Expression: "view/sites"
 - Filename:   ... gg/Products/CMFPlone/browser/templates/plone-overview.pt
 - Location:   (line 21: col 24)
 - Source:     <body tal:define="sites view/sites">
                                       ^^^^^^^^^^
 - Arguments:  template: <ViewPageTemplateFile - at 0x7f06a462d390>
               options: {...} (0)
               args: <tuple - at 0x7f06b70a0050>
               nothing: <NoneType - at 0x855ec0>
               modules: <_SecureModuleImporter - at 0x7f06b3774bd0>
               request: <WSGIRequest - at 0x7f06a458c8d0>
               view: <SimpleViewClass from /home/ajung/sandboxes/dynamore-plone-5.2-upgrade/eggs/Products.CMFPlone-5.2.0-py3.7.egg/Products/CMFPlone/browser/templates/plone-overview.pt plone-overview at 0x7f06a458ced0>
               context: <ImplicitAcquisitionWrapper  at 0x7f06ada4c3c0>
               views: <ViewMapper - at 0x7f06a458b1d0>
               here: <ImplicitAcquisitionWrapper  at 0x7f06ada4c3c0>
               container: <ImplicitAcquisitionWrapper  at 0x7f06ada4c3c0>
               root: <ImplicitAcquisitionWrapper  at 0x7f06ada4c3c0>
               traverse_subpath: <list - at 0x7f06ad9d4500>
               user: <ImplicitAcquisitionWrapper - at 0x7f06ad9d4b40>
               default: <object - at 0x7f06b5a7af40>
               repeat: {...} (0)
               loop: {...} (0)
               wrapped_repeat: <SafeMapping - at 0x7f06ad9ddf50>
               target_language: <NoneType - at 0x855ec0>
               translate: <function translate at 0x7f06ad175440>

```

**Comment by parruc** [comment]
I'm having the exact same error. Were you able to solve it in the end? Thanks

**Comment by jensens** [comment]
Closing as outdated (3 years old). About UnicodeDecodeError after zodbupdate Plone 5.1 to 5.2 migration. This Py2-to-Py3 migration path is no longer relevant.
If you think this issue is still relevant please reopen it. Thank you for the original report!
