### ISSUE TITLE
subrequest with VirtualHost rewrite fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#2995]
A subrequest using a VirtualHost rewrite may fail with a transform error because of unicode problems. It worked fine on Plone 4.3.18, but fails on 4.3.19 (and also 5.1.6, as I conclude later). Difference: plone.subrequest was updated from 1.8.5 to 1.8.6, with some Python 2/3 and Zope 4 fixes. Pinning it back to 1.8.5 fixes the problem.

I may be able to come up with an easier way to reproduce this, but currently you need collective.cover:

* Plone 4.3.19
* collective.cover master branch (2.2.1 unreleased, but same for 1.7b3).
* Create a Plone Site, install collective.cover, and create a cover.
* On the Layout tab of the cover, add a rich text tile.
* On the Compose tab of the cover, add content to this tile. Let this contain an internal link, and some unicode.
* View the cover on the normal url, it works fine. In my case: http://localhost:8080/Plone/my-cover/
* View the same cover on a url like would happen with VirtualHostMonster rewriting in nginx or Apache: http://localhost:8080/VirtualHostBase/http/localhost:9200/VirtualHostRoot/Plone/my-cover/. This will say "There was an error while rendering this tile”. (And it is ugly because css cannot be loaded, unless you actually have a properly configured nginx running on that port 9200, but that is not the point.)

Sample html content of tile:

```
<p>An internal <a class="internal-link" href="resolveuid/cc5edba9092744bcb4939e440a836d6f" target="_self" title="">link</a>.</p>
<p>And some ünicode.</p>
```

This causes two related tracebacks:

```
2019-12-04 12:01:59 ERROR plone.app.textfield Transform exception
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp27m/plone.app.textfield-1.2.11-py2.7.egg/plone/app/textfield/transform.py", line 46, in __call__
    encoding=value.encoding)
  File "/Users/maurits/shared-eggs/cp27m/Products.PortalTransforms-2.1.12-py2.7.egg/Products/PortalTransforms/TransformEngine.py", line 171, in convertTo
    usedby=usedby, **kwargs)
  File "/Users/maurits/shared-eggs/cp27m/Products.PortalTransforms-2.1.12-py2.7.egg/Products/PortalTransforms/chain.py", line 51, in convert
    data = transform.convert(orig, data, **kwargs)
  File "/Users/maurits/shared-eggs/cp27m/Products.PortalTransforms-2.1.12-py2.7.egg/Products/PortalTransforms/Transform.py", line 196, in convert
    return self._v_transform.convert(*args, **kwargs)
  File "/Users/maurits/shared-eggs/cp27m/plone.outputfilters-1.15.3-py2.7.egg/plone/outputfilters/transforms/html_to_plone_outputfilters_html.py", line 47, in convert
    res = apply_filters(filters, orig)
  File "/Users/maurits/shared-eggs/cp27m/plone.outputfilters-1.15.3-py2.7.egg/plone/outputfilters/__init__.py", line 6, in apply_filters
    res = filter(data)
  File "/Users/maurits/shared-eggs/cp27m/plone.outputfilters-1.15.3-py2.7.egg/plone/outputfilters/filters/resolveuid_and_caption.py", line 123, in __call__
    return self.getResult()
  File "/Users/maurits/shared-eggs/cp27m/plone.outputfilters-1.15.3-py2.7.egg/plone/outputfilters/filters/resolveuid_and_caption.py", line 413, in getResult
    result = "".join(self.pieces)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
2019-12-04 12:01:59 ERROR plone.subrequest Error handling subrequest to http://localhost:9200/Plone/my-cover/@@collective.cover.richtext/fff3fdee-254a-42f7-b915-401b4ca75537
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp27m/plone.subrequest-1.8.6-py2.7.egg/plone/subrequest/__init__.py", line 163, in subrequest
    bind=1
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.29-py2.7.egg/ZPublisher/mapply.py", line 78, in mapply
    else: return object(*args)
  File "/Users/maurits/shared-eggs/cp27m/plone.tiles-2.1-py2.7.egg/plone/tiles/esi.py", line 87, in __call__
    return self.index(*args, **kwargs)
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.29-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.29-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/Users/maurits/shared-eggs/cp27m/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/Users/maurits/shared-eggs/cp27m/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 240, in __call__
    interpreter()
  File "/Users/maurits/shared-eggs/cp27m/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 271, in __call__
    self.interpret(self.program)
  File "/Users/maurits/shared-eggs/cp27m/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/maurits/shared-eggs/cp27m/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 583, in do_setLocal_tal
    self.engine.setLocal(name, self.engine.evaluateValue(expr))
  File "/Users/maurits/shared-eggs/cp27m/zope.tales-3.5.3-py2.7.egg/zope/tales/tales.py", line 696, in evaluate
    return expression(self)
  File "/Users/maurits/shared-eggs/cp27m/zope.tales-3.5.3-py2.7.egg/zope/tales/expressions.py", line 217, in __call__
    return self._eval(econtext)
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.29-py2.7.egg/Products/PageTemplates/Expressions.py", line 155, in _eval
    return render(ob, econtext.vars)
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.29-py2.7.egg/Products/PageTemplates/Expressions.py", line 117, in render
    ob = ob()
  File "/Users/maurits/community/collective.cover/src/collective/cover/tiles/richtext.py", line 53, in getText
    text = transformer(text, 'text/x-html-safe')
  File "/Users/maurits/shared-eggs/cp27m/plone.app.textfield-1.2.11-py2.7.egg/plone/app/textfield/transform.py", line 69, in __call__
    raise TransformError('Error during transformation', e)
TransformError: Error during transformation
```

Near the bottom of the second traceback you see that the cover tile is calling the safe html transform. And that causes the first traceback. It fails in the [resolve uid and caption filter](https://github.com/plone/plone.outputfilters/blob/1.15.3/plone/outputfilters/filters/resolveuid_and_caption.py#L413). This code does `"".join(self.pieces)` and this fails because one of the pieces is unicode, and another is a utf-8 encoded string:

```
['<p>',
 'An internal ',
 u'<a style="" target="_self" title="" href="http://localhost:9200/Plone/news" data-mce-href="resolveuid/cc5edba9092744bcb4939e440a836d6f" class="internal-link">',
 'link',
 '</a>',
 '.',
 '<br data-mce-bogus="1" />',
 '</p>',
 '<p>',
 'And some \xc3\xbcnicode.',
 '<br data-mce-bogus="1" />',
 '</p>']
```

And you cannot join those. The error is basically the same as in this plain Python 2.7 example:

```
>>> x = '\xc3\xbcnicode'
>>> print(x)
ünicode
>>> x + u''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

I expect that the core elements for reproducing this, are:

* A text with an internal link, so the resolveuid transform/filter is called.
* A unicode character in the text.
* Call this text in a subrequest. Maybe a Diazo rule can do the trick.

So, plone.subrequest 1.8.6 causes the problem because it adds compatibility with Python 3 and Zope 4, one of the changes being that subrequest urls are turned into from string into unicode (from bytes to text). But this version is only used on Plone 4.3, 5.0 and 5.1. So the change is useless. So maybe we should just revert these changes on the 1.8.x branch.

To check:
* Is this also happening on Plone 5.1, like I expect? Answer: yes. I migrated my collective.cover buildout to 5.1 and had the same problem with this content. And with plone.subrequest 1.8.5 it is fine.
* Is this also a problem on Plone 5.2 with Python 2.7?
* Does it actually work on Plone 5.2 with Python 3?

FYI @idgserpro @hvelarde

**Comment by mauritsvanrees** [comment]
I tried to [add a test](https://github.com/plone/Products.CMFPlone/commit/788b1d013aa42924a044455c1a2fea2c6fd69d92) for this, but it did not trigger an error.

**Comment by mauritsvanrees** [comment]
I haven't got further with this. Most importantly, I don't know if this is also a problem on Plone 5.2 with some Python versions.

But the bottom line is: the latest `plone.subrequest` releases on the 1.8 branch are for Python 3 compatibility, so they are not useful at all for Plone 5.1 and earlier. But those are the only Plone versions that use this branch.
I propose to revert those changes (I can make a PR) and make a fresh 1.8.7 release without them. 
Does that sound okay?

**Comment by mauritsvanrees** [comment]
I have made the proposed PR: https://github.com/plone/plone.subrequest/pull/23

**Comment by jensens** [comment]
PR as merged
