### ISSUE TITLE
TypeError: can't subtract offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3056]
On Jenkins, I have seen lots of errors like this in several jobs:

```
portlets - ERROR - Error while determining renderer availability of portlet ('context' '/plone' 'events'): can't subtract offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/jenkins/.buildout/eggs/cp27m/plone.portlets-2.3.1-py2.7.egg/plone/portlets/manager.py", line 119, in _lazyLoadPortlets
    isAvailable = renderer.available
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.event-3.2.6-py2.7.egg/plone/app/event/portlets/portlet_events.py", line 141, in available
    return self.data.count > 0 and len(self.events)
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.event-3.2.6-py2.7.egg/plone/app/event/portlets/portlet_events.py", line 189, in events
    expand=True, limit=data.count, **query
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.event-3.2.6-py2.7.egg/plone/app/event/base.py", line 163, in get_events
    sort_reverse)
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.event-3.2.6-py2.7.egg/plone/app/event/base.py", line 283, in expand_events
    IRecurrenceSupport(obj).occurrences(start, end)]
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.event-3.2.6-py2.7.egg/plone/app/event/recurrence.py", line 77, in occurrences
    duration = event_end - event_start
TypeError: can't subtract offset-naive and offset-aware datetimes
```

This is an error while rendering a portlet, so maybe it does not result in an actual test failure.

Example job it [this PR on 5.2 Py 2.7](https://jenkins.plone.org/job/pull-request-5.2/937/console), where among others it goes wrong during this test which passes fine locally:

    bin/test --all -s Products.CMFPlone -t test_querystring.robot

Any idea?

**Comment by jensens** [comment]
Code path still exists in Plone 6: plone.app.event recurrence.py line 71 (duration = event_end - event_start) can still fail if one datetime is timezone-aware and the other is naive. Needs verification on Plone 6.
