### ISSUE TITLE
Internal Server Error with new installed PLONE 5.2.1 ZEO

### ISSUE THREAD

**Issue by PeterBaeuerle** [plone/Products.CMFPlone#3072]
I installed a new downloaded PLONE 5.2.1 with unifed Installer Plone-5.2.1-UnifiedInstaller-r3 with ZEO option. After having adjusted the Ports in buildout.cfg and running buildout I get this message, when calling the clients od ZMI:

Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)

When running in fg I see
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)

Taceback:

Serving on http://0.0.0.0:8083
2020-03-16 11:57:03,981 ERROR   [waitress:357][waitress] Exception while serving /
Traceback (most recent call last):
  File "/home/users/mlpd/Plone/buildout-cache/eggs/waitress-1.4.3-py2.7.egg/waitress/channel.py", line 349, in service
    task.service()
  File "/home/users/mlpd/Plone/buildout-cache/eggs/waitress-1.4.3-py2.7.egg/waitress/task.py", line 169, in service
    self.execute()
  File "/home/users/mlpd/Plone/buildout-cache/eggs/waitress-1.4.3-py2.7.egg/waitress/task.py", line 439, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/home/users/mlpd/Plone/buildout-cache/eggs/Paste-3.1.1-py2.7.egg/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/users/mlpd/Plone/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/home/users/mlpd/Plone/buildout-cache/eggs/Zope-4.1.3-py2.7.egg/ZPublisher/WSGIPublisher.py", line 357, in publish_module
    start_response(status, headers)
  File "/home/users/mlpd/Plone/buildout-cache/eggs/Paste-3.1.1-py2.7.egg/paste/translogger.py", line 67, in replacement_start_response
    self.write_log(environ, method, req_uri, start, status, bytes)
  File "/home/users/mlpd/Plone/buildout-cache/eggs/Paste-3.1.1-py2.7.egg/paste/translogger.py", line 99, in write_log
    message = self.format % d
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)

Debugger Results:

/home/users/mlpd/Plone/buildout-cache/eggs/Paste-3.1.1-py2.7.egg/paste/translogger.py(100)write_log()
-> message = self.format % d
(Pdb) print d
{'REQUEST_METHOD': 'GET', 'status': '200', 'REMOTE_USER': u'admin', 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0', 'HTTP_REFERER': '-', 'REMOTE_ADDR': '93.206.36.15', 'HTTP_VERSION': 'HTTP/1.1', 'time': '17/M\xc3\xa4r/2020:09:49:53 +0200', 'bytes': '7807', 'REQUEST_URI': '/'}
(Pdb)

(Pdb) print self.format
%(REMOTE_ADDR)s - %(REMOTE_USER)s [%(time)s] "%(REQUEST_METHOD)s %(REQUEST_URI)s %(HTTP_VERSION)s" %(status)s %(bytes)s "%(HTTP_REFERER)s" "%(HTTP_USER_AGENT)s"

Some explanations:

There is some unexpected German month name inside the data

'time': '17/M\xc3\xa4r/2020:09:49:53 +0200

The month name should clearly be in English.

**Comment by 1letter** [comment]
The issue should post to [https://github.com/cdent/paste/](url), where it happens.
