### ISSUE TITLE
toolbar fails to render when seeing comments views on folderish objects

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#3073]
Or to put it more simply:

- create a Plone 5.2.1 site
- globally enable comments
- create a folder (say `hi-folder`) and enable comments on it
- create a comment
- the toolbar fails to render when seeing the history view of the comment `http://localhost:8080/Plone/hi-folder/++conversation++default/COMMENT_ID/@@historyview`

The traceback is:

```
Traceback (most recent call last):
  File "/home/gil/.buildout/eggs/plone.app.viewletmanager-3.1.0-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/gil/.buildout/eggs/plone.app.layout-3.4.0-py2.7.egg/plone/app/layout/viewlets/common.py", line 73, in render
    return self.index()
  File "/home/gil/.buildout/eggs/Zope-4.1.3-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 126, in __call__
    return self.__func__(__self__, *args, **kw)
  File "/home/gil/.buildout/eggs/Zope-4.1.3-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 61, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/gil/.buildout/eggs/zope.pagetemplate-4.4.1-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 135, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/gil/.buildout/eggs/Zope-4.1.3-py2.7.egg/Products/PageTemplates/engine.py", line 88, in __call__
    return self.template.render(**kwargs)
  File "/home/gil/.buildout/eggs/z3c.pt-3.2.0-py2.7.egg/z3c/pt/pagetemplate.py", line 173, in render
    return base_renderer(**context)
  File "/home/gil/.buildout/eggs/Chameleon-3.6.2-py2.7.egg/chameleon/zpt/template.py", line 306, in render
    return super(PageTemplate, self).render(**_kw)
  File "/home/gil/.buildout/eggs/Chameleon-3.6.2-py2.7.egg/chameleon/template.py", line 187, in render
    self._render(stream, econtext, rcontext)
  File "/home/gil/Documents/freitag/git/plain-plone/var/cache/751996ac20a86adc2782a13a21c5882c.py", line 149, in render
    __cache_139970452891856 = _render_content_provider(econtext, __cache_139970452891856)
  File "/home/gil/.buildout/eggs/z3c.pt-3.2.0-py2.7.egg/z3c/pt/expressions.py", line 73, in render_content_provider
    return cp.render()
  File "/home/gil/.buildout/eggs/plone.app.contentmenu-2.3.0-py2.7.egg/plone/app/contentmenu/view.py", line 18, in render
    return self.index()
  File "/home/gil/.buildout/eggs/Zope-4.1.3-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 126, in __call__
    return self.__func__(__self__, *args, **kw)
  File "/home/gil/.buildout/eggs/Zope-4.1.3-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 61, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/gil/.buildout/eggs/zope.pagetemplate-4.4.1-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 135, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/gil/.buildout/eggs/Zope-4.1.3-py2.7.egg/Products/PageTemplates/engine.py", line 88, in __call__
    return self.template.render(**kwargs)
  File "/home/gil/.buildout/eggs/z3c.pt-3.2.0-py2.7.egg/z3c/pt/pagetemplate.py", line 173, in render
    return base_renderer(**context)
  File "/home/gil/.buildout/eggs/Chameleon-3.6.2-py2.7.egg/chameleon/zpt/template.py", line 306, in render
    return super(PageTemplate, self).render(**_kw)
  File "/home/gil/.buildout/eggs/Chameleon-3.6.2-py2.7.egg/chameleon/template.py", line 209, in render
    raise_with_traceback(exc, tb)
  File "/home/gil/.buildout/eggs/Chameleon-3.6.2-py2.7.egg/chameleon/template.py", line 187, in render
    self._render(stream, econtext, rcontext)
  File "/home/gil/Documents/freitag/git/plain-plone/var/cache/4a169b28367e01c3d13dc06717a9c2aa.py", line 113, in render
    __value = _static_139970562108112(getitem('view'), econtext, True, ('menu', ))
  File "/home/gil/.buildout/eggs/Zope-4.1.3-py2.7.egg/Products/PageTemplates/expression.py", line 101, in __call__
    return base()
  File "/home/gil/.buildout/eggs/plone.app.contentmenu-2.3.0-py2.7.egg/plone/app/contentmenu/view.py", line 27, in menu
    items = menu.getMenuItems(self.context, self.request)
  File "/home/gil/.buildout/eggs/zope.browsermenu-4.4-py2.7.egg/zope/browsermenu/menu.py", line 52, in getMenuItems
    if item.available():
  File "/home/gil/.buildout/eggs/plone.memoize-2.0.1-py2.7.egg/plone/memoize/instance.py", line 53, in memogetter
    val = func(*args, **kwargs)
  File "/home/gil/.buildout/eggs/plone.app.contentmenu-2.3.0-py2.7.egg/plone/app/contentmenu/menu.py", line 178, in available
    if self.disabled():
  File "/home/gil/.buildout/eggs/plone.memoize-2.0.1-py2.7.egg/plone/memoize/instance.py", line 53, in memogetter
    val = func(*args, **kwargs)
  File "/home/gil/.buildout/eggs/plone.app.contentmenu-2.3.0-py2.7.egg/plone/app/contentmenu/menu.py", line 232, in disabled
    if not getattr(context, 'isPrincipiaFolderish', False):
AttributeError: __contains__
```

i.e. on [plone.app.contentmenu.menu line 232](https://github.com/plone/plone.app.contentmenu/blob/6f1a748fabcd6db9947b6aa767161bf45e830db0/plone/app/contentmenu/menu.py#L224-L236) a comment is not a default page, due to being on a folder the `isPrincipiaFolderish` does not work either and finally it gets to the `elif 'index_html' not in context` but a comment does not have a `__contains__`. :man_shrugging: 

**how to solve it?**
- should comments have an explicit `isPrincipiaFolderish` set to `False`?
- should comments implement `__contains__` ?
- should an explicit check on `plone.app.contentmenu` be added to check for comments on that method?
- *other ideas*?

**Comment by jensens** [comment]
Closing as outdated (6 years old). About toolbar crash on comment views. plone.app.contentmenu has been refactored and the specific code path updated.
If you think this issue is still relevant please reopen it. Thank you for the original report!
