### ISSUE TITLE
Error with catalog search for title with round brackets

### ISSUE THREAD

**Issue by achimwilde** [plone/Products.CMFPlone#3268]
### What I did:

Run a catalog search for a title with round brackets: portal_catalog.searchResults(Title="test (test2)")

### What I expect to happen:

[]

### What actually happened:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/plone/api/buildout-cache/eggs/Products.CMFPlone-5.2.1-py3.6.egg/Products/CMFPlone/CatalogTool.py", line 457, in searchResults
    return ZCatalog.searchResults(self, query, **kw)
  File "/opt/plone/api/buildout-cache/eggs/Products.ZCatalog-5.0.1-py3.6.egg/Products/ZCatalog/ZCatalog.py", line 611, in searchResults
    return self._catalog.searchResults(query, **kw)
  File "/opt/plone/api/buildout-cache/eggs/Products.ZCatalog-5.0.1-py3.6.egg/Products/ZCatalog/Catalog.py", line 1091, in searchResults
    return self.search(query, sort_indexes, reverse, sort_limit, _merge)
  File "/opt/plone/api/buildout-cache/eggs/Products.ZCatalog-5.0.1-py3.6.egg/Products/ZCatalog/Catalog.py", line 634, in search
    rs = self._search_index(cr, index_id, query, rs)
  File "/opt/plone/api/buildout-cache/eggs/Products.ZCatalog-5.0.1-py3.6.egg/Products/ZCatalog/Catalog.py", line 564, in _search_index
    index_rs = index.query_index(index_query, rs)
  File "/opt/plone/api/buildout-cache/eggs/Products.ZCatalog-5.0.1-py3.6.egg/Products/ZCTextIndex/ZCTextIndex.py", line 209, in query_index
    tree = QueryParser(self.getLexicon()).parseQuery(query_str)
  File "/opt/plone/api/buildout-cache/eggs/Products.ZCatalog-5.0.1-py3.6.egg/Products/ZCTextIndex/QueryParser.py", line 154, in parseQuery
    self._require(_EOF)
  File "/opt/plone/api/buildout-cache/eggs/Products.ZCatalog-5.0.1-py3.6.egg/Products/ZCTextIndex/QueryParser.py", line 174, in _require
    raise ParseTree.ParseError(msg)
Products.ZCTextIndex.ParseTree.ParseError: Token <Token:EOF> required, '(' found
```

### What version of Plone/ Addons I am using:

Plone 5, multiple versions affected

**Comment by achimwilde** [comment]
Hm...

https://community.plone.org/t/parseerror-when-search-term-contains-parenthesis-in-zcatalog-search/13424

**Comment by jensens** [comment]
Closing as outdated (5 years old). This is a ZCatalog/ZCTextIndex query parser issue (parentheses are query syntax), not a CMFPlone bug. No activity since 2021.
If you think this issue is still relevant please reopen it. Thank you for the original report!
