### ISSUE TITLE
Viewing Plone 5.2 site with wsgi=off (ZServer) fails.

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#3337]
I get this traceback:

```
2021-10-20 10:12:59 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp27m/ZServer-4.0.2-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 32, in __init__
    response=b)
  File "/Users/maurits/shared-eggs/cp27m/ZServer-4.0.2-py2.7.egg/ZServer/ZPublisher/Publish.py", line 404, in publish_module
    environ, debug, request, response)
  File "/Users/maurits/shared-eggs/cp27m/ZServer-4.0.2-py2.7.egg/ZServer/ZPublisher/Publish.py", line 279, in publish_module_standard
    outputBody()
  File "/Users/maurits/shared-eggs/cp27m/ZServer-4.0.2-py2.7.egg/ZServer/HTTPResponse.py", line 252, in outputBody
    self.stdout.write(str(self))
  File "/Users/maurits/shared-eggs/cp27m/ZServer-4.0.2-py2.7.egg/ZServer/HTTPResponse.py", line 145, in __str__
    return "\r\n".join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 190: ordinal not in range(128)
```

To reproduce:

- Use `buildout.coredev` branch 5.2.
- Edit `core.cfg`, go to the `instance:python27` part and add `wsgi = off`.
- Bootstrap with python 2.7 and run buildout.
- Start Plone, create a Plone Site. This actually works.
- But viewing it fails with the `UnicodeDecodeError`.
- Viewing an already existing Plone Site fails as well.

When I go in with a `pdb`, these are the chunks that it tries to combine:

```
pp chunks
['HTTP/1.1 200 OK',
 'Server: Zope/(4.6.3, python 2.7.17, darwin) ZServer/1.1',
 'Date: Wed, 20 Oct 2021 08:15:57 GMT',
 'Content-Length: 29675',
 'Expires: Sat, 1 Jan 2000 00:00:00 GMT',
 'Content-Type: text/html;charset=utf-8',
 'X-Frame-Options: SAMEORIGIN',
 u'Content-Language: nl',
 '',
 '<!DOCTYPE html>\n...']
```

The odd-one-out here is ` u'Content-Language: nl'` which is the only unicode, even though it only contains ascii characters.

We could call this a breaking bug, but it is already there since at least Plone 5.2.5, because [`buildout.plonetest` had the same problem](https://github.com/collective/buildout.plonetest/pull/80).

I really don't want to work on this right now, and I am not going to. Might be a low-level problem in `ZServer` or `Zope`.

**Comment by mauritsvanrees** [comment]
Still a problem in current 5.2 on Py 2. Might be in `plone.app.layout`, which seems the only place where `Content-Language` is set:

```
parts/packages/plone/app/layout/viewlets/httpheaders.py
24-
25-    def getHeaders(self):
26-        lang = getattr(self.context, "Language", None)
27-        if callable(lang):
28-            lang = lang()
29-        if not lang:
30-            lang = self.portal_state.default_language()
31-        return [
32-            ("Content-Type", "text/html;charset=utf-8"),
33-            ("Expires", "Sat, 1 Jan 2000 00:00:00 GMT"),
34:            ("Content-Language", lang),
35-        ]
```

But not something I will tackle now.

**Comment by jensens** [comment]
Closing as outdated (4 years old). About Plone 5.2 with ZServer (non-WSGI). ZServer is Python 2 only. Plone 6 uses WSGI exclusively.
If you think this issue is still relevant please reopen it. Thank you for the original report!
