### ISSUE TITLE
Broken alias for getAllowedSizes

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#3641]
PR #3615 introduced some broken aliases after some helpers were moved:
```console
ale@avo:~/Code/plone/projects/coredev/6.0$ ./bin/zopepy 
>>> from Products.CMFPlone.utils import getAllowedSizes
<console>:1: DeprecationWarning: getAllowedSizes is deprecated. Import from plone.namedfile.utils instead (will be removed in Plone 7)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ale/.buildout/eggs/cp310/zope.deferredimport-4.4-py3.10.egg/zope/deferredimport/deferredmodule.py", line 71, in __getattr__
    v = get.get()
  File "/home/ale/.buildout/eggs/cp310/zope.deferredimport-4.4-py3.10.egg/zope/deferredimport/deferredmodule.py", line 55, in get
    return super(DeferredAndDeprecated, self).get()
  File "/home/ale/.buildout/eggs/cp310/zope.deferredimport-4.4-py3.10.egg/zope/deferredimport/deferredmodule.py", line 37, in get
    v = __import__(module, *self._import_chicken)
ModuleNotFoundError: No module named 'plone.namedfile.utils.getAllowedSizes'
```

**Comment by ale-rt** [comment]
Workaround and future proof code:
```python
try:
    from plone.namedfile.utils import getAllowedSizes
except ImportError:
    # BBB Plone 5.2
    from Products.CMFPlone.utils import getAllowedSizes
```
