### ISSUE TITLE
Write-on-Read in Products.CMFPlone.Portal.PloneSite

### ISSUE THREAD

**Issue by darryldixon** [plone/Products.CMFPlone#3712]
Hi, lines 100 and 107 in PloneSite.py in Products.CMFPlone 5.2.6 call "setattr(...)" - this causes a transaction commit and will fail when the Plone Site is being served from a ReadOnly database:

`2023-01-17 13:57:18,705 ERROR   [plone.transformchain:70][waitress-1] Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/u01/pre/general-node2/eggscache/plone.transformchain-2.0.2-py2.7.egg/plone/transformchain/transformer.py", line 59, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/u01/pre/general-node2/eggscache/plone.caching-1.2.2-py2.7.egg/plone/caching/hooks.py", line 151, in transformIterable
    self.mutate()
  File "/u01/pre/general-node2/eggscache/plone.caching-1.2.2-py2.7.egg/plone/caching/hooks.py", line 163, in mutate
    rule, operationName, operation = findOperation(request)
  File "/u01/pre/general-node2/eggscache/plone.caching-1.2.2-py2.7.egg/plone/caching/utils.py", line 106, in findOperation
    rule = lookup()
  File "/u01/pre/general-node2/eggscache/plone.app.caching-2.1.0-py2.7.egg/plone/app/caching/lookup.py", line 93, in __call__
    defaultView = getObjectDefaultView(parent)
  File "/u01/pre/general-node2/eggscache/plone.app.caching-2.1.0-py2.7.egg/plone/app/caching/utils.py", line 53, in getObjectDefaultView
    return stripLeadingCharacters(browserDefault.defaultView())
  File "/u01/pre/general-node2/eggscache/Products.CMFDynamicViewFTI-6.0.3-py2.7.egg/Products/CMFDynamicViewFTI/browserdefault.py", line 67, in defaultView
    return fti.defaultView(self)
  File "/u01/pre/general-node2/eggscache/Products.CMFDynamicViewFTI-6.0.3-py2.7.egg/Products/CMFDynamicViewFTI/fti.py", line 201, in defaultView
    obj, path = plone_utils.browserDefault(context)
  File "/u01/pre/general-node2/eggscache/Products.CMFPlone-5.2.6-py2.7.egg/Products/CMFPlone/PloneTool.py", line 655, in browserDefault
    if not isinstance(getattr(obj, 'index_html', None),
  File "/u01/pre/general-node2/eggscache/Products.CMFPlone-5.2.6-py2.7.egg/Products/CMFPlone/Portal.py", line 107, in index_html
    setattr(result, '__replaceable__', REPLACEABLE)
  File "/u01/pre/general-node2/eggscache/ZODB-5.5.1-py2.7.egg/ZODB/Connection.py", line 830, in register
    self._register(obj)
  File "/u01/pre/general-node2/eggscache/ZODB-5.5.1-py2.7.egg/ZODB/Connection.py", line 840, in _register
    self.transaction_manager.get().join(self)
  File "/u01/pre/general-node2/eggscache/transaction-3.0.1-py2.7-linux-x86_64.egg/transaction/_transaction.py", line 186, in join
    self._prior_operation_failed()  # doesn't return
  File "/u01/pre/general-node2/eggscache/transaction-3.0.1-py2.7-linux-x86_64.egg/transaction/_transaction.py", line 181, in _prior_operation_failed
    self._failure_traceback.getvalue())
`

etc. This causes a cascade of failure resulting in:
`  File "/u01/pre/general-node2/eggscache/ZODB-5.5.1-py2.7.egg/ZODB/Connection.py", line 480, in tpc_begin
    self._normal_storage.tpc_begin(meta_data)
  File "/u01/pre/general-node2/eggscache/ZODB-5.5.1-py2.7.egg/ZODB/mvccadapter.py", line 161, in tpc_begin
    self._storage.tpc_begin(transaction)
  File "/u01/pre/general-node2/eggscache/ZEO-5.2.2-py2.7-linux-x86_64.egg/ZEO/ClientStorage.py", line 801, in tpc_begin
    raise POSException.ReadOnlyError()
ReadOnlyError
`

**Comment by darryldixon** [comment]
Needs something like:

```
                if not getattr(result, '_p_jar', getattr(self, '_p_jar')).db().storage.isReadOnly():
                    setattr(result, '__replaceable__', REPLACEABLE)
```

**Comment by yurj** [comment]
https://github.com/plone/Products.CMFPlone/pull/3060

**Comment by jensens** [comment]
Closing as outdated (3 years old). Fixed: the write-on-read code path now only runs when HAS_ZSERVER is True, which is never the case in Plone 6.
If you think this issue is still relevant please reopen it. Thank you for the original report!
