### ISSUE TITLE
Problems migrating from `5.2-latest` to `6.0-latest`

### ISSUE THREAD

**Issue by petschki** [plone/Products.CMFPlone#3787]
When running `@@plone-upgrade` on a `5.2-latest` database with `6.0-latest` buildout installation I get the following traceback:

```
Traceback (most recent call last):
  File "/Users/peterm/workspace/gbd/eggs/Products.CMFPlone-6.0.4-py3.11.egg/Products/CMFPlone/MigrationTool.py", line 299, in upgrade
    step['step'].doStep(setup)
  File "/Users/peterm/workspace/gbd/eggs/Products.GenericSetup-3.0.1-py3.11.egg/Products/GenericSetup/upgrade.py", line 225, in doStep
    tool.runAllImportStepsFromProfile(profile_id,
  File "/Users/peterm/workspace/gbd/eggs/Products.GenericSetup-3.0.1-py3.11.egg/Products/GenericSetup/tool.py", line 393, in runAllImportStepsFromProfile
    result = self._runImportStepsFromContext(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/gbd/eggs/Products.GenericSetup-3.0.1-py3.11.egg/Products/GenericSetup/tool.py", line 1504, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/gbd/eggs/Products.GenericSetup-3.0.1-py3.11.egg/Products/GenericSetup/tool.py", line 1316, in _doRunImportStep
    return handler(context)
           ^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/gbd/eggs/plone.app.registry-2.0.2-py3.11.egg/plone/app/registry/exportimport/handler.py", line 79, in importRegistry
    importer.importDocument(body)
  File "/Users/peterm/workspace/gbd/eggs/plone.app.registry-2.0.2-py3.11.egg/plone/app/registry/exportimport/handler.py", line 125, in importDocument
    self.importRecords(node)
  File "/Users/peterm/workspace/gbd/eggs/plone.app.registry-2.0.2-py3.11.egg/plone/app/registry/exportimport/handler.py", line 391, in importRecords
    interface=interface.__identifier__,
              ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute '__identifier__'
```

Turns out, that `zope.dottedname.resolve` returns a dict for `Products.CMFPlone.interfaces.IBundleRegistry` likely because the location is marked as deprecated and should be `plone.base.interfaces.resources.IBundleRegistry` now ... but the old interface is defined in the `to_6004` profile of `plone.app.upgrade`.

Has anyone some pointers how to fix that? Is it a problem of `zope.deferredimport` in combination with `zope.dottedname` ? 

/cc @maurits @jensens

**Comment by petschki** [comment]
Aha ... the problem is when marking as `zope.deferredimport.deprecated` it doesn't get resolved. When marked as `zope.deprecation.moved` it gets resolved to the new location:

```
(Pdb++) resolve("plone.base.interfaces.resources.IBundleRegistry")
<InterfaceClass plone.base.interfaces.resources.IBundleRegistry>
(Pdb++) resolve("Products.CMFPlone.interfaces.IBundleRegistry")
{}
(Pdb++) resolve("Products.CMFPlone.interfaces.resources.IBundleRegistry")
<InterfaceClass plone.base.interfaces.resources.IBundleRegistry>
```

**Comment by gforcada** [comment]
I was having the same problem the other day 😓

**Comment by mauritsvanrees** [comment]
Is this a problem with 6.0.4 already, or new in 6.0-latest?

Workaround might be to call `bin/zodbupdate`, but that may need `moved` instead of `deprecated` as well.  And it should usually be called after running `@@plone-upgrade` and not before.

**Comment by petschki** [comment]
This is since the Interface imports have been moved from `Products.CMFPlone.interfaces` to `plone.base.interfaces` so as I can see in the repo since `6.0a4` ... the (not so) fun fact about this: if I run the `plone.app.upgrade` tests, the interfaces get resolved correctly ... so I got stuck in debugging how to solve this in the real world...

**Comment by petschki** [comment]
@icemac do you know this issue?

**Comment by icemac** [comment]
> @icemac do you know this issue?

No, I've never seen this before.

**Comment by gforcada** [comment]
I'm still having this problem, for now, my current hack is to modify `plone.app.upgrade` and `plone.staticresources` `registry.xml` to point to the `plone.base` locations and see if I can get it through.

A proper fix would be nice though 😅 

Maybe an upgrade to 6.0.3 and later to something else might work? I will give it a go 🤞🏾

**Comment by jensens** [comment]
Closing as resolved. Fixed: zope.dottedname.resolve now correctly returns InterfaceClass. Upgrade profiles reference plone.base.interfaces directly.
Thank you for the original report!
