### ISSUE TITLE
DX-types fail when using MessageFactory

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#386]
When I create a simple DX-type and use the messagefactory to allow translating the title I get a traceback. 

When I use unicode without ``_`` it works.
I use todays Plone5-coredev (zope.schema = 4.2.2)

This breaks:

    # -*- coding: utf-8 -*-
    from plone.supermodel import model
    from ploneconf.site import MessageFactory as _
    from zope import schema

    class ISpeaker(model.Schema):

        first_name = schema.TextLine(
            title=_(u'First Name'),
        )

Traceback:

    2015-02-26 17:45:38 ERROR Zope.SiteErrorLog 1424969138.980.355089187521 http://localhost:8080/Plone/ordner/++add++speaker
    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
      Module ZPublisher.Publish, line 48, in call_object
      Module plone.z3cform.layout, line 63, in __call__
      Module plone.z3cform.layout, line 47, in update
      Module plone.dexterity.browser.add, line 121, in update
      Module plone.z3cform.fieldsets.extensible, line 63, in update
      Module plone.autoform.form, line 33, in updateFields
      Module plone.autoform.base, line 54, in updateFieldsFromSchemata
      Module plone.dexterity.browser.base, line 28, in schema
      Module plone.dexterity.fti, line 235, in lookupSchema
      Module plone.dexterity.utils, line 52, in resolveDottedName
      Module zope.dottedname.resolve, line 38, in resolve
      Module None, line 14, in <module>
      Module None, line 19, in ISpeaker
      Module zope.schema._bootstrapfields, line 324, in __init__
      Module zope.schema._bootstrapfields, line 306, in __init__
      Module zope.schema._bootstrapfields, line 151, in __init__
      Module zope.schema.fieldproperty, line 52, in __set__
      Module zope.schema._bootstrapfields, line 182, in validate
      Module zope.schema._bootstrapfields, line 309, in _validate
      Module zope.schema._bootstrapfields, line 209, in _validate
    WrongType: (<zope.i18nmessageid.message.MessageFactory object at 0x10c16ec90>, <type 'unicode'>, 'title')

This works

    class ISpeaker(model.Schema):

        first_name = schema.TextLine(
            title=u'First Name',
        )

MessageFactory is: 

    from zope.i18nmessageid import MessageFactory
    _ = MessageFactory('ploneconf.site')

The same happens (and is faster to reproduce) when using zopy to import the class:

    [philip@lightning ~/workspace/training/buildout (plone5)]$ ./bin/zopepy 

    >>> from ploneconf.site.content.speaker import ISpeaker
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/Users/philip/workspace/training/buildout/src/ploneconf.site/src/ploneconf/site/content/speaker.py", line 13, in <module>
        class ISpeaker(model.Schema):
      File "/Users/philip/workspace/training/buildout/src/ploneconf.site/src/ploneconf/site/content/speaker.py", line 18, in ISpeaker
        title=_('First Name'),
      File "/Users/philip/.cache/buildout/eggs/zope.schema-4.2.2-py2.7.egg/zope/schema/_bootstrapfields.py", line 324, in __init__
        super(Text, self).__init__(*args, **kw)
      File "/Users/philip/.cache/buildout/eggs/zope.schema-4.2.2-py2.7.egg/zope/schema/_bootstrapfields.py", line 306, in __init__
        super(MinMaxLen, self).__init__(**kw)
      File "/Users/philip/.cache/buildout/eggs/zope.schema-4.2.2-py2.7.egg/zope/schema/_bootstrapfields.py", line 151, in __init__
        self.title = title
      File "/Users/philip/.cache/buildout/eggs/zope.schema-4.2.2-py2.7.egg/zope/schema/fieldproperty.py", line 52, in __set__
        field.validate(value)
      File "/Users/philip/.cache/buildout/eggs/zope.schema-4.2.2-py2.7.egg/zope/schema/_bootstrapfields.py", line 182, in validate
        self._validate(value)
      File "/Users/philip/.cache/buildout/eggs/zope.schema-4.2.2-py2.7.egg/zope/schema/_bootstrapfields.py", line 309, in _validate
        super(MinMaxLen, self)._validate(value)
      File "/Users/philip/.cache/buildout/eggs/zope.schema-4.2.2-py2.7.egg/zope/schema/_bootstrapfields.py", line 209, in _validate
        raise WrongType(value, self._type, self.__name__)
    WrongType: (<zope.i18nmessageid.message.MessageFactory object at 0x1069760d0>, <type 'unicode'>, 'title')

**Comment by pbauer** [comment]
My bad! The import was wrong. It should have been:

    from ploneconf.site import _
