### ISSUE TITLE
plone.app.folder has test isolation issues.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#449]
Running plone.app.folder and plone.app.caching tests together leads to test failures:

$ bin/test -s plone.app.folder -s plone.app.caching

To be able to run all current test in one alltests group in buildout.coredev, we have to fix those test isolation problems. Running one single alltests group will allow Jenkins to report test failures properly.

```
$ bin/test -s plone.app.folder -s plone.app.caching
Running Testing.ZopeTestCase.layer.ZopeLite tests:
  Set up Testing.ZopeTestCase.layer.ZopeLite in 0.059 seconds.
  Running:

  Ran 2 tests with 0 failures, 0 errors, 0 skipped in 0.004 seconds.
Running plone.app.caching.testing.PloneAppCaching:Functional tests:
  Tear down Testing.ZopeTestCase.layer.ZopeLite in 0.000 seconds.
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.066 seconds.
  Set up plone.app.testing.layers.PloneFixture in 5.090 seconds.
  Set up plone.app.event.testing.PAEventLayer in 0.146 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes in 0.359 seconds.
  Set up plone.app.caching.testing.PloneAppCaching in 0.157 seconds.
  Set up plone.app.caching.testing.PloneAppCaching:Functional in 0.000 seconds.
  Running:
    3/15 (20.0%)

Error in test test_gzip_setting (plone.app.caching.tests.test_integration.TestOperations)
Traceback (most recent call last):
  File "/home/timo/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.caching/plone/app/caching/tests/test_integration.py", line 170, in test_gzip_setting
    self.portal.invokeFactory('Folder', 'f1')
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/PortalFolder.py", line 292, in invokeFactory
    return pt.constructContent(type_name, self, id, RESPONSE, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 833, in constructContent
    ob = info.constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 311, in constructInstance
    return self._constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 569, in _constructInstance
    rval = container._setObject(id, obj)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 326, in _setObject
    v = self._checkId(id)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/Skinnable.py", line 213, in _checkId
    return superCheckId(self, id, allow_dup)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 116, in checkValidId
    'The id "%s" is invalid - it is already in use.' % id)
BadRequest: The id "f1" is invalid - it is already in use.

    4/15 (26.7%)

Error in test test_last_modified_no_etags (plone.app.caching.tests.test_operation_default.TestOperationDefault)
Traceback (most recent call last):
  File "/home/timo/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.caching/plone/app/caching/tests/test_operation_default.py", line 46, in test_last_modified_no_etags
    self.portal.invokeFactory('Folder', 'f1')
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/PortalFolder.py", line 292, in invokeFactory
    return pt.constructContent(type_name, self, id, RESPONSE, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 833, in constructContent
    ob = info.constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 311, in constructInstance
    return self._constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 569, in _constructInstance
    rval = container._setObject(id, obj)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 326, in _setObject
    v = self._checkId(id)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/Skinnable.py", line 213, in _checkId
    return superCheckId(self, id, allow_dup)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 116, in checkValidId
    'The id "%s" is invalid - it is already in use.' % id)
BadRequest: The id "f1" is invalid - it is already in use.

    5/15 (33.3%)

Error in test test_anon_only (plone.app.caching.tests.test_operation_parameters.TestOperationParameters)
Traceback (most recent call last):
  File "/home/timo/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.caching/plone/app/caching/tests/test_operation_parameters.py", line 44, in test_anon_only
    self.portal.invokeFactory('Folder', 'f1')
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/PortalFolder.py", line 292, in invokeFactory
    return pt.constructContent(type_name, self, id, RESPONSE, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 833, in constructContent
    ob = info.constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 311, in constructInstance
    return self._constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 569, in _constructInstance
    rval = container._setObject(id, obj)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 326, in _setObject
    v = self._checkId(id)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/Skinnable.py", line 213, in _checkId
    return superCheckId(self, id, allow_dup)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 116, in checkValidId
    'The id "%s" is invalid - it is already in use.' % id)
BadRequest: The id "f1" is invalid - it is already in use.

    6/15 (40.0%)

Error in test test_composite_views (plone.app.caching.tests.test_profile_with_caching_proxy.TestProfileWithCaching)
Traceback (most recent call last):
  File "/home/timo/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.caching/plone/app/caching/tests/test_profile_with_caching_proxy.py", line 103, in test_composite_views
    self.portal.invokeFactory('Folder', 'f1')
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/PortalFolder.py", line 292, in invokeFactory
    return pt.constructContent(type_name, self, id, RESPONSE, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 833, in constructContent
    ob = info.constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 311, in constructInstance
    return self._constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 569, in _constructInstance
    rval = container._setObject(id, obj)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 326, in _setObject
    v = self._checkId(id)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/Skinnable.py", line 213, in _checkId
    return superCheckId(self, id, allow_dup)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 116, in checkValidId
    'The id "%s" is invalid - it is already in use.' % id)
BadRequest: The id "f1" is invalid - it is already in use.

    8/15 (53.3%)

Error in test test_content_files (plone.app.caching.tests.test_profile_with_caching_proxy.TestProfileWithCaching)
Traceback (most recent call last):
  File "/home/timo/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.caching/plone/app/caching/tests/test_profile_with_caching_proxy.py", line 335, in test_content_files
    self.portal.invokeFactory('Folder', 'f1')
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/PortalFolder.py", line 292, in invokeFactory
    return pt.constructContent(type_name, self, id, RESPONSE, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 833, in constructContent
    ob = info.constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 311, in constructInstance
    return self._constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 569, in _constructInstance
    rval = container._setObject(id, obj)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 326, in _setObject
    v = self._checkId(id)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/Skinnable.py", line 213, in _checkId
    return superCheckId(self, id, allow_dup)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 116, in checkValidId
    'The id "%s" is invalid - it is already in use.' % id)
BadRequest: The id "f1" is invalid - it is already in use.

    11/15 (73.3%)

Error in test test_composite_views (plone.app.caching.tests.test_profile_without_caching_proxy.TestProfileWithoutCaching)
Traceback (most recent call last):
  File "/home/timo/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.caching/plone/app/caching/tests/test_profile_without_caching_proxy.py", line 96, in test_composite_views
    self.portal.invokeFactory('Folder', 'f1')
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/PortalFolder.py", line 292, in invokeFactory
    return pt.constructContent(type_name, self, id, RESPONSE, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 833, in constructContent
    ob = info.constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 311, in constructInstance
    return self._constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 569, in _constructInstance
    rval = container._setObject(id, obj)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 326, in _setObject
    v = self._checkId(id)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/Skinnable.py", line 213, in _checkId
    return superCheckId(self, id, allow_dup)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 116, in checkValidId
    'The id "%s" is invalid - it is already in use.' % id)
BadRequest: The id "f1" is invalid - it is already in use.

    13/15 (86.7%)

Error in test test_content_files (plone.app.caching.tests.test_profile_without_caching_proxy.TestProfileWithoutCaching)
Traceback (most recent call last):
  File "/home/timo/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.caching/plone/app/caching/tests/test_profile_without_caching_proxy.py", line 328, in test_content_files
    self.portal.invokeFactory('Folder', 'f1')
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/PortalFolder.py", line 292, in invokeFactory
    return pt.constructContent(type_name, self, id, RESPONSE, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 833, in constructContent
    ob = info.constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 311, in constructInstance
    return self._constructInstance(container, id, *args, **kw)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/TypesTool.py", line 569, in _constructInstance
    rval = container._setObject(id, obj)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 326, in _setObject
    v = self._checkId(id)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/Skinnable.py", line 213, in _checkId
    return superCheckId(self, id, allow_dup)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 116, in checkValidId
    'The id "%s" is invalid - it is already in use.' % id)
BadRequest: The id "f1" is invalid - it is already in use.

    14/15 (93.3%)

Error in test test_resources (plone.app.caching.tests.test_profile_without_caching_proxy.TestProfileWithoutCaching)
Traceback (most recent call last):
  File "/home/timo/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.caching/plone/app/caching/tests/test_profile_without_caching_proxy.py", line 417, in test_resources
    self.portal.manage_addFile('bigfile', file=StringIO(s), content_type='application/octet-stream')
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/Image.py", line 72, in manage_addFile
    self._setObject(id, File(id,title,'',content_type, precondition))
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 326, in _setObject
    v = self._checkId(id)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/Skinnable.py", line 213, in _checkId
    return superCheckId(self, id, allow_dup)
  File "/home/timo/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 116, in checkValidId
    'The id "%s" is invalid - it is already in use.' % id)
BadRequest: The id "bigfile" is invalid - it is already in use.


  Ran 15 tests with 0 failures, 8 errors, 0 skipped in 6.437 seconds.
Running plone.app.folder.tests.layer.plone.app.folder testing:Integration tests:
  Tear down plone.app.caching.testing.PloneAppCaching:Functional in 0.000 seconds.
  Tear down plone.app.caching.testing.PloneAppCaching in 0.002 seconds.
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes in 0.085 seconds.
  Tear down plone.app.event.testing.PAEventLayer in 0.002 seconds.
  Set up plone.app.testing.bbb.PloneTestCaseFixture Traceback (most recent call last):
  File "/home/timo/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 400, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/home/timo/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 708, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/timo/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 708, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/timo/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 708, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/timo/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 713, in setup_layer
    layer.setUp()
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.testing/plone/app/testing/helpers.py", line 350, in setUp
    self.setUpPloneSite(portal)
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.testing/plone/app/testing/bbb.py", line 42, in setUpPloneSite
    testing.applyProfile(portal, 'Products.ATContentTypes:content')
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.testing/plone/app/testing/helpers.py", line 120, in applyProfile
    blacklisted_steps=blacklisted_steps)
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 365, in runAllImportStepsFromProfile
    blacklisted_steps=blacklisted_steps)
   - __traceback_info__: profile-Products.ATContentTypes:content
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 1119, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 1030, in _doRunImportStep
    return handler(context)
   - __traceback_info__: typeinfo
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/exportimport/typeinfo.py", line 225, in importTypesTool
    importObjects(tool, '', context)
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/utils.py", line 838, in importObjects
    importObjects(sub, path + '/', context)
   - __traceback_info__: portal_types
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/utils.py", line 834, in importObjects
    importer.body = body
   - __traceback_info__: types/Collection
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/utils.py", line 509, in _importBody
    self._importNode(dom.documentElement)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/exportimport/typeinfo.py", line 60, in _importNode
    self._initProperties(node)
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/utils.py", line 730, in _initProperties
    raise ValueError("undefined property '%s'" % prop_id)
ValueError: undefined property 'content_meta_type'

Running plone.app.folder.tests.layer.plone.app.folder testing:Partial ordering integration tests:
  Set up plone.app.testing.bbb.PloneTestCaseFixture Traceback (most recent call last):
  File "/home/timo/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 400, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/home/timo/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 708, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/timo/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 708, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/timo/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 708, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/timo/.buildout/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 713, in setup_layer
    layer.setUp()
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.testing/plone/app/testing/helpers.py", line 350, in setUp
    self.setUpPloneSite(portal)
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.testing/plone/app/testing/bbb.py", line 42, in setUpPloneSite
    testing.applyProfile(portal, 'Products.ATContentTypes:content')
  File "/home/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.testing/plone/app/testing/helpers.py", line 120, in applyProfile
    blacklisted_steps=blacklisted_steps)
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 365, in runAllImportStepsFromProfile
    blacklisted_steps=blacklisted_steps)
   - __traceback_info__: profile-Products.ATContentTypes:content
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 1119, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/tool.py", line 1030, in _doRunImportStep
    return handler(context)
   - __traceback_info__: typeinfo
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/exportimport/typeinfo.py", line 225, in importTypesTool
    importObjects(tool, '', context)
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/utils.py", line 838, in importObjects
    importObjects(sub, path + '/', context)
   - __traceback_info__: portal_types
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/utils.py", line 834, in importObjects
    importer.body = body
   - __traceback_info__: types/Collection
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/utils.py", line 509, in _importBody
    self._importNode(dom.documentElement)
  File "/home/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/exportimport/typeinfo.py", line 60, in _importNode
    self._initProperties(node)
  File "/home/timo/.buildout/eggs/Products.GenericSetup-1.7.5-py2.7.egg/Products/GenericSetup/utils.py", line 730, in _initProperties
    raise ValueError("undefined property '%s'" % prop_id)
ValueError: undefined property 'content_meta_type'

Running plone.testing.zca.UnitTesting tests:
  Tear down plone.app.testing.layers.PloneFixture in 0.018 seconds.
  Tear down plone.testing.z2.Startup in 0.002 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.002 seconds.
  Set up plone.testing.zca.UnitTesting in 0.000 seconds.
  Running:

  Ran 150 tests with 0 failures, 0 errors, 0 skipped in 0.129 seconds.
Running plone.caching.testing.ImplicitRulesetRegistryUnitTestingLayer tests:
  Set up plone.caching.testing.ImplicitRulesetRegistryUnitTestingLayer in 0.000 seconds.
  Running:

  Ran 14 tests with 0 failures, 0 errors, 0 skipped in 0.024 seconds.
Tearing down left over layers:
  Tear down plone.caching.testing.ImplicitRulesetRegistryUnitTestingLayer in 0.000 seconds.
  Tear down plone.testing.zca.UnitTesting in 0.000 seconds.
Total: 181 tests, 0 failures, 10 errors, 0 skipped in 14.403 seconds.
```

**Comment by jensens** [comment]
@pbauer did we solve this already in python 3?

**Comment by jensens** [comment]
This was fixed by https://github.com/plone/plone.app.folder/pull/21
