### ISSUE TITLE
Can't add a country-specific language variant Plone 5 site

### ISSUE THREAD

**Issue by davilima6** [plone/Products.CMFPlone#681]
Running vanilla coredev and using `@@add-plone-site` I can add Plone sites in English (en), Portuguese (pt) or Spanish (es) but if I try any of the country-specific language such as Portuguese Brazilian (pt-br) or Spanish (Spain) (es-es) [I get](http://pastebin.com/Ry6dWhYS):

```
2015-07-14 17:02:25 ERROR Zope.SiteErrorLog 1436904145.00.0964837101172 http://localhost:8080/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.browser.admin, line 232, in __call__
  Module Products.CMFPlone.factory, line 94, in addPloneSite
  Module plone.registry.registry, line 47, in __setitem__
  Module plone.registry.record, line 83, in _set_value
  Module zope.schema._bootstrapfields, line 182, in validate
  Module zope.schema._field, line 389, in _validate
ConstraintNotSatisfied: pt-br
```

Not only the site isn't created, if I try to access *_ANY_* URL in Zope (including `/manage_UndoForm`) I get:

```
2015-07-14 17:02:25 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/Users/davi/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in __init__
    response=b)
  File "/Users/davi/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/Users/davi/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/Users/davi/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/BaseRequest.py", line 218, in close
    notify(EndRequestEvent(None, self))
  File "/Users/davi/.buildout/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/Users/davi/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/Users/davi/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/davi/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
AttributeError: adapters
```

The only way out is deleting `Data.fs` and starting from scratch.

**Comment by tomgross** [comment]
Duplicate https://github.com/plone/Products.CMFPlone/issues/411
