### ISSUE TITLE
error while rendering plone.contentviews after installing Working Copy Support (Iterate) 

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#798]
**Resolved when Working Copy Support is uninstalled**

2015-08-05 09:29:38 INFO Zope Ready to handle requests
2015-08-05 09:29:41 INFO plone.app.theming.policy local cache invalidated on thread 4578684928
2015-08-05 09:29:41 INFO plone.app.theming.policy initializing local cache on thread 4578684928 for http://localhost:8080/Plone5::barceloneta
2015-08-05 09:29:41 ERROR plone.app.viewletmanager rendering of plone.toolbar in plone.contentviews fails: ('Could not adapt', <PloneSite at /Plone5>, <InterfaceClass plone.app.iterate.interfaces.ICheckinCheckoutPolicy>)

 - Expression: "provider:plone.contentmenu"
 - Filename:   ... .5.9-py2.7.egg/plone/app/layout/viewlets/contentviews.pt
 - Location:   (line 9: col 32)
 - Source:     ... :replace="structure provider:plone.contentmenu" />
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "view/menu"
 - Filename:   ... enu-2.1.5-py2.7.egg/plone/app/contentmenu/contentmenu.pt
 - Location:   (line 1: col 37)
 - Source:     ... tentactionmenus define="menu view/menu;"
                                                ^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x10e9d8a10>
               views: <ViewMapper - at 0x1105b5b90>
               modules: <instance - at 0x109bce518>
               args: <tuple - at 0x109200050>
               here: <ImplicitAcquisitionWrapper Plone5 at 0x10e15af00>
               user: <ImplicitAcquisitionWrapper - at 0x1102d04b0>
               nothing: <NoneType - at 0x1091657f8>
               container: <ImplicitAcquisitionWrapper Plone5 at 0x10e15af00>
               request: <instance - at 0x10e9cfb90>
               wrapped_repeat: <SafeMapping - at 0x10f4b4260>
               traverse_subpath: <list - at 0x10e54e6c8>
               default: <object - at 0x109257c00>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper Plone5 at 0x10e15af00>
               view: <ContentMenuProvider plone.contentmenu at 0x11061ccd0>
               translate: <function translate at 0x11129d7d0>
               root: <ImplicitAcquisitionWrapper Zope at 0x10e0f0a50>
               options: {...} (0)
               target_language: <NoneType - at 0x1091657f8>
Traceback (most recent call last):
  File "/Users/userID//Plone5/buildout-cache/eggs/plone.app.viewletmanager-2.0.8-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/Users/userID//Plone5/buildout-cache/eggs/plone.app.layout-2.5.9-py2.7.egg/plone/app/layout/viewlets/common.py", line 59, in render
    return self.index()
  File "/Users/userID//Plone5/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/Users/userID//Plone5/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/Users/userID//Plone5/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/Users/userID//Plone5/buildout-cache/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/Users/userID//Plone5/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/Users/userID//Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/Users/userID//Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "8af553c586904aca5f966245e9ed090e.py", line 157, in render
  File "/Users/userID//Plone5/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/expressions.py", line 74, in render_content_provider
    return cp.render()
  File "/Users/userID//Plone5/buildout-cache/eggs/plone.app.contentmenu-2.1.5-py2.7.egg/plone/app/contentmenu/view.py", line 20, in render
    return self.index()
  File "/Users/userID//Plone5/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/Users/userID//Plone5/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/Users/userID//Plone5/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/Users/userID//Plone5/buildout-cache/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/Users/userID//Plone5/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/Users/userID//Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/Users/userID//Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/Users/userID//Plone5/buildout-cache/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "d227d5843f56f1419eced36357f7c7b5.py", line 102, in render
  File "/Users/userID//Plone5/buildout-cache/eggs/five.pt-2.2.3-py2.7.egg/five/pt/expressions.py", line 161, in __call__
    return base()
  File "/Users/userID//Plone5/buildout-cache/eggs/plone.app.contentmenu-2.1.5-py2.7.egg/plone/app/contentmenu/view.py", line 29, in menu
    items = menu.getMenuItems(self.context, self.request)
  File "/Users/userID//Plone5/buildout-cache/eggs/zope.browsermenu-3.9.1-py2.7.egg/zope/browsermenu/menu.py", line 53, in getMenuItems
    if item.available():
  File "/Users/userID//Plone5/buildout-cache/eggs/plone.memoize-1.1.1-py2.7.egg/plone/memoize/instance.py", line 51, in memogetter
    val=func(*args, **kwargs)
  File "/Users/userID//Plone5/buildout-cache/eggs/plone.app.contentmenu-2.1.5-py2.7.egg/plone/app/contentmenu/menu.py", line 80, in available
    object=self.context, categories=('object_buttons',), max=1)
  File "/Users/userID//Plone5/buildout-cache/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/ActionsTool.py", line 80, in listActionInfos
    if check_condition and not ai['available']:
  File "/Users/userID//Plone5/buildout-cache/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/ActionInformation.py", line 206, in __getitem__
    value = self.data[key] = value(self._ec)
  File "/Users/userID//Plone5/buildout-cache/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/Expression.py", line 47, in __call__
    res = compiled(econtext)
  File "/Users/userID//Plone5/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/ZRPythonExpr.py", line 48, in __call__
    return eval(self._code, vars, {})
  File "PythonExpr", line 1, in <expression>
  File "/Users/userID//Plone5/buildout-cache/eggs/plone.memoize-1.1.1-py2.7.egg/plone/memoize/view.py", line 47, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/Users/userID/Plone5/buildout-cache/eggs/plone.app.iterate-3.1.0-py2.7.egg/plone/app/iterate/browser/control.py", line 93, in cancel_allowed
    policy = ICheckinCheckoutPolicy(self.context)
TypeError: ('Could not adapt', <PloneSite at /Plone5>, <InterfaceClass plone.app.iterate.interfaces.ICheckinCheckoutPolicy>)

 - Expression: "provider:plone.contentmenu"
 - Filename:   ... .5.9-py2.7.egg/plone/app/layout/viewlets/contentviews.pt
 - Location:   (line 9: col 32)
 - Source:     ... :replace="structure provider:plone.contentmenu" />
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "view/menu"
 - Filename:   ... enu-2.1.5-py2.7.egg/plone/app/contentmenu/contentmenu.pt
 - Location:   (line 1: col 37)
 - Source:     ... tentactionmenus define="menu view/menu;"
                                                ^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x10e9d8a10>
               views: <ViewMapper - at 0x1105b5b90>
               modules: <instance - at 0x109bce518>
               args: <tuple - at 0x109200050>
               here: <ImplicitAcquisitionWrapper Plone5 at 0x10e15af00>
               user: <ImplicitAcquisitionWrapper - at 0x1102d04b0>
               nothing: <NoneType - at 0x1091657f8>
               container: <ImplicitAcquisitionWrapper Plone5 at 0x10e15af00>
               request: <instance - at 0x10e9cfb90>
               wrapped_repeat: <SafeMapping - at 0x10f4b4260>
               traverse_subpath: <list - at 0x10e54e6c8>
               default: <object - at 0x109257c00>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper Plone5 at 0x10e15af00>
               view: <ContentMenuProvider plone.contentmenu at 0x11061ccd0>
               translate: <function translate at 0x11129d7d0>
               root: <ImplicitAcquisitionWrapper Zope at 0x10e0f0a50>
               options: {...} (0)
               target_language: <NoneType - at 0x1091657f8>

**Comment by vangheem** [comment]
already fixed here: https://github.com/plone/plone.app.iterate/commit/58b0f1aebe83fe08f5fc9fcf8df5fb8fe4b2773f
