### ISSUE TITLE
including barceloneta in a custom bundle fails

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#822]
When I create a custom theme in the filesystem and include the barceloneta-less in my own less-files like this:
```
@import "++theme++barceloneta/less/barceloneta.plone.less";
@import "kbo.less";
@import "kbo-fontello.less";
```
I get the traceback ``FileError: '++theme++barceloneta/less/barceloneta.plone.less' wasn't found``. It works fine when I remove the barceloneta-less. Here is the full traceback:
```
./bin/plone-compile-resources --site-id=Plone --bundle=kbo-bundle
Running command: /Users/philip/workspace/kbo/bin/instance run /Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/_scripts/_generate_gruntfile.py
2015-08-11 17:35:01 WARNING plone.behavior Specifying 'for' in behavior 'Locking' if no 'factory' is given has no effect and is superfluous.
2015-08-11 17:35:02 WARNING plone.behavior Specifying 'for' in behavior 'Name from Thema' if no 'factory' is given has no effect and is superfluous.
2015-08-11 17:35:02 WARNING plone.behavior Specifying 'for' in behavior 'KBO Custom ID Generation' if no 'factory' is given has no effect and is superfluous.
Using site id: Plone
Setup npm env
Running command: npm install
Running command: /usr/local/bin/grunt --gruntfile=/Users/philip/workspace/kbo/Gruntfile.js compile-kbo-bundle
Running "requirejs:kbo-bundle" (requirejs) task

Running "less:kbo-bundle" (less) task
>> FileError: '++theme++barceloneta/less/barceloneta.plone.less' wasn't found. Tried - /Users/philip/workspace/kbo/src/kbo.webapp/src/kbo/webapp/theme/less/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/static/components/bootstrap/less/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/static/components/dropzone/dist/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/static/components/jqtree/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/static/components/jquery.recurrenceinput.js/src/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/workspace/kbo/src/kbo.webapp/src/kbo/webapp/theme/less/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/autotoc/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/filemanager/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/livesearch/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/markspeciallinks/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/modal/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/pickadate/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/querystring/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/recurrence/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/relateditems/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/resourceregistry/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/select2/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/structure/less/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/thememapper/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/tinymce/less/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/tooltip/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/tree/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/patterns/upload/less/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/mockup-2.0.5-py2.7.egg/mockup/less/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/static/components/pickadate/lib/themes/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/static/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/static/patterns/toolbar/src/css/++theme++barceloneta/less/barceloneta.plone.less,temp_resources/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/static/components/jquery.recurrenceinput.js/lib/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/static/components/select2/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/plone.app.theming-1.2.7-py2.7.egg/plone/app/theming/browser/resources/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/static/components/tinymce-builded/js/tinymce/plugins/visualblocks/css/++theme++barceloneta/less/barceloneta.plone.less,/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/static/components/tinymce-builded/js/tinymce/skins/lightgray/++theme++barceloneta/less/barceloneta.plone.less,++theme++barceloneta/less/barceloneta.plone.less in /Users/philip/workspace/kbo/src/kbo.webapp/src/kbo/webapp/theme/less/kbo.plone.less on line 2, column 1:
>> 1 // This imports all kbo-related less and is compiled into bundle.css
>> 2 @import "++theme++barceloneta/less/barceloneta.plone.less";
>> 3 @import "kbo.less";
Warning: Error compiling /Users/philip/workspace/kbo/src/kbo.webapp/src/kbo/webapp/theme/less/kbo.plone.less Use --force to continue.

Aborted due to warnings.
Traceback (most recent call last):
  File "./bin/plone-compile-resources", line 269, in <module>
    sys.exit(Products.CMFPlone._scripts.compile_resources.main())
  File "/Users/philip/.cache/buildout/eggs/Products.CMFPlone-5.0b3-py2.7.egg/Products/CMFPlone/_scripts/compile_resources.py", line 87, in main
    subprocess.check_call(cmd)
  File "/Users/philip/workspace/buildout.python/parts/opt/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/grunt', '--gruntfile=/Users/philip/workspace/kbo/Gruntfile.js', 'compile-kbo-bundle']' returned non-zero exit status 6
```

**Comment by pbauer** [comment]
When I try it TTW and enable the css-debug-mode in resource-registries the site loads forever and I get a message that the script ``http://localhost:8080/Plone/++plone++static/components/less/dist/less.js:5270`` is not answering any more.

**Comment by MrTango** [comment]
A working solution for less files is, to use resource registry vars to include the resources:

    @import url("@{barceloneta-plone-less}");

But then we need to have that vars provided by the barceloneta theme, which is not the case by now.
But this could simply changed.

**Comment by MrTango** [comment]
the need registry file in plonetheme.barceloneta for that is:

   <?xml version="1.0"?>                                                                   
   <registry>                                                                              
                                                                         
    <records prefix="plone.resources/barceloneta-plone-less"                              
              interface='Products.CMFPlone.interfaces.IResourceRegistry'>                 
       <value key="css">                                                                  
          <element>++theme++barceloneta/less/barceloneta.plone.less</element>             
       </value>                                                                           
    </records>                                                                                                                                                                 
  </registry>

**Comment by MrTango** [comment]
If have create an updated approach, see the PR here for details: https://github.com/plone/plonetheme.barceloneta/pull/37

**Comment by vangheem** [comment]
I'm okay with the PR. @pbauer did you have problems with it? Go ahead an merge if not.

**Comment by pbauer** [comment]
Merged. The '"process out of memory"-problem I have (see https://github.com/plone/plonetheme.barceloneta/pull/37#issuecomment-135685441) is no issue fo the new resource but rather of the gruntfile.

**Comment by pbauer** [comment]
Will be fixed by https://github.com/plone/plonetheme.barceloneta/pull/51
